export interface ArabicWord {
  arabic: string;
  transliteration: string;
  meaning_hi: string;
  meaning_hinglish: string;
  meaning_en: string;
}

const EASY_WORDS: ArabicWord[] = [
  { arabic: "اللَّه", transliteration: "Allah", meaning_hi: "अल्लाह (ईश्वर)", meaning_hinglish: "Allah (Bhagwan)", meaning_en: "God" },
  { arabic: "رَبّ", transliteration: "Rabb", meaning_hi: "पालनहार", meaning_hinglish: "Palanhar (Lord)", meaning_en: "Lord" },
  { arabic: "قَالَ", transliteration: "Qaala", meaning_hi: "उसने कहा", meaning_hinglish: "Usne kaha", meaning_en: "He said" },
  { arabic: "كَانَ", transliteration: "Kaana", meaning_hi: "वह था", meaning_hinglish: "Woh tha", meaning_en: "He was" },
  { arabic: "مِنْ", transliteration: "Min", meaning_hi: "से", meaning_hinglish: "Se (from)", meaning_en: "From" },
  { arabic: "فِي", transliteration: "Fee", meaning_hi: "में", meaning_hinglish: "Mein (in)", meaning_en: "In" },
  { arabic: "عَلَى", transliteration: "Ala", meaning_hi: "ऊपर / पर", meaning_hinglish: "Upar / Par", meaning_en: "Upon/On" },
  { arabic: "إِلَى", transliteration: "Ila", meaning_hi: "की ओर", meaning_hinglish: "Ki taraf", meaning_en: "To/Towards" },
  { arabic: "مَا", transliteration: "Maa", meaning_hi: "क्या / नहीं", meaning_hinglish: "Kya / Nahi", meaning_en: "What/Not" },
  { arabic: "لَا", transliteration: "Laa", meaning_hi: "नहीं", meaning_hinglish: "Nahi", meaning_en: "No/Not" },
  { arabic: "إِنَّ", transliteration: "Inna", meaning_hi: "निश्चय ही", meaning_hinglish: "Nishchay hi (beshak)", meaning_en: "Indeed" },
  { arabic: "هُوَ", transliteration: "Huwa", meaning_hi: "वह (पुल्लिंग)", meaning_hinglish: "Woh (he)", meaning_en: "He" },
  { arabic: "وَ", transliteration: "Wa", meaning_hi: "और", meaning_hinglish: "Aur", meaning_en: "And" },
  { arabic: "الَّذِي", transliteration: "Alladhi", meaning_hi: "जो / जिसने", meaning_hinglish: "Jo / Jisne", meaning_en: "Who/Which" },
  { arabic: "أَنَّ", transliteration: "Anna", meaning_hi: "कि", meaning_hinglish: "Ki (that)", meaning_en: "That" },
  { arabic: "هُمْ", transliteration: "Hum", meaning_hi: "वे लोग", meaning_hinglish: "Woh log", meaning_en: "They" },
  { arabic: "لَهُ", transliteration: "Lahu", meaning_hi: "उसके लिए", meaning_hinglish: "Uske liye", meaning_en: "For him" },
  { arabic: "بِ", transliteration: "Bi", meaning_hi: "के साथ / द्वारा", meaning_hinglish: "Ke saath / Dwara", meaning_en: "With/By" },
  { arabic: "كُلّ", transliteration: "Kull", meaning_hi: "हर / सब", meaning_hinglish: "Har / Sab", meaning_en: "Every/All" },
  { arabic: "يَوْم", transliteration: "Yawm", meaning_hi: "दिन", meaning_hinglish: "Din (day)", meaning_en: "Day" },
  { arabic: "أَرْض", transliteration: "Ard", meaning_hi: "धरती", meaning_hinglish: "Dharti / Zameen", meaning_en: "Earth" },
  { arabic: "سَمَاء", transliteration: "Samaa", meaning_hi: "आकाश", meaning_hinglish: "Aasmaan", meaning_en: "Sky/Heaven" },
  { arabic: "نَاس", transliteration: "Naas", meaning_hi: "लोग", meaning_hinglish: "Log", meaning_en: "People" },
  { arabic: "قَوْم", transliteration: "Qawm", meaning_hi: "क़ौम / जाति", meaning_hinglish: "Qaum / Jaati", meaning_en: "Nation/People" },
  { arabic: "عِلْم", transliteration: "Ilm", meaning_hi: "ज्ञान", meaning_hinglish: "Gyaan / Ilm", meaning_en: "Knowledge" },
  { arabic: "كِتَاب", transliteration: "Kitaab", meaning_hi: "किताब", meaning_hinglish: "Kitaab", meaning_en: "Book" },
  { arabic: "آيَة", transliteration: "Aayah", meaning_hi: "निशानी / आयत", meaning_hinglish: "Nishaani / Aayat", meaning_en: "Sign/Verse" },
  { arabic: "نَبِيّ", transliteration: "Nabi", meaning_hi: "नबी (पैग़म्बर)", meaning_hinglish: "Nabi (Paighambar)", meaning_en: "Prophet" },
  { arabic: "رَسُول", transliteration: "Rasool", meaning_hi: "रसूल (दूत)", meaning_hinglish: "Rasool (Doot)", meaning_en: "Messenger" },
  { arabic: "مُؤْمِن", transliteration: "Mu'min", meaning_hi: "ईमान वाला", meaning_hinglish: "Imaan wala (Believer)", meaning_en: "Believer" },
  { arabic: "صَلَاة", transliteration: "Salaah", meaning_hi: "नमाज़", meaning_hinglish: "Namaaz", meaning_en: "Prayer" },
  { arabic: "حَقّ", transliteration: "Haqq", meaning_hi: "सत्य / हक़", meaning_hinglish: "Sach / Haqq", meaning_en: "Truth/Right" },
  { arabic: "دِين", transliteration: "Deen", meaning_hi: "धर्म / दीन", meaning_hinglish: "Dharm / Deen", meaning_en: "Religion/Way of life" },
  { arabic: "رَحْمَة", transliteration: "Rahmah", meaning_hi: "दया / रहमत", meaning_hinglish: "Daya / Rehmat", meaning_en: "Mercy" },
  { arabic: "عَذَاب", transliteration: "Adhaab", meaning_hi: "अज़ाब (दंड)", meaning_hinglish: "Azaab (Sazaa)", meaning_en: "Punishment" },
  { arabic: "جَنَّة", transliteration: "Jannah", meaning_hi: "जन्नत (स्वर्ग)", meaning_hinglish: "Jannat (Swarg)", meaning_en: "Paradise" },
  { arabic: "نَار", transliteration: "Naar", meaning_hi: "आग / जहन्नम", meaning_hinglish: "Aag / Jahannam", meaning_en: "Fire/Hell" },
  { arabic: "مَاء", transliteration: "Maa'", meaning_hi: "पानी", meaning_hinglish: "Paani", meaning_en: "Water" },
  { arabic: "خَيْر", transliteration: "Khayr", meaning_hi: "भलाई", meaning_hinglish: "Bhalaai / Khayr", meaning_en: "Good" },
  { arabic: "شَرّ", transliteration: "Sharr", meaning_hi: "बुराई", meaning_hinglish: "Buraai / Sharr", meaning_en: "Evil" },
  { arabic: "ذِكْر", transliteration: "Dhikr", meaning_hi: "याद / ज़िक्र", meaning_hinglish: "Yaad / Zikr", meaning_en: "Remembrance" },
  { arabic: "شَيْء", transliteration: "Shay'", meaning_hi: "चीज़", meaning_hinglish: "Cheez", meaning_en: "Thing" },
  { arabic: "أَهْل", transliteration: "Ahl", meaning_hi: "परिवार / वाले", meaning_hinglish: "Parivaar / Wale", meaning_en: "Family/People of" },
  { arabic: "بَعْد", transliteration: "Ba'd", meaning_hi: "बाद में", meaning_hinglish: "Baad mein", meaning_en: "After" },
  { arabic: "قَبْل", transliteration: "Qabl", meaning_hi: "पहले", meaning_hinglish: "Pehle", meaning_en: "Before" },
  { arabic: "عِنْد", transliteration: "Inda", meaning_hi: "पास / के यहाँ", meaning_hinglish: "Paas / Ke yahaan", meaning_en: "At/Near" },
  { arabic: "بَيْن", transliteration: "Bayn", meaning_hi: "बीच में", meaning_hinglish: "Beech mein", meaning_en: "Between" },
  { arabic: "ثُمَّ", transliteration: "Thumma", meaning_hi: "फिर", meaning_hinglish: "Phir", meaning_en: "Then" },
  { arabic: "حَتَّى", transliteration: "Hatta", meaning_hi: "यहाँ तक कि", meaning_hinglish: "Yahaan tak ki", meaning_en: "Until" },
  { arabic: "أَوْ", transliteration: "Aw", meaning_hi: "या", meaning_hinglish: "Ya (or)", meaning_en: "Or" },
];

const MEDIUM_WORDS: ArabicWord[] = [
  { arabic: "تَوْبَة", transliteration: "Tawbah", meaning_hi: "तौबा (पश्चाताप)", meaning_hinglish: "Taubah (Pashchataap)", meaning_en: "Repentance" },
  { arabic: "صَبْر", transliteration: "Sabr", meaning_hi: "धैर्य / सब्र", meaning_hinglish: "Dhairya / Sabr", meaning_en: "Patience" },
  { arabic: "شُكْر", transliteration: "Shukr", meaning_hi: "कृतज्ञता / शुक्र", meaning_hinglish: "Shukriya / Shukr", meaning_en: "Gratitude" },
  { arabic: "تَقْوَى", transliteration: "Taqwa", meaning_hi: "ईश्वर-चेतना", meaning_hinglish: "Khuda se darna / Taqwa", meaning_en: "God-consciousness" },
  { arabic: "أَمَانَة", transliteration: "Amaanah", meaning_hi: "अमानत (विश्वास)", meaning_hinglish: "Amaanat (Vishwaas)", meaning_en: "Trust" },
  { arabic: "عَدْل", transliteration: "Adl", meaning_hi: "न्याय / इन्साफ़", meaning_hinglish: "Nyaay / Insaaf", meaning_en: "Justice" },
  { arabic: "ظُلْم", transliteration: "Dhulm", meaning_hi: "अत्याचार / ज़ुल्म", meaning_hinglish: "Atyaachaar / Zulm", meaning_en: "Oppression" },
  { arabic: "نُور", transliteration: "Noor", meaning_hi: "प्रकाश / नूर", meaning_hinglish: "Rooshni / Noor", meaning_en: "Light" },
  { arabic: "ظَلَام", transliteration: "Dhalaam", meaning_hi: "अंधेरा", meaning_hinglish: "Andhera", meaning_en: "Darkness" },
  { arabic: "هِدَايَة", transliteration: "Hidaayah", meaning_hi: "मार्गदर्शन / हिदायत", meaning_hinglish: "Raasta dikhana / Hidaayat", meaning_en: "Guidance" },
  { arabic: "ضَلَال", transliteration: "Dhalaal", meaning_hi: "गुमराही / भटकाव", meaning_hinglish: "Gumraahi / Bhatkaav", meaning_en: "Misguidance" },
  { arabic: "مَلَك", transliteration: "Malak", meaning_hi: "फ़रिश्ता", meaning_hinglish: "Farishta", meaning_en: "Angel" },
  { arabic: "شَيْطَان", transliteration: "Shaytaan", meaning_hi: "शैतान", meaning_hinglish: "Shaitaan", meaning_en: "Satan" },
  { arabic: "رِزْق", transliteration: "Rizq", meaning_hi: "रोज़ी / जीविका", meaning_hinglish: "Rozi / Jeevika", meaning_en: "Provision" },
  { arabic: "دُعَاء", transliteration: "Du'aa", meaning_hi: "दुआ (प्रार्थना)", meaning_hinglish: "Dua (Praarthna)", meaning_en: "Supplication" },
  { arabic: "عِبَادَة", transliteration: "Ibaadah", meaning_hi: "इबादत (पूजा)", meaning_hinglish: "Ibaadat (Pooja)", meaning_en: "Worship" },
  { arabic: "زَكَاة", transliteration: "Zakaah", meaning_hi: "ज़कात (दान)", meaning_hinglish: "Zakaat (Daan)", meaning_en: "Charity" },
  { arabic: "صَوْم", transliteration: "Sawm", meaning_hi: "रोज़ा (उपवास)", meaning_hinglish: "Roza (Upvaas)", meaning_en: "Fasting" },
  { arabic: "حَجّ", transliteration: "Hajj", meaning_hi: "हज (तीर्थयात्रा)", meaning_hinglish: "Hajj (Teerthyaatra)", meaning_en: "Pilgrimage" },
  { arabic: "جِهَاد", transliteration: "Jihaad", meaning_hi: "जिहाद (संघर्ष)", meaning_hinglish: "Jihaad (Sangharsh)", meaning_en: "Striving" },
  { arabic: "أَمْر", transliteration: "Amr", meaning_hi: "आदेश / हुक्म", meaning_hinglish: "Aadesh / Hukm", meaning_en: "Command" },
  { arabic: "نَهْي", transliteration: "Nahy", meaning_hi: "मनाही / निषेध", meaning_hinglish: "Manaahi / Nishedh", meaning_en: "Prohibition" },
  { arabic: "حَلَال", transliteration: "Halaal", meaning_hi: "हलाल (जायज़)", meaning_hinglish: "Halaal (Jaayaz)", meaning_en: "Permissible" },
  { arabic: "حَرَام", transliteration: "Haraam", meaning_hi: "हराम (वर्जित)", meaning_hinglish: "Haraam (Varjit)", meaning_en: "Forbidden" },
  { arabic: "وَعْد", transliteration: "Wa'd", meaning_hi: "वादा", meaning_hinglish: "Vaada", meaning_en: "Promise" },
  { arabic: "عَهْد", transliteration: "Ahd", meaning_hi: "अहद (वचन)", meaning_hinglish: "Ahd (Vachan)", meaning_en: "Covenant" },
  { arabic: "مِيثَاق", transliteration: "Meethaaq", meaning_hi: "मीसाक़ (समझौता)", meaning_hinglish: "Meethaaq (Samjhauta)", meaning_en: "Pact" },
  { arabic: "فِتْنَة", transliteration: "Fitnah", meaning_hi: "फ़ितना (आज़माइश)", meaning_hinglish: "Fitna (Aazmaish)", meaning_en: "Trial" },
  { arabic: "بَلَاء", transliteration: "Balaa", meaning_hi: "बला (परीक्षा)", meaning_hinglish: "Balaa (Pareeksha)", meaning_en: "Test" },
  { arabic: "أَجْر", transliteration: "Ajr", meaning_hi: "अज्र (प्रतिफल)", meaning_hinglish: "Ajr (Pratifal)", meaning_en: "Reward" },
  { arabic: "ثَوَاب", transliteration: "Thawaab", meaning_hi: "सवाब (पुण्य)", meaning_hinglish: "Sawaab (Punya)", meaning_en: "Reward" },
  { arabic: "إِيمَان", transliteration: "Imaan", meaning_hi: "ईमान (विश्वास)", meaning_hinglish: "Imaan (Vishwaas)", meaning_en: "Faith" },
  { arabic: "كُفْر", transliteration: "Kufr", meaning_hi: "कुफ़्र (अविश्वास)", meaning_hinglish: "Kufr (Avishwaas)", meaning_en: "Disbelief" },
  { arabic: "إِسْلَام", transliteration: "Islaam", meaning_hi: "इस्लाम (समर्पण)", meaning_hinglish: "Islaam (Samarpan)", meaning_en: "Submission" },
  { arabic: "مُسْلِم", transliteration: "Muslim", meaning_hi: "मुस्लिम (समर्पित)", meaning_hinglish: "Muslim (Samarpan karne wala)", meaning_en: "One who submits" },
  { arabic: "تَوْحِيد", transliteration: "Tawheed", meaning_hi: "तौहीद (एकेश्वरवाद)", meaning_hinglish: "Tawheed (Ekeshwarwaad)", meaning_en: "Monotheism" },
  { arabic: "شِرْك", transliteration: "Shirk", meaning_hi: "शिर्क (बहुदेववाद)", meaning_hinglish: "Shirk (Bahudevwaad)", meaning_en: "Polytheism" },
  { arabic: "سُنَّة", transliteration: "Sunnah", meaning_hi: "सुन्नत (तरीक़ा)", meaning_hinglish: "Sunnat (Tareeka)", meaning_en: "Way/Practice" },
  { arabic: "حِكْمَة", transliteration: "Hikmah", meaning_hi: "हिकमत (बुद्धिमत्ता)", meaning_hinglish: "Hikmat (Buddhimatta)", meaning_en: "Wisdom" },
  { arabic: "بَصِيرَة", transliteration: "Baseerah", meaning_hi: "बसीरत (अंतर्दृष्टि)", meaning_hinglish: "Baseerat (Antardrishti)", meaning_en: "Insight" },
  { arabic: "فُرْقَان", transliteration: "Furqaan", meaning_hi: "फ़ुरक़ान (कसौटी)", meaning_hinglish: "Furqaan (Kasauti)", meaning_en: "Criterion" },
  { arabic: "مَغْفِرَة", transliteration: "Maghfirah", meaning_hi: "मग़फ़िरत (क्षमा)", meaning_hinglish: "Maghfirat (Kshama)", meaning_en: "Forgiveness" },
  { arabic: "سَلَام", transliteration: "Salaam", meaning_hi: "सलाम (शांति)", meaning_hinglish: "Salaam (Shaanti)", meaning_en: "Peace" },
  { arabic: "بَرَكَة", transliteration: "Barakah", meaning_hi: "बरकत (आशीर्वाद)", meaning_hinglish: "Barkat (Aashirwaad)", meaning_en: "Blessing" },
  { arabic: "نِعْمَة", transliteration: "Ni'mah", meaning_hi: "नेमत (अनुग्रह)", meaning_hinglish: "Nemat (Anugrah)", meaning_en: "Favor" },
  { arabic: "شَفَاعَة", transliteration: "Shafaa'ah", meaning_hi: "शफ़ाअत (सिफ़ारिश)", meaning_hinglish: "Shafaa'at (Sifarish)", meaning_en: "Intercession" },
  { arabic: "مِيزَان", transliteration: "Meezaan", meaning_hi: "मीज़ान (तराज़ू)", meaning_hinglish: "Meezaan (Taraazu)", meaning_en: "Balance/Scale" },
  { arabic: "صِرَاط", transliteration: "Siraat", meaning_hi: "सिरात (रास्ता)", meaning_hinglish: "Siraat (Raasta)", meaning_en: "Path" },
  { arabic: "مُسْتَقِيم", transliteration: "Mustaqeem", meaning_hi: "सीधा", meaning_hinglish: "Seedha (Straight)", meaning_en: "Straight" },
  { arabic: "هُدَى", transliteration: "Huda", meaning_hi: "हिदायत (मार्गदर्शन)", meaning_hinglish: "Hidaayat (Maargdarshan)", meaning_en: "Guidance" },
];

const HARD_WORDS: ArabicWord[] = [
  { arabic: "خَشْيَة", transliteration: "Khashyah", meaning_hi: "ख़शियत (भय/विस्मय)", meaning_hinglish: "Khashiyat (Bhay/Vismay)", meaning_en: "Awe/Fear" },
  { arabic: "خُشُوع", transliteration: "Khushoo'", meaning_hi: "ख़ुशू (विनम्रता)", meaning_hinglish: "Khushoo (Vinamrata)", meaning_en: "Humility in worship" },
  { arabic: "وَرَع", transliteration: "Wara'", meaning_hi: "वरअ (परहेज़गारी)", meaning_hinglish: "Wara (Parhezgaari)", meaning_en: "Piety" },
  { arabic: "زُهْد", transliteration: "Zuhd", meaning_hi: "ज़ुह्द (वैराग्य)", meaning_hinglish: "Zuhd (Vairaagya)", meaning_en: "Asceticism" },
  { arabic: "إِخْلَاص", transliteration: "Ikhlaas", meaning_hi: "इख़्लास (निष्ठा)", meaning_hinglish: "Ikhlaas (Nishtha)", meaning_en: "Sincerity" },
  { arabic: "يَقِين", transliteration: "Yaqeen", meaning_hi: "यक़ीन (निश्चितता)", meaning_hinglish: "Yaqeen (Nishchitata)", meaning_en: "Certainty" },
  { arabic: "تَوَكُّل", transliteration: "Tawakkul", meaning_hi: "तवक्कुल (ईश्वर पर भरोसा)", meaning_hinglish: "Tawakkul (Allah par bharosa)", meaning_en: "Reliance on God" },
  { arabic: "رِضَا", transliteration: "Rida", meaning_hi: "रिज़ा (संतोष)", meaning_hinglish: "Riza (Santosh)", meaning_en: "Contentment" },
  { arabic: "قَنَاعَة", transliteration: "Qana'ah", meaning_hi: "क़नाअत (संतुष्टि)", meaning_hinglish: "Qanaa'at (Santushti)", meaning_en: "Contentment" },
  { arabic: "مُرَاقَبَة", transliteration: "Muraaqabah", meaning_hi: "मुराक़बा (आत्म-निगरानी)", meaning_hinglish: "Muraaqaba (Aatm-nigraani)", meaning_en: "Self-vigilance" },
  { arabic: "مُحَاسَبَة", transliteration: "Muhaasabah", meaning_hi: "मुहासबा (आत्म-लेखा)", meaning_hinglish: "Muhaasaba (Aatm-lekha)", meaning_en: "Self-accounting" },
  { arabic: "اِسْتِغْفَار", transliteration: "Istighfaar", meaning_hi: "इस्तिग़फ़ार (क्षमा माँगना)", meaning_hinglish: "Istighfaar (Kshama maangna)", meaning_en: "Seeking forgiveness" },
  { arabic: "تَسْبِيح", transliteration: "Tasbeeh", meaning_hi: "तसबीह (महिमागान)", meaning_hinglish: "Tasbeeh (Mahimaagaan)", meaning_en: "Glorification" },
  { arabic: "تَهْلِيل", transliteration: "Tahleel", meaning_hi: "तहलील (एकता की घोषणा)", meaning_hinglish: "Tahleel (Ekta ki ghoshna)", meaning_en: "Declaration of oneness" },
  { arabic: "تَكْبِير", transliteration: "Takbeer", meaning_hi: "तकबीर (महानता की घोषणा)", meaning_hinglish: "Takbeer (Mahaanta ki ghoshna)", meaning_en: "Declaring greatness" },
  { arabic: "حَمْد", transliteration: "Hamd", meaning_hi: "हम्द (स्तुति)", meaning_hinglish: "Hamd (Stuti)", meaning_en: "Praise" },
  { arabic: "فَلَاح", transliteration: "Falaah", meaning_hi: "फ़लाह (सफलता)", meaning_hinglish: "Falaah (Safalta)", meaning_en: "Success" },
  { arabic: "خُسْرَان", transliteration: "Khusraan", meaning_hi: "ख़ुसरान (हानि)", meaning_hinglish: "Khusraan (Haani)", meaning_en: "Loss" },
  { arabic: "غَفْلَة", transliteration: "Ghaflah", meaning_hi: "ग़फ़लत (लापरवाही)", meaning_hinglish: "Ghaflat (Laaparwaahi)", meaning_en: "Heedlessness" },
  { arabic: "رِيَاء", transliteration: "Riyaa", meaning_hi: "रिया (दिखावा)", meaning_hinglish: "Riyaa (Dikhaawa)", meaning_en: "Showing off" },
  { arabic: "كِبْر", transliteration: "Kibr", meaning_hi: "किब्र (घमंड)", meaning_hinglish: "Kibr (Ghamand)", meaning_en: "Arrogance" },
  { arabic: "حَسَد", transliteration: "Hasad", meaning_hi: "हसद (ईर्ष्या)", meaning_hinglish: "Hasad (Irshya)", meaning_en: "Envy" },
  { arabic: "بُغْض", transliteration: "Bughd", meaning_hi: "बुग़्ज़ (घृणा)", meaning_hinglish: "Bughz (Ghrina)", meaning_en: "Hatred" },
  { arabic: "سَخَاء", transliteration: "Sakhaa", meaning_hi: "सख़ावत (उदारता)", meaning_hinglish: "Sakhaawat (Udaarta)", meaning_en: "Generosity" },
  { arabic: "عِفَّة", transliteration: "Iffah", meaning_hi: "इफ़्फ़त (पवित्रता)", meaning_hinglish: "Iffat (Pavitrata)", meaning_en: "Chastity" },
  { arabic: "حَيَاء", transliteration: "Hayaa", meaning_hi: "हया (लज्जा)", meaning_hinglish: "Hayaa (Lajja)", meaning_en: "Modesty" },
  { arabic: "تَوَاضُع", transliteration: "Tawaadu'", meaning_hi: "तवाज़ुअ (विनम्रता)", meaning_hinglish: "Tawaazu (Vinamrata)", meaning_en: "Humility" },
  { arabic: "سَكِينَة", transliteration: "Sakeenah", meaning_hi: "सकीना (शांति)", meaning_hinglish: "Sakeena (Shaanti)", meaning_en: "Tranquility" },
  { arabic: "اِطْمِئْنَان", transliteration: "Itmi'naan", meaning_hi: "इत्मीनान (स्थिरता)", meaning_hinglish: "Itmi'naan (Sthirta)", meaning_en: "Serenity" },
  { arabic: "بَيْعَة", transliteration: "Bay'ah", meaning_hi: "बैअत (प्रतिज्ञा)", meaning_hinglish: "Bai'at (Pratigya)", meaning_en: "Pledge" },
  { arabic: "خِلَافَة", transliteration: "Khilaafah", meaning_hi: "ख़िलाफ़त (उत्तराधिकार)", meaning_hinglish: "Khilaafat (Uttaraadhikaar)", meaning_en: "Succession" },
  { arabic: "أُمَّة", transliteration: "Ummah", meaning_hi: "उम्मत (समुदाय)", meaning_hinglish: "Ummat (Samudaay)", meaning_en: "Nation/Community" },
  { arabic: "شُورَى", transliteration: "Shoora", meaning_hi: "शूरा (परामर्श)", meaning_hinglish: "Shoora (Paraamarsh)", meaning_en: "Consultation" },
  { arabic: "عَقِيدَة", transliteration: "Aqeedah", meaning_hi: "अक़ीदा (विश्वास)", meaning_hinglish: "Aqeeda (Vishwaas)", meaning_en: "Creed" },
  { arabic: "مَنْهَج", transliteration: "Manhaj", meaning_hi: "मन्हज (कार्यप्रणाली)", meaning_hinglish: "Manhaj (Kaaryapranali)", meaning_en: "Methodology" },
  { arabic: "فِقْه", transliteration: "Fiqh", meaning_hi: "फ़िक़्ह (धार्मिक न्यायशास्त्र)", meaning_hinglish: "Fiqh (Dharmik Nyaayshastra)", meaning_en: "Jurisprudence" },
  { arabic: "تَفْسِير", transliteration: "Tafseer", meaning_hi: "तफ़सीर (व्याख्या)", meaning_hinglish: "Tafseer (Vyaakhya)", meaning_en: "Exegesis" },
  { arabic: "تَجْوِيد", transliteration: "Tajweed", meaning_hi: "तजवीद (शुद्ध पाठ)", meaning_hinglish: "Tajweed (Shuddh Paath)", meaning_en: "Proper recitation" },
  { arabic: "حُرُوف", transliteration: "Huroof", meaning_hi: "हुरूफ़ (अक्षर)", meaning_hinglish: "Huroof (Akshar)", meaning_en: "Letters" },
  { arabic: "تِلَاوَة", transliteration: "Tilaawah", meaning_hi: "तिलावत (पाठ)", meaning_hinglish: "Tilaawat (Paath)", meaning_en: "Recitation" },
  { arabic: "وَحْي", transliteration: "Wahy", meaning_hi: "वह्य (प्रकटीकरण)", meaning_hinglish: "Wahy (Prakatikaran)", meaning_en: "Revelation" },
  { arabic: "سُورَة", transliteration: "Soorah", meaning_hi: "सूरह (अध्याय)", meaning_hinglish: "Soorah (Adhyaay)", meaning_en: "Chapter" },
  { arabic: "مُصْحَف", transliteration: "Mushaf", meaning_hi: "मुसहफ़ (लिखित क़ुरआन)", meaning_hinglish: "Mushaf (Likhit Quran)", meaning_en: "Written Quran" },
  { arabic: "حَافِظ", transliteration: "Haafidh", meaning_hi: "हाफ़िज़ (याद करने वाला)", meaning_hinglish: "Haafiz (Yaad karne wala)", meaning_en: "Memorizer" },
  { arabic: "قَارِئ", transliteration: "Qaari", meaning_hi: "क़ारी (पढ़ने वाला)", meaning_hinglish: "Qaari (Padhne wala)", meaning_en: "Reciter" },
  { arabic: "عَالِم", transliteration: "Aalim", meaning_hi: "आलिम (विद्वान)", meaning_hinglish: "Aalim (Vidwaan)", meaning_en: "Scholar" },
  { arabic: "مُجْتَهِد", transliteration: "Mujtahid", meaning_hi: "मुज्तहिद (प्रयत्नशील विद्वान)", meaning_hinglish: "Mujtahid (Prayatnasheel Vidwaan)", meaning_en: "Scholar of effort" },
  { arabic: "فَتْوَى", transliteration: "Fatwa", meaning_hi: "फ़तवा (धार्मिक निर्णय)", meaning_hinglish: "Fatwa (Dharmik Nirnay)", meaning_en: "Religious ruling" },
  { arabic: "إِجْمَاع", transliteration: "Ijmaa", meaning_hi: "इज्मा (सर्वसम्मति)", meaning_hinglish: "Ijmaa (Sarvasammati)", meaning_en: "Consensus" },
  { arabic: "قِيَاس", transliteration: "Qiyaas", meaning_hi: "क़ियास (अनुमान)", meaning_hinglish: "Qiyaas (Anumaan)", meaning_en: "Analogical reasoning" },
];

export const WORD_LEVELS: Record<"easy" | "medium" | "hard", ArabicWord[]> = {
  easy: EASY_WORDS,
  medium: MEDIUM_WORDS,
  hard: HARD_WORDS,
};
