export interface Dua {
  id: number;
  arabic: string;
  transliteration: string;
  meaning_hi: string;
  meaning_hinglish: string;
  meaning_en: string;
  reference: string;
  category: string;
}

export const DUA_CATEGORIES: string[] = [
  "Morning & Evening",
  "Salah",
  "Food & Drink",
  "Travel",
  "Sleep",
  "Masjid",
  "Protection",
  "Forgiveness",
  "General",
];

export const DUAS: Dua[] = [
  // ═══════════════════ Morning & Evening ═══════════════════
  { id: 1, arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", transliteration: "Asbahna wa asbahal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadeer", meaning_hi: "हमने सुबह की और सारी बादशाही अल्लाह की है और सारी तारीफ़ अल्लाह के लिए है, अल्लाह के सिवा कोई माबूद नहीं, वह अकेला है, उसका कोई शरीक नहीं, उसी की बादशाही है और उसी की तारीफ़ है और वह हर चीज़ पर क़ादिर है", meaning_hinglish: "Humne subah ki aur saari baadshahi Allah ki hai aur saari tareef Allah ke liye hai, Allah ke siwa koi mabood nahi, woh akela hai, uska koi shareek nahi, usi ki baadshahi hai aur usi ki tareef hai aur woh har cheez par qaadir hai", meaning_en: "We have entered the morning and the dominion belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah alone, with no partner. To Him belongs the dominion and all praise, and He is over all things capable.", reference: "Muslim 2723", category: "Morning & Evening" },
  { id: 2, arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ", transliteration: "Allahumma bika asbahna wa bika amsayna, wa bika nahya wa bika namootu wa ilaykan-nushoor", meaning_hi: "ऐ अल्लाह! तेरे ही सहारे हमने सुबह की और तेरे ही सहारे हमने शाम की, तेरे ही सहारे हम जीते हैं और तेरे ही सहारे हम मरते हैं और तेरी ही तरफ़ लौटना है", meaning_hinglish: "Ae Allah! Tere hi sahare humne subah ki aur tere hi sahare humne shaam ki, tere hi sahare hum jeete hain aur tere hi sahare hum marte hain aur teri hi taraf lautna hai", meaning_en: "O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.", reference: "Tirmidhi 3391", category: "Morning & Evening" },
  { id: 3, arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", transliteration: "SubhanAllahi wa bihamdihi", meaning_hi: "अल्लाह पाक है अपनी तारीफ़ के साथ", meaning_hinglish: "Allah paak hai apni tareef ke saath", meaning_en: "Glory is to Allah and praise is to Him.", reference: "Muslim 2692 (100 times morning/evening)", category: "Morning & Evening" },
  { id: 4, arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadeer", meaning_hi: "अल्लाह के सिवा कोई माबूद नहीं, वह अकेला है, उसका कोई शरीक नहीं, उसी की बादशाही है और उसी की तारीफ़ है और वह हर चीज़ पर क़ादिर है", meaning_hinglish: "Allah ke siwa koi mabood nahi, woh akela hai, uska koi shareek nahi, usi ki baadshahi hai aur usi ki tareef hai aur woh har cheez par qaadir hai", meaning_en: "None has the right to be worshipped except Allah alone, with no partner. To Him belongs the dominion and all praise, and He is over all things capable.", reference: "Bukhari 3293 (100 times daily)", category: "Morning & Evening" },
  { id: 5, arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ", transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq", meaning_hi: "मैं अल्लाह के मुकम्मल कलिमात की पनाह लेता हूँ हर उस चीज़ के शर से जो उसने पैदा की", meaning_hinglish: "Main Allah ke mukammal kalimaat ki panah leta hoon har us cheez ke shar se jo usne paida ki", meaning_en: "I seek refuge in the perfect words of Allah from the evil of what He has created.", reference: "Muslim 2708 (3 times evening)", category: "Morning & Evening" },
  { id: 6, arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ", transliteration: "Bismillahilladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-Samee'ul-'Aleem", meaning_hi: "अल्लाह के नाम से जिसके नाम के साथ ज़मीन और आसमान में कोई चीज़ नुक़सान नहीं पहुँचा सकती और वह सुनने वाला जानने वाला है", meaning_hinglish: "Allah ke naam se jiske naam ke saath zameen aur aasmaan mein koi cheez nuqsaan nahi pahuncha sakti aur woh sunne wala jaanne wala hai", meaning_en: "In the name of Allah, with whose name nothing on earth or in the heavens can cause harm, and He is the All-Hearing, All-Knowing.", reference: "Abu Dawud 5088 (3 times morning/evening)", category: "Morning & Evening" },
  { id: 7, arabic: "رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا", transliteration: "Radheetu billahi Rabba, wa bil-Islami deena, wa bi-Muhammadin sallallahu alayhi wa sallama nabiyya", meaning_hi: "मैं अल्लाह को रब मान कर, इस्लाम को दीन मान कर और मुहम्मद ﷺ को नबी मान कर राज़ी हो गया", meaning_hinglish: "Main Allah ko Rabb maan kar, Islam ko deen maan kar aur Muhammad ﷺ ko Nabi maan kar raazi ho gaya", meaning_en: "I am pleased with Allah as my Lord, Islam as my religion, and Muhammad (peace be upon him) as my Prophet.", reference: "Abu Dawud 5072 (3 times morning/evening)", category: "Morning & Evening" },
  { id: 8, arabic: "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ أَصْلِحْ لِي شَأْنِي كُلَّهُ وَلَا تَكِلْنِي إِلَىٰ نَفْسِي طَرْفَةَ عَيْنٍ", transliteration: "Ya Hayyu ya Qayyoom, bi-rahmatika astagheethu, aslih li sha'ni kullahu wa la takilni ila nafsi tarfata 'ayn", meaning_hi: "ऐ हमेशा ज़िंदा रहने वाले, ऐ सब को क़ायम रखने वाले, तेरी रहमत से मैं मदद माँगता हूँ, मेरे सारे मामले सुधार दे और मुझे पलक झपकने के बराबर भी मेरे नफ़्स के हवाले न कर", meaning_hinglish: "Ae hamesha zinda rehne wale, ae sab ko qaayam rakhne wale, teri rehmat se main madad maangta hoon, mere saare maamle sudhaar de aur mujhe palak jhapakne ke barabar bhi mere nafs ke hawale na kar", meaning_en: "O Ever-Living, O Sustainer, by Your mercy I seek help. Rectify all my affairs and do not leave me to myself even for the blink of an eye.", reference: "Mustadrak al-Hakim 2000", category: "Morning & Evening" },
  { id: 9, arabic: "أَصْبَحْنَا عَلَىٰ فِطْرَةِ الْإِسْلَامِ وَعَلَىٰ كَلِمَةِ الْإِخْلَاصِ وَعَلَىٰ دِينِ نَبِيِّنَا مُحَمَّدٍ وَعَلَىٰ مِلَّةِ أَبِينَا إِبْرَاهِيمَ حَنِيفًا مُسْلِمًا وَمَا كَانَ مِنَ الْمُشْرِكِينَ", transliteration: "Asbahna 'ala fitratil-Islam, wa 'ala kalimatil-ikhlas, wa 'ala deeni nabiyyina Muhammadin, wa 'ala millati abeena Ibrahima haneefan musliman wa ma kana minal-mushrikeen", meaning_hi: "हमने सुबह की इस्लाम की फ़ितरत पर, कलिमा-ए-इख़लास पर, अपने नबी मुहम्मद ﷺ के दीन पर और अपने बाप इबराहीम अलैहिस्सलाम के मिल्लत पर जो एक अल्लाह के बंदे थे, मुस्लिम थे और मुशरिकों में से नहीं थे", meaning_hinglish: "Humne subah ki Islam ki fitrat par, Kalima-e-Ikhlas par, apne Nabi Muhammad ﷺ ke deen par aur apne baap Ibrahim AS ke millat par jo ek Allah ke bande the, Muslim the aur mushrikeen mein se nahi the", meaning_en: "We have entered the morning upon the fitrah of Islam, upon the word of sincerity, upon the religion of our Prophet Muhammad, and upon the way of our father Ibrahim, who was upright and Muslim, and was not of the polytheists.", reference: "Ahmad 15360", category: "Morning & Evening" },
  { id: 10, arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ", transliteration: "Allahumma inni as'alukal-'afiyata fid-dunya wal-akhirah", meaning_hi: "ऐ अल्लाह! मैं तुझसे दुनिया और आख़िरत में आफ़ियत (सलामती) माँगता हूँ", meaning_hinglish: "Ae Allah! Main tujhse duniya aur aakhirat mein aafiyat (salaamati) maangta hoon", meaning_en: "O Allah, I ask You for well-being in this world and the Hereafter.", reference: "Abu Dawud 5074", category: "Morning & Evening" },

  // ═══════════════════ Salah ═══════════════════
  { id: 11, arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَىٰ جَدُّكَ وَلَا إِلَٰهَ غَيْرُكَ", transliteration: "Subhanakallahumma wa bihamdika wa tabarakasmuka wa ta'ala jadduka wa la ilaha ghayruk", meaning_hi: "ऐ अल्लाह! तू पाक है अपनी तारीफ़ के साथ, तेरा नाम बरकत वाला है, तेरी शान बुलंद है और तेरे सिवा कोई माबूद नहीं", meaning_hinglish: "Ae Allah! Tu paak hai apni tareef ke saath, tera naam barkat wala hai, teri shaan buland hai aur tere siwa koi mabood nahi", meaning_en: "Glory is to You O Allah, and praise. Blessed is Your name, exalted is Your majesty, and there is no god but You.", reference: "Abu Dawud 775 (Opening dua of Salah)", category: "Salah" },
  { id: 12, arabic: "سُبْحَانَ رَبِّيَ الْعَظِيمِ", transliteration: "Subhana Rabbiyal-'Adheem", meaning_hi: "पाक है मेरा रब जो बहुत बड़ा है", meaning_hinglish: "Paak hai mera Rabb jo bahut bada hai", meaning_en: "Glory is to my Lord, the Most Great.", reference: "Muslim 772 (Said in Ruku)", category: "Salah" },
  { id: 13, arabic: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ رَبَّنَا وَلَكَ الْحَمْدُ", transliteration: "Sami'Allahu liman hamidah, Rabbana wa lakal-hamd", meaning_hi: "अल्लाह ने सुन लिया जिसने उसकी तारीफ़ की। ऐ हमारे रब! तेरे ही लिए सारी तारीफ़ है", meaning_hinglish: "Allah ne sun liya jisne uski tareef ki. Ae hamare Rabb! Tere hi liye saari tareef hai", meaning_en: "Allah hears whoever praises Him. Our Lord, to You is all praise.", reference: "Bukhari 789 (Rising from Ruku)", category: "Salah" },
  { id: 14, arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَىٰ", transliteration: "Subhana Rabbiyal-A'la", meaning_hi: "पाक है मेरा रब जो सबसे बुलंद है", meaning_hinglish: "Paak hai mera Rabb jo sabse buland hai", meaning_en: "Glory is to my Lord, the Most High.", reference: "Muslim 772 (Said in Sujood)", category: "Salah" },
  { id: 15, arabic: "رَبِّ اغْفِرْ لِي رَبِّ اغْفِرْ لِي", transliteration: "Rabbighfir li, Rabbighfir li", meaning_hi: "ऐ मेरे रब! मुझे माफ़ कर, ऐ मेरे रब! मुझे माफ़ कर", meaning_hinglish: "Ae mere Rabb! Mujhe maaf kar, ae mere Rabb! Mujhe maaf kar", meaning_en: "My Lord, forgive me. My Lord, forgive me.", reference: "Abu Dawud 874 (Between two Sujood)", category: "Salah" },
  { id: 16, arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَىٰ عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ", transliteration: "At-tahiyyatu lillahi was-salawatu wat-tayyibat. As-salamu 'alayka ayyuhan-Nabiyyu wa rahmatullahi wa barakatuh. As-salamu 'alayna wa 'ala 'ibadillahis-saliheen. Ash-hadu an la ilaha illallah wa ash-hadu anna Muhammadan 'abduhu wa rasuluh", meaning_hi: "सारी इबादतें अल्लाह के लिए हैं, सारी नमाज़ें और पाक चीज़ें। ऐ नबी! आप पर सलाम हो और अल्लाह की रहमत और बरकतें। हम पर और अल्लाह के नेक बंदों पर सलाम हो। मैं गवाही देता हूँ कि अल्लाह के सिवा कोई माबूद नहीं और मुहम्मद उसके बंदे और रसूल हैं", meaning_hinglish: "Saari ibadatein Allah ke liye hain, saari namazein aur paak cheezein. Ae Nabi! Aap par salaam ho aur Allah ki rehmat aur barkatein. Hum par aur Allah ke nek bandon par salaam ho. Main gawahi deta hoon ki Allah ke siwa koi mabood nahi aur Muhammad uske bande aur Rasool hain", meaning_en: "All greetings, prayers and good things are for Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that none has the right to be worshipped except Allah and that Muhammad is His servant and Messenger.", reference: "Bukhari 831 (Tashahhud)", category: "Salah" },
  { id: 17, arabic: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ", transliteration: "Allahumma salli 'ala Muhammadin wa 'ala aali Muhammadin kama sallayta 'ala Ibrahima wa 'ala aali Ibrahima innaka Hameedun Majeed", meaning_hi: "ऐ अल्लाह! मुहम्मद और उनकी आल पर रहमत नाज़िल फ़रमा जैसे तूने इबराहीम और उनकी आल पर रहमत नाज़िल फ़रमाई, बेशक तू तारीफ़ वाला बुज़ुर्गी वाला है", meaning_hinglish: "Ae Allah! Muhammad aur unki aal par rehmat naazil farma jaise tune Ibrahim aur unki aal par rehmat naazil farmaai, beshak tu tareef wala buzurgi wala hai", meaning_en: "O Allah, send blessings upon Muhammad and upon the family of Muhammad, as You sent blessings upon Ibrahim and upon the family of Ibrahim. Indeed You are Praiseworthy, Glorious.", reference: "Bukhari 3370 (Durood Ibrahim)", category: "Salah" },
  { id: 18, arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ وَمِنْ عَذَابِ جَهَنَّمَ وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ وَمِنْ شَرِّ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ", transliteration: "Allahumma inni a'udhu bika min 'adhabil-qabri wa min 'adhabi jahannam, wa min fitnatil-mahya wal-mamat, wa min sharri fitnatil-masihid-dajjal", meaning_hi: "ऐ अल्लाह! मैं तेरी पनाह माँगता हूँ क़ब्र के अज़ाब से और जहन्नम के अज़ाब से और ज़िंदगी और मौत के फ़ित्ने से और मसीह दज्जाल के फ़ित्ने के शर से", meaning_hinglish: "Ae Allah! Main teri panah maangta hoon qabr ke azaab se aur jahannam ke azaab se aur zindagi aur maut ke fitne se aur Maseeh Dajjal ke fitne ke shar se", meaning_en: "O Allah, I seek refuge in You from the punishment of the grave, from the punishment of Hellfire, from the trials of life and death, and from the evil of the trial of the False Messiah.", reference: "Muslim 588 (Before salam in Salah)", category: "Salah" },
  { id: 19, arabic: "أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ", transliteration: "Astaghfirullah, Astaghfirullah, Astaghfirullah", meaning_hi: "मैं अल्लाह से माफ़ी माँगता हूँ (तीन बार)", meaning_hinglish: "Main Allah se maafi maangta hoon (teen baar)", meaning_en: "I seek forgiveness from Allah (three times).", reference: "Muslim 591 (After Salam)", category: "Salah" },
  { id: 20, arabic: "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Allahumma antas-Salam wa minkas-salam, tabarakta ya dhal-jalali wal-ikram", meaning_hi: "ऐ अल्लाह! तू ही सलामती वाला है और तुझ से ही सलामती है, तू बरकत वाला है ऐ जलाल और इकराम वाले", meaning_hinglish: "Ae Allah! Tu hi salaamati wala hai aur tujh se hi salaamati hai, tu barkat wala hai ae jalaal aur ikraam wale", meaning_en: "O Allah, You are Peace and from You is peace. Blessed are You, O Owner of Majesty and Honor.", reference: "Muslim 592 (After Salam)", category: "Salah" },

  // ═══════════════════ Food & Drink ═══════════════════
  { id: 21, arabic: "بِسْمِ اللَّهِ", transliteration: "Bismillah", meaning_hi: "अल्लाह के नाम से", meaning_hinglish: "Allah ke naam se", meaning_en: "In the name of Allah.", reference: "Bukhari 5376 (Before eating)", category: "Food & Drink" },
  { id: 22, arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَٰذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ", transliteration: "Alhamdu lillahilladhi at'amani hadha wa razaqaneehi min ghayri hawlin minni wa la quwwah", meaning_hi: "अल्लाह की तारीफ़ जिसने मुझे यह खिलाया और मुझे यह रिज़्क़ दिया बिना मेरी ताक़त और क़ुव्वत के", meaning_hinglish: "Allah ki tareef jisne mujhe yeh khilaya aur mujhe yeh rizq diya bina meri taaqat aur quwwat ke", meaning_en: "All praise is for Allah who fed me this and provided it for me without any power or might from me.", reference: "Tirmidhi 3458 (After eating)", category: "Food & Drink" },
  { id: 23, arabic: "الْحَمْدُ لِلَّهِ حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ", transliteration: "Alhamdu lillahi hamdan katheeran tayyiban mubarakan feeh", meaning_hi: "अल्लाह की बहुत-बहुत पाक और बरकत वाली तारीफ़", meaning_hinglish: "Allah ki bahut-bahut paak aur barkat wali tareef", meaning_en: "All praise is for Allah, abundant, good and blessed praise.", reference: "Bukhari 5458 (After eating)", category: "Food & Drink" },
  { id: 24, arabic: "بِسْمِ اللَّهِ وَعَلَىٰ بَرَكَةِ اللَّهِ", transliteration: "Bismillahi wa 'ala barakatillah", meaning_hi: "अल्लाह के नाम से और अल्लाह की बरकत पर", meaning_hinglish: "Allah ke naam se aur Allah ki barkat par", meaning_en: "In the name of Allah and upon the blessings of Allah.", reference: "Abu Dawud 3767 (Before eating with others)", category: "Food & Drink" },
  { id: 25, arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَأَطْعِمْنَا خَيْرًا مِنْهُ", transliteration: "Allahumma barik lana feehi wa at'imna khayran minhu", meaning_hi: "ऐ अल्लाह! हमें इसमें बरकत दे और हमें इससे बेहतर खिला", meaning_hinglish: "Ae Allah! Humein ismein barkat de aur humein isse behtar khila", meaning_en: "O Allah, bless us in it and feed us with something better than it.", reference: "Tirmidhi 3455 (When drinking milk)", category: "Food & Drink" },
  { id: 26, arabic: "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ", transliteration: "Dhahabadh-dhama'u wabtallatil-'urooqu wa thabatal-ajru in sha'Allah", meaning_hi: "प्यास बुझ गई, रगें तर हो गईं और अज्र साबित हो गया इन शा अल्लाह", meaning_hinglish: "Pyaas bujh gayi, ragein tar ho gayin aur ajr saabit ho gaya In Sha Allah", meaning_en: "The thirst has gone, the veins are moistened, and the reward is confirmed, if Allah wills.", reference: "Abu Dawud 2357 (When breaking fast)", category: "Food & Drink" },
  { id: 27, arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا", transliteration: "Allahumma inni as'aluka 'ilman nafi'an wa rizqan tayyiban wa 'amalan mutaqabbala", meaning_hi: "ऐ अल्लाह! मैं तुझसे फ़ायदेमंद इल्म, पाक रिज़्क़ और क़बूल होने वाला अमल माँगता हूँ", meaning_hinglish: "Ae Allah! Main tujhse faydemand ilm, paak rizq aur qubool hone wala amal maangta hoon", meaning_en: "O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.", reference: "Ibn Majah 925 (After Fajr salah)", category: "Salah" },
  { id: 28, arabic: "اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي وَاسْقِ مَنْ سَقَانِي", transliteration: "Allahumma at'im man at'amani wasqi man saqani", meaning_hi: "ऐ अल्लाह! जिसने मुझे खिलाया उसे खिला और जिसने मुझे पिलाया उसे पिला", meaning_hinglish: "Ae Allah! Jisne mujhe khilaya use khila aur jisne mujhe pilaya use pila", meaning_en: "O Allah, feed the one who fed me and give drink to the one who gave me drink.", reference: "Muslim 2055 (Dua for host)", category: "Food & Drink" },

  // ═══════════════════ Travel ═══════════════════
  { id: 29, arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنْقَلِبُونَ", transliteration: "Subhanalladhi sakh-khara lana hadha wa ma kunna lahu muqrineen, wa inna ila Rabbina lamunqaliboon", meaning_hi: "पाक है वह जिसने इसे हमारे वश में किया जबकि हम इसे वश में करने की ताक़त नहीं रखते थे और बेशक हम अपने रब की तरफ़ लौटने वाले हैं", meaning_hinglish: "Paak hai woh jisne ise hamare vash mein kiya jabki hum ise vash mein karne ki taaqat nahi rakhte the aur beshak hum apne Rabb ki taraf lautne wale hain", meaning_en: "Glory to the One who has subjected this to us, and we could not have otherwise subdued it. And indeed, to our Lord we will surely return.", reference: "Quran 43:13-14 (Boarding vehicle)", category: "Travel" },
  { id: 30, arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَٰذَا الْبِرَّ وَالتَّقْوَىٰ وَمِنَ الْعَمَلِ مَا تَرْضَىٰ", transliteration: "Allahumma inna nas'aluka fi safarina hadhal-birra wat-taqwa wa minal-'amali ma tarda", meaning_hi: "ऐ अल्लाह! हम तुझसे इस सफ़र में नेकी और तक़वा माँगते हैं और ऐसे अमल माँगते हैं जिनसे तू राज़ी हो", meaning_hinglish: "Ae Allah! Hum tujhse is safar mein neki aur taqwa maangte hain aur aise amal maangte hain jinse tu raazi ho", meaning_en: "O Allah, we ask You in this journey for righteousness, piety, and deeds that please You.", reference: "Muslim 1342 (Starting journey)", category: "Travel" },
  { id: 31, arabic: "اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَٰذَا وَاطْوِ عَنَّا بُعْدَهُ", transliteration: "Allahumma hawwin 'alayna safarana hadha watwi 'anna bu'dahu", meaning_hi: "ऐ अल्लाह! हमारा यह सफ़र आसान कर दे और इसकी दूरी कम कर दे", meaning_hinglish: "Ae Allah! Hamara yeh safar aasaan kar de aur iski doori kam kar de", meaning_en: "O Allah, make this journey easy for us and shorten its distance for us.", reference: "Muslim 1342 (Travel dua)", category: "Travel" },
  { id: 32, arabic: "اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ وَالْخَلِيفَةُ فِي الْأَهْلِ", transliteration: "Allahumma antas-sahibu fis-safari wal-khaleefatu fil-ahl", meaning_hi: "ऐ अल्लाह! तू सफ़र में साथी है और घर वालों में (मेरा) ख़लीफ़ा है", meaning_hinglish: "Ae Allah! Tu safar mein saathi hai aur ghar walon mein (mera) khaleefa hai", meaning_en: "O Allah, You are the Companion on the journey and the Guardian of the family.", reference: "Muslim 1342 (Travel dua)", category: "Travel" },
  { id: 33, arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ وَعْثَاءِ السَّفَرِ وَكَآبَةِ الْمَنْظَرِ وَسُوءِ الْمُنْقَلَبِ فِي الْمَالِ وَالْأَهْلِ", transliteration: "Allahumma inni a'udhu bika min wa'tha'is-safari wa ka'abatil-mandhari wa soo'il-munqalabi fil-mali wal-ahli", meaning_hi: "ऐ अल्लाह! मैं तेरी पनाह माँगता हूँ सफ़र की तकलीफ़ से, बुरे नज़ारे से और माल और घरवालों में बुरी वापसी से", meaning_hinglish: "Ae Allah! Main teri panah maangta hoon safar ki takleef se, bure nazaare se aur maal aur gharwalon mein buri waapsi se", meaning_en: "O Allah, I seek refuge in You from the hardships of travel, from seeing distressing sights, and from finding harm in property and family upon return.", reference: "Muslim 1342 (Travel dua)", category: "Travel" },
  { id: 34, arabic: "اللَّهُمَّ اجْعَلْ لِي فِيهَا قَرَارًا وَرِزْقًا حَسَنًا", transliteration: "Allahummaj'al li feeha qararan wa rizqan hasana", meaning_hi: "ऐ अल्लाह! मेरे लिए इसमें ठहराव और अच्छा रिज़्क़ रख", meaning_hinglish: "Ae Allah! Mere liye ismein theharaav aur achha rizq rakh", meaning_en: "O Allah, grant me a good dwelling and good provision in it.", reference: "Tabarani (Entering a city)", category: "Travel" },
  { id: 35, arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ", transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq", meaning_hi: "मैं अल्लाह के मुकम्मल कलिमात की पनाह माँगता हूँ उसकी बनाई हर चीज़ के शर से", meaning_hinglish: "Main Allah ke mukammal kalimaat ki panah maangta hoon uski banaai har cheez ke shar se", meaning_en: "I seek refuge in the perfect words of Allah from the evil of what He has created.", reference: "Muslim 2708 (When stopping at a place during travel)", category: "Travel" },
  { id: 36, arabic: "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ", transliteration: "Aayiboona ta'iboona 'aabidoona li Rabbina hamidoon", meaning_hi: "हम लौटने वाले हैं, तौबा करने वाले, इबादत करने वाले, अपने रब की तारीफ़ करने वाले", meaning_hinglish: "Hum lautne wale hain, tauba karne wale, ibadat karne wale, apne Rabb ki tareef karne wale", meaning_en: "We are returning, repenting, worshipping, and praising our Lord.", reference: "Muslim 1342 (Returning from journey)", category: "Travel" },

  // ═══════════════════ Sleep ═══════════════════
  { id: 37, arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", transliteration: "Bismikallahumma amootu wa ahya", meaning_hi: "ऐ अल्लाह! तेरे नाम से मरता हूँ और जीता हूँ", meaning_hinglish: "Ae Allah! Tere naam se marta hoon aur jeeta hoon", meaning_en: "In Your name, O Allah, I die and I live.", reference: "Bukhari 6324 (Before sleeping)", category: "Sleep" },
  { id: 38, arabic: "اللَّهُمَّ بِاسْمِكَ أَحْيَا وَبِاسْمِكَ أَمُوتُ", transliteration: "Allahumma bismika ahya wa bismika amoot", meaning_hi: "ऐ अल्लाह! तेरे नाम से जीता हूँ और तेरे नाम से मरता हूँ", meaning_hinglish: "Ae Allah! Tere naam se jeeta hoon aur tere naam se marta hoon", meaning_en: "O Allah, in Your name I live and in Your name I die.", reference: "Bukhari 6325 (Before sleeping)", category: "Sleep" },
  { id: 39, arabic: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ", transliteration: "Allahumma qini 'adhabaka yawma tab'athu 'ibadak", meaning_hi: "ऐ अल्लाह! मुझे अपने अज़ाब से बचा उस दिन जब तू अपने बंदों को उठाएगा", meaning_hinglish: "Ae Allah! Mujhe apne azaab se bacha us din jab tu apne bandon ko uthaayega", meaning_en: "O Allah, protect me from Your punishment on the Day You resurrect Your servants.", reference: "Abu Dawud 5045 (Before sleeping)", category: "Sleep" },
  { id: 40, arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ", transliteration: "Alhamdu lillahilladhi ahyana ba'da ma amatana wa ilayhin-nushoor", meaning_hi: "अल्लाह की तारीफ़ जिसने हमें ज़िंदा किया हमें मारने के बाद और उसी की तरफ़ उठना है", meaning_hinglish: "Allah ki tareef jisne humein zinda kiya humein maarne ke baad aur usi ki taraf uthna hai", meaning_en: "All praise is for Allah who gave us life after causing us to die, and to Him is the resurrection.", reference: "Bukhari 6324 (Upon waking up)", category: "Sleep" },
  { id: 41, arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ", transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan", meaning_hi: "ऐ अल्लाह! मैं तेरी पनाह माँगता हूँ ग़म और उदासी से", meaning_hinglish: "Ae Allah! Main teri panah maangta hoon gham aur udaasi se", meaning_en: "O Allah, I seek refuge in You from worry and grief.", reference: "Bukhari 6369 (Before sleeping)", category: "Sleep" },
  { id: 42, arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ", transliteration: "A'udhu billahi minash-shaytanir-rajeem", meaning_hi: "मैं अल्लाह की पनाह माँगता हूँ शैतान मरदूद से", meaning_hinglish: "Main Allah ki panah maangta hoon Shaytan mardood se", meaning_en: "I seek refuge in Allah from the accursed Shaytan.", reference: "Muslim 2262 (After bad dream — then spit left 3 times)", category: "Sleep" },

  // ═══════════════════ Masjid ═══════════════════
  { id: 43, arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ", transliteration: "Allahummaftah li abwaba rahmatik", meaning_hi: "ऐ अल्लाह! मेरे लिए अपनी रहमत के दरवाज़े खोल दे", meaning_hinglish: "Ae Allah! Mere liye apni rehmat ke darwaze khol de", meaning_en: "O Allah, open for me the doors of Your mercy.", reference: "Muslim 713 (Entering Masjid)", category: "Masjid" },
  { id: 44, arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ", transliteration: "Allahumma inni as'aluka min fadlik", meaning_hi: "ऐ अल्लाह! मैं तुझसे तेरा फ़ज़ल माँगता हूँ", meaning_hinglish: "Ae Allah! Main tujhse tera fazal maangta hoon", meaning_en: "O Allah, I ask You of Your bounty.", reference: "Muslim 713 (Leaving Masjid)", category: "Masjid" },
  { id: 45, arabic: "أَعُوذُ بِاللَّهِ الْعَظِيمِ وَبِوَجْهِهِ الْكَرِيمِ وَسُلْطَانِهِ الْقَدِيمِ مِنَ الشَّيْطَانِ الرَّجِيمِ", transliteration: "A'udhu billahil-'Adheem wa bi-wajhihil-kareem wa sultanihil-qadeem minash-shaytanir-rajeem", meaning_hi: "मैं अल्लाह अज़ीम की पनाह माँगता हूँ और उसके करीम चेहरे की और उसकी क़दीम सल्तनत की शैतान मरदूद से", meaning_hinglish: "Main Allah Azeem ki panah maangta hoon aur uske kareem chehre ki aur uski qadeem saltanat ki Shaytan mardood se", meaning_en: "I seek refuge in Allah the Almighty, and in His noble Face, and in His eternal authority, from the accursed Shaytan.", reference: "Abu Dawud 466 (Entering Masjid)", category: "Masjid" },
  { id: 46, arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", transliteration: "La hawla wa la quwwata illa billah", meaning_hi: "कोई ताक़त और कोई क़ुव्वत नहीं सिवाय अल्लाह के", meaning_hinglish: "Koi taaqat aur koi quwwat nahi siwaay Allah ke", meaning_en: "There is no power and no strength except with Allah.", reference: "Muslim 209 (Upon hearing adhan)", category: "Masjid" },
  { id: 47, arabic: "اللَّهُمَّ رَبَّ هَٰذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ", transliteration: "Allahumma Rabba hadhihid-da'watit-tammati was-salatil-qa'imati, aati Muhammadanil-waseelata wal-fadeelata wab'athhu maqamam-mahmoodanilladhi wa'adtah", meaning_hi: "ऐ अल्लाह! इस मुकम्मल दावत और क़ायम होने वाली नमाज़ के रब! मुहम्मद ﷺ को वसीला और फ़ज़ीलत अता फ़रमा और उन्हें मक़ामे-महमूद पर पहुँचा जिसका तूने उनसे वादा किया है", meaning_hinglish: "Ae Allah! Is mukammal dawat aur qaayam hone wali namaz ke Rabb! Muhammad ﷺ ko waseela aur fazeelat ata farma aur unhein maqaam-e-mahmood par pahuncha jiska tune unse waada kiya hai", meaning_en: "O Allah, Lord of this perfect call and the established prayer, grant Muhammad the intercession and favor, and raise him to the honored station that You have promised him.", reference: "Bukhari 614 (After Adhan)", category: "Masjid" },
  { id: 48, arabic: "اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا وَفِي بَصَرِي نُورًا وَفِي سَمْعِي نُورًا", transliteration: "Allahummaj'al fi qalbi nooran wa fi basari nooran wa fi sam'i noora", meaning_hi: "ऐ अल्लाह! मेरे दिल में नूर रख दे, मेरी आँखों में नूर और मेरे कानों में नूर", meaning_hinglish: "Ae Allah! Mere dil mein noor rakh de, meri aankhon mein noor aur mere kaanon mein noor", meaning_en: "O Allah, place light in my heart, light in my sight, and light in my hearing.", reference: "Bukhari 6316 (Going to Masjid)", category: "Masjid" },

  // ═══════════════════ Protection ═══════════════════
  { id: 49, arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ", transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazani wal-'ajzi wal-kasali wal-bukhli wal-jubni wa dala'id-dayni wa ghalabatir-rijal", meaning_hi: "ऐ अल्लाह! मैं तेरी पनाह माँगता हूँ ग़म और उदासी से, कमज़ोरी और सुस्ती से, कंजूसी और बुज़दिली से, क़र्ज़ के बोझ से और लोगों के ग़लबे से", meaning_hinglish: "Ae Allah! Main teri panah maangta hoon gham aur udaasi se, kamzori aur susti se, kanjoosi aur buzdili se, qarz ke bojh se aur logon ke ghalbe se", meaning_en: "O Allah, I seek refuge in You from worry and grief, from weakness and laziness, from miserliness and cowardice, from the burden of debt and from being overpowered by men.", reference: "Bukhari 6369", category: "Protection" },
  { id: 50, arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ", transliteration: "Bismillahilladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-Samee'ul-'Aleem", meaning_hi: "अल्लाह के नाम से जिसके नाम के साथ ज़मीन और आसमान में कोई चीज़ नुक़सान नहीं दे सकती और वह सुनने वाला जानने वाला है", meaning_hinglish: "Allah ke naam se jiske naam ke saath zameen aur aasmaan mein koi cheez nuqsaan nahi de sakti aur woh sunne wala jaanne wala hai", meaning_en: "In the name of Allah, with whose name nothing on earth or in the heavens can cause harm, and He is the All-Hearing, All-Knowing.", reference: "Abu Dawud 5088 (3 times for protection)", category: "Protection" },
  { id: 51, arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ", transliteration: "A'udhu bikalimatillahit-tammati min kulli shaytanin wa hammatin wa min kulli 'aynin lammah", meaning_hi: "मैं अल्लाह के मुकम्मल कलिमात की पनाह माँगता हूँ हर शैतान और ज़हरीले जानवर से और हर नज़र लगाने वाली आँख से", meaning_hinglish: "Main Allah ke mukammal kalimaat ki panah maangta hoon har shaytan aur zahreele jaanwar se aur har nazar lagane wali aankh se", meaning_en: "I seek refuge in the perfect words of Allah from every devil and poisonous creature, and from every evil eye.", reference: "Bukhari 3371 (Protection from evil eye)", category: "Protection" },
  { id: 52, arabic: "حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ", transliteration: "Hasbiyallahu la ilaha illa Huwa 'alayhi tawakkaltu wa Huwa Rabbul-'Arshil-'Adheem", meaning_hi: "मेरे लिए अल्लाह काफ़ी है, उसके सिवा कोई माबूद नहीं, उसी पर मैंने भरोसा किया और वह अर्शे-अज़ीम का रब है", meaning_hinglish: "Mere liye Allah kaafi hai, uske siwa koi mabood nahi, usi par maine bharosa kiya aur woh Arsh-e-Azeem ka Rabb hai", meaning_en: "Allah is sufficient for me. There is no god but He. In Him I put my trust, and He is the Lord of the Mighty Throne.", reference: "Quran 9:129 (7 times morning/evening)", category: "Protection" },
  { id: 53, arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ مَا عَمِلْتُ وَمِنْ شَرِّ مَا لَمْ أَعْمَلْ", transliteration: "Allahumma inni a'udhu bika min sharri ma 'amiltu wa min sharri ma lam a'mal", meaning_hi: "ऐ अल्लाह! मैं तेरी पनाह माँगता हूँ जो मैंने किया उसके शर से और जो मैंने नहीं किया उसके शर से", meaning_hinglish: "Ae Allah! Main teri panah maangta hoon jo maine kiya uske shar se aur jo maine nahi kiya uske shar se", meaning_en: "O Allah, I seek refuge in You from the evil of what I have done and the evil of what I have not done.", reference: "Muslim 2716", category: "Protection" },
  { id: 54, arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ جَهْدِ الْبَلَاءِ وَدَرَكِ الشَّقَاءِ وَسُوءِ الْقَضَاءِ وَشَمَاتَةِ الْأَعْدَاءِ", transliteration: "Allahumma inni a'udhu bika min jahdil-bala'i wa darakish-shaqa'i wa soo'il-qada'i wa shamatatal-a'da'", meaning_hi: "ऐ अल्लाह! मैं तेरी पनाह माँगता हूँ सख़्त आज़माइश से, बदबख़्ती से, बुरी तक़दीर से और दुश्मनों की ख़ुशी से", meaning_hinglish: "Ae Allah! Main teri panah maangta hoon sakht aazmaish se, badbakhti se, buri taqdeer se aur dushmanon ki khushi se", meaning_en: "O Allah, I seek refuge in You from severe trials, from being overtaken by wretchedness, from bad fate, and from the gloating of enemies.", reference: "Bukhari 6347", category: "Protection" },
  { id: 55, arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ وَعَذَابِ الْقَبْرِ", transliteration: "Allahumma inni a'udhu bika minal-kufri wal-faqri wa 'adhabil-qabr", meaning_hi: "ऐ अल्लाह! मैं तेरी पनाह माँगता हूँ कुफ़्र से, फ़क़ीरी से और क़ब्र के अज़ाब से", meaning_hinglish: "Ae Allah! Main teri panah maangta hoon kufr se, faqeeri se aur qabr ke azaab se", meaning_en: "O Allah, I seek refuge in You from disbelief, poverty, and the punishment of the grave.", reference: "Nasai 5475", category: "Protection" },
  { id: 56, arabic: "اللَّهُمَّ اسْتُرْ عَوْرَاتِي وَآمِنْ رَوْعَاتِي", transliteration: "Allahummastir 'awrati wa aamin raw'ati", meaning_hi: "ऐ अल्लाह! मेरी कमज़ोरियाँ छुपा दे और मेरे ख़ौफ़ को अमन में बदल दे", meaning_hinglish: "Ae Allah! Meri kamzoriyan chhupa de aur mere khauf ko aman mein badal de", meaning_en: "O Allah, conceal my faults and calm my fears.", reference: "Abu Dawud 5074", category: "Protection" },
  { id: 57, arabic: "اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَنْ شِمَالِي وَمِنْ فَوْقِي وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي", transliteration: "Allahummahfadhni min bayni yadayya wa min khalfi wa 'an yameeni wa 'an shimali wa min fawqi wa a'udhu bi'adhamatika an ughtala min tahti", meaning_hi: "ऐ अल्लाह! मेरी हिफ़ाज़त कर मेरे आगे से, पीछे से, दाईं तरफ़ से, बाईं तरफ़ से, ऊपर से, और मैं तेरी अज़मत की पनाह माँगता हूँ कि मुझे नीचे से हलाक किया जाए", meaning_hinglish: "Ae Allah! Meri hifazat kar mere aage se, peeche se, daayin taraf se, baayin taraf se, oopar se, aur main teri azmat ki panah maangta hoon ki mujhe neeche se halaak kiya jaaye", meaning_en: "O Allah, protect me from my front, from behind, from my right, from my left, from above, and I seek refuge in Your Greatness from being destroyed from beneath me.", reference: "Abu Dawud 5074", category: "Protection" },
  { id: 58, arabic: "أَعُوذُ بِاللَّهِ السَّمِيعِ الْعَلِيمِ مِنَ الشَّيْطَانِ الرَّجِيمِ مِنْ هَمْزِهِ وَنَفْخِهِ وَنَفْثِهِ", transliteration: "A'udhu billahis-Samee'il-'Aleem minash-shaytanir-rajeem min hamzihi wa nafkhihi wa nafthih", meaning_hi: "मैं अल्लाह, सुनने वाले और जानने वाले की पनाह माँगता हूँ शैतान मरदूद से, उसके बहकावे, घमंड और बुरे असर से", meaning_hinglish: "Main Allah, sunne wale aur jaanne wale ki panah maangta hoon Shaytan mardood se, uske behkaave, ghamand aur bure asar se", meaning_en: "I seek refuge in Allah, the All-Hearing, the All-Knowing, from the accursed Shaytan — from his promptings, arrogance, and harmful influence.", reference: "Abu Dawud 775", category: "Protection" },

  // ═══════════════════ Forgiveness ═══════════════════
  { id: 59, arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ", transliteration: "Astaghfirullaha-'Adheemalladhi la ilaha illa Huwal-Hayyul-Qayyoomu wa atoobu ilayh", meaning_hi: "मैं अल्लाह अज़ीम से माफ़ी माँगता हूँ जिसके सिवा कोई माबूद नहीं, वह ज़िंदा है, सब को क़ायम रखने वाला है और मैं उसकी तरफ़ तौबा करता हूँ", meaning_hinglish: "Main Allah Azeem se maafi maangta hoon jiske siwa koi mabood nahi, woh zinda hai, sab ko qaayam rakhne wala hai aur main uski taraf tauba karta hoon", meaning_en: "I seek forgiveness from Allah the Almighty, there is no god but He, the Ever-Living, the Sustainer of all, and I repent to Him.", reference: "Abu Dawud 1517", category: "Forgiveness" },
  { id: 60, arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ", transliteration: "Allahumma anta Rabbi la ilaha illa anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, aboo'u laka bi-ni'matika 'alayya wa aboo'u bi-dhanbi, faghfir li fa innahu la yaghfirudh-dhunuba illa ant", meaning_hi: "ऐ अल्लाह! तू मेरा रब है, तेरे सिवा कोई माबूद नहीं, तूने मुझे पैदा किया और मैं तेरा बंदा हूँ, मैं तेरे अहद और वादे पर हूँ जितना मुझसे हो सकता है, मैं तेरी पनाह माँगता हूँ जो बुराई मैंने की उससे, मैं तेरी नेअमतों का इक़रार करता हूँ और अपने गुनाहों का इक़रार करता हूँ, मुझे माफ़ कर दे क्योंकि तेरे सिवा कोई गुनाह माफ़ नहीं करता", meaning_hinglish: "Ae Allah! Tu mera Rabb hai, tere siwa koi mabood nahi, tune mujhe paida kiya aur main tera banda hoon, main tere ahad aur waade par hoon jitna mujhse ho sakta hai, main teri panah maangta hoon jo buraai maine ki usse, main teri nematon ka iqraar karta hoon aur apne gunaahon ka iqraar karta hoon, mujhe maaf kar de kyunki tere siwa koi gunaah maaf nahi karta", meaning_en: "O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil I have done. I acknowledge Your blessings upon me, and I acknowledge my sin. So forgive me, for verily none can forgive sins except You.", reference: "Bukhari 6306 (Sayyidul Istighfar)", category: "Forgiveness" },
  { id: 61, arabic: "رَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ", transliteration: "Rabbana dhalamna anfusana wa in lam taghfir lana wa tarhamna lanakoonanna minal-khasireen", meaning_hi: "ऐ हमारे रब! हमने अपनी जानों पर ज़ुल्म किया और अगर तूने हमें माफ़ न किया और हम पर रहम न किया तो हम ज़रूर नुक़सान उठाने वालों में से होंगे", meaning_hinglish: "Ae hamare Rabb! Humne apni jaanon par zulm kiya aur agar tune humein maaf na kiya aur hum par reham na kiya to hum zaroor nuqsaan uthane walon mein se honge", meaning_en: "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.", reference: "Quran 7:23 (Dua of Adam AS)", category: "Forgiveness" },
  { id: 62, arabic: "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ", transliteration: "Rabbighfir li wa tub 'alayya innaka antat-Tawwabur-Raheem", meaning_hi: "ऐ मेरे रब! मुझे माफ़ कर और मेरी तौबा क़बूल कर, बेशक तू बहुत तौबा क़बूल करने वाला रहम करने वाला है", meaning_hinglish: "Ae mere Rabb! Mujhe maaf kar aur meri tauba qubool kar, beshak tu bahut tauba qubool karne wala reham karne wala hai", meaning_en: "My Lord, forgive me and accept my repentance. Indeed, You are the Oft-Returning, the Most Merciful.", reference: "Abu Dawud 1516 (100 times daily)", category: "Forgiveness" },
  { id: 63, arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ", transliteration: "SubhanAllahi wa bihamdihi, astaghfirullaha wa atoobu ilayh", meaning_hi: "अल्लाह पाक है अपनी तारीफ़ के साथ, मैं अल्लाह से माफ़ी माँगता हूँ और उसकी तरफ़ तौबा करता हूँ", meaning_hinglish: "Allah paak hai apni tareef ke saath, main Allah se maafi maangta hoon aur uski taraf tauba karta hoon", meaning_en: "Glory and praise be to Allah, I seek forgiveness from Allah and I repent to Him.", reference: "Muslim 484 (At end of gathering)", category: "Forgiveness" },
  { id: 64, arabic: "رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا وَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ", transliteration: "Rabbanagh-fir lana dhunubana wa israfana fi amrina wa thabbit aqdamana wansurna 'alal-qawmil-kafireen", meaning_hi: "ऐ हमारे रब! हमारे गुनाह माफ़ कर दे और हमारे कामों में जो ज़्यादती हुई उसे माफ़ कर और हमारे क़दम जमा दे और काफ़िरों के मुक़ाबले में हमारी मदद कर", meaning_hinglish: "Ae hamare Rabb! Hamare gunaah maaf kar de aur hamare kaamon mein jo zyaadati hui use maaf kar aur hamare qadam jama de aur kafiron ke muqable mein hamari madad kar", meaning_en: "Our Lord, forgive us our sins and our excesses in our affairs, plant our feet firmly, and grant us victory over the disbelieving people.", reference: "Quran 3:147", category: "Forgiveness" },
  { id: 65, arabic: "رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ", transliteration: "Rabbanagh-fir li wa liwaalidayya wa lil-mu'mineena yawma yaqoomul-hisab", meaning_hi: "ऐ हमारे रब! मुझे माफ़ कर और मेरे माँ-बाप को और सब मोमिनों को उस दिन जब हिसाब होगा", meaning_hinglish: "Ae hamare Rabb! Mujhe maaf kar aur mere maa-baap ko aur sab mominon ko us din jab hisaab hoga", meaning_en: "Our Lord, forgive me and my parents and the believers on the Day the account is established.", reference: "Quran 14:41", category: "Forgiveness" },
  { id: 66, arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي", transliteration: "Allahumma innaka 'Afuwwun tuhibbul-'afwa fa'fu 'anni", meaning_hi: "ऐ अल्लाह! बेशक तू माफ़ करने वाला है, माफ़ करना पसंद करता है, तो मुझे माफ़ कर दे", meaning_hinglish: "Ae Allah! Beshak tu maaf karne wala hai, maaf karna pasand karta hai, to mujhe maaf kar de", meaning_en: "O Allah, You are the Pardoner, You love to pardon, so pardon me.", reference: "Tirmidhi 3513 (Laylatul Qadr dua)", category: "Forgiveness" },

  // ═══════════════════ General ═══════════════════
  { id: 67, arabic: "رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", transliteration: "Rabbighfir li wa liwaalidayya warhamhuma kama rabbayani sagheera", meaning_hi: "ऐ मेरे रब! मुझे और मेरे माँ-बाप को माफ़ कर और उन पर रहम कर जैसे उन्होंने मुझे बचपन में पाला", meaning_hinglish: "Ae mere Rabb! Mujhe aur mere maa-baap ko maaf kar aur un par reham kar jaise unhone mujhe bachpan mein paala", meaning_en: "My Lord, forgive me and my parents, and have mercy upon them as they brought me up when I was small.", reference: "Quran 17:24 (Dua for parents)", category: "General" },
  { id: 68, arabic: "رَبِّ زِدْنِي عِلْمًا", transliteration: "Rabbi zidni 'ilma", meaning_hi: "ऐ मेरे रब! मेरा इल्म बढ़ा दे", meaning_hinglish: "Ae mere Rabb! Mera ilm badha de", meaning_en: "My Lord, increase me in knowledge.", reference: "Quran 20:114 (Dua for knowledge)", category: "General" },
  { id: 69, arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhabannar", meaning_hi: "ऐ हमारे रब! हमें दुनिया में भी भलाई दे और आख़िरत में भी भलाई दे और आग के अज़ाब से बचा", meaning_hinglish: "Ae hamare Rabb! Humein duniya mein bhi bhalaai de aur aakhirat mein bhi bhalaai de aur aag ke azaab se bacha", meaning_en: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.", reference: "Quran 2:201 (Most recited Quranic dua)", category: "General" },
  { id: 70, arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا", transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqeena imama", meaning_hi: "ऐ हमारे रब! हमें हमारी बीवियों और औलाद से आँखों की ठंडक अता कर और हमें मुत्तक़ियों का इमाम बना", meaning_hinglish: "Ae hamare Rabb! Humein hamari biwiyon aur aulaad se aankhon ki thandak ata kar aur humein muttaqiyon ka imaam bana", meaning_en: "Our Lord, grant us from our spouses and offspring comfort to our eyes, and make us leaders for the righteous.", reference: "Quran 25:74 (Dua for family)", category: "General" },
  { id: 71, arabic: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي", transliteration: "Rabbish-rahli sadri wa yassir li amri", meaning_hi: "ऐ मेरे रब! मेरा सीना खोल दे और मेरे काम आसान कर दे", meaning_hinglish: "Ae mere Rabb! Mera seena khol de aur mere kaam aasaan kar de", meaning_en: "My Lord, expand my chest and ease my task for me.", reference: "Quran 20:25-26 (Dua of Musa AS)", category: "General" },
  { id: 72, arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَىٰ وَالتُّقَىٰ وَالْعَفَافَ وَالْغِنَىٰ", transliteration: "Allahumma inni as'alukal-huda wat-tuqa wal-'afafa wal-ghina", meaning_hi: "ऐ अल्लाह! मैं तुझसे हिदायत, तक़वा, पाकदामनी और बेनियाज़ी माँगता हूँ", meaning_hinglish: "Ae Allah! Main tujhse hidayat, taqwa, paakdaamani aur beniyazi maangta hoon", meaning_en: "O Allah, I ask You for guidance, piety, chastity, and self-sufficiency.", reference: "Muslim 2721 (Dua for guidance)", category: "General" },
  { id: 73, arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي", transliteration: "Allahumma 'aafini fi badani, Allahumma 'aafini fi sam'i, Allahumma 'aafini fi basari", meaning_hi: "ऐ अल्लाह! मेरे जिस्म में आफ़ियत दे, ऐ अल्लाह! मेरे कानों में आफ़ियत दे, ऐ अल्लाह! मेरी आँखों में आफ़ियत दे", meaning_hinglish: "Ae Allah! Mere jism mein aafiyat de, Ae Allah! Mere kaanon mein aafiyat de, Ae Allah! Meri aankhon mein aafiyat de", meaning_en: "O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight.", reference: "Abu Dawud 5090 (Dua for health)", category: "General" },
  { id: 74, arabic: "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ وَعَافِنِي فِيمَنْ عَافَيْتَ وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ", transliteration: "Allahummahdini feeman hadayt, wa 'aafini feeman 'afayt, wa tawallani feeman tawallayt", meaning_hi: "ऐ अल्लाह! मुझे हिदायत दे उनमें जिन्हें तूने हिदायत दी, मुझे आफ़ियत दे उनमें जिन्हें तूने आफ़ियत दी, मेरी सरपरस्ती कर उनमें जिनकी तूने सरपरस्ती की", meaning_hinglish: "Ae Allah! Mujhe hidayat de unmein jinhein tune hidayat di, mujhe aafiyat de unmein jinhein tune aafiyat di, meri sarparasti kar unmein jinki tune sarparasti ki", meaning_en: "O Allah, guide me among those You have guided, grant me health among those You have granted health, and take care of me among those You have taken care of.", reference: "Abu Dawud 1425 (Dua Qunoot)", category: "General" },
  { id: 75, arabic: "اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَىٰ نَبِيِّنَا مُحَمَّدٍ", transliteration: "Allahumma salli wa sallim 'ala nabiyyina Muhammad", meaning_hi: "ऐ अल्लाह! हमारे नबी मुहम्मद ﷺ पर दरूद और सलाम भेज", meaning_hinglish: "Ae Allah! Hamare Nabi Muhammad ﷺ par durood aur salaam bhej", meaning_en: "O Allah, send blessings and peace upon our Prophet Muhammad.", reference: "Quran 33:56 (Durood)", category: "General" },
  { id: 76, arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ", transliteration: "Allahummakfini bi-halalika 'an haramika wa aghnini bi-fadlika 'amman siwak", meaning_hi: "ऐ अल्लाह! मुझे अपने हलाल से काफ़ी कर दे अपने हराम से बचा कर और अपने फ़ज़ल से मुझे अपने सिवा सबसे बेनियाज़ कर दे", meaning_hinglish: "Ae Allah! Mujhe apne halal se kaafi kar de apne haram se bacha kar aur apne fazal se mujhe apne siwa sabse beniyaaz kar de", meaning_en: "O Allah, suffice me with what You have made lawful over what You have made unlawful, and enrich me by Your favour over all others.", reference: "Tirmidhi 3563 (Dua for rizq)", category: "General" },
  { id: 77, arabic: "اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ", transliteration: "Allahumma inni astakheeruka bi'ilmika wa astaqdiruka biqudratika wa as'aluka min fadlikal-'adheem", meaning_hi: "ऐ अल्लाह! मैं तेरे इल्म से तुझसे भलाई चाहता हूँ और तेरी क़ुदरत से तुझसे ताक़त माँगता हूँ और तुझसे तेरा बड़ा फ़ज़ल माँगता हूँ", meaning_hinglish: "Ae Allah! Main tere ilm se tujhse bhalaai chahta hoon aur teri qudrat se tujhse taaqat maangta hoon aur tujhse tera bada fazal maangta hoon", meaning_en: "O Allah, I seek Your guidance through Your knowledge, and I seek ability through Your power, and I ask You of Your great bounty.", reference: "Bukhari 1162 (Istikhara — beginning)", category: "General" },
  { id: 78, arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً إِنَّكَ أَنْتَ الْوَهَّابُ", transliteration: "Rabbana la tuzigh quloobana ba'da idh hadaytana wa hab lana min ladunka rahmatan innaka antal-Wahhab", meaning_hi: "ऐ हमारे रब! हमारे दिलों को टेढ़ा न कर इसके बाद कि तूने हमें हिदायत दी और हमें अपने पास से रहमत दे, बेशक तू बड़ा देने वाला है", meaning_hinglish: "Ae hamare Rabb! Hamare dilon ko tedha na kar iske baad ki tune humein hidayat di aur humein apne paas se rehmat de, beshak tu bada dene wala hai", meaning_en: "Our Lord, do not let our hearts deviate after You have guided us, and grant us mercy from Yourself. Indeed, You are the Bestower.", reference: "Quran 3:8 (Dua for steadfastness)", category: "General" },
  { id: 79, arabic: "اللَّهُمَّ أَصْلِحْ لِي دِينِي الَّذِي هُوَ عِصْمَةُ أَمْرِي وَأَصْلِحْ لِي دُنْيَايَ الَّتِي فِيهَا مَعَاشِي وَأَصْلِحْ لِي آخِرَتِي الَّتِي فِيهَا مَعَادِي", transliteration: "Allahumma aslih li deeniyalladhi huwa 'ismatu amri, wa aslih li dunyayallatee feeha ma'ashi, wa aslih li aakhiratiyallatee feeha ma'adi", meaning_hi: "ऐ अल्लाह! मेरा दीन दुरुस्त कर दे जो मेरे हर काम की बुनियाद है, मेरी दुनिया दुरुस्त कर दे जिसमें मेरी ज़िंदगी है, मेरी आख़िरत दुरुस्त कर दे जहाँ मुझे लौटना है", meaning_hinglish: "Ae Allah! Mera deen durust kar de jo mere har kaam ki bunyaad hai, meri duniya durust kar de jismein meri zindagi hai, meri aakhirat durust kar de jahan mujhe lautna hai", meaning_en: "O Allah, rectify my religion which is the safeguard of my affairs, rectify my worldly life in which is my livelihood, rectify my Hereafter to which is my return.", reference: "Muslim 2720", category: "General" },
  { id: 80, arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ", transliteration: "Ya Muqallibal-quloob thabbit qalbi 'ala deenika", meaning_hi: "ऐ दिलों को पलटने वाले! मेरे दिल को अपने दीन पर जमा दे", meaning_hinglish: "Ae dilon ko palatne wale! Mere dil ko apne deen par jama de", meaning_en: "O Turner of hearts, make my heart firm upon Your religion.", reference: "Tirmidhi 2140", category: "General" },
];
