export interface QuizQuestion {
  id: number;
  question_hi: string;
  question_hinglish: string;
  question_en: string;
  options: string[];
  correct: number;
  difficulty: "easy" | "medium" | "hard";
  topic: string;
}

export const GENERAL_QUIZ: QuizQuestion[] = [
  // ── EASY (1-30) ──────────────────────────────────────────────
  {
    id: 1,
    question_hi: "इस्लाम के कितने स्तंभ हैं?",
    question_hinglish: "Islam ke kitne stambh hain?",
    question_en: "How many pillars of Islam are there?",
    options: ["3", "4", "5", "7"],
    correct: 2,
    difficulty: "easy",
    topic: "Pillars of Islam",
  },
  {
    id: 2,
    question_hi: "क़ुरआन की पहली सूरह कौन सी है?",
    question_hinglish: "Quran ki pehli Surah kaun si hai?",
    question_en: "What is the first Surah of the Quran?",
    options: ["Al-Baqarah", "Al-Fatihah", "Al-Ikhlas", "An-Nas"],
    correct: 1,
    difficulty: "easy",
    topic: "Quran",
  },
  {
    id: 3,
    question_hi: "क़ुरआन में कुल कितनी सूरतें हैं?",
    question_hinglish: "Quran mein kul kitni Suratein hain?",
    question_en: "How many Surahs are in the Quran?",
    options: ["100", "110", "114", "120"],
    correct: 2,
    difficulty: "easy",
    topic: "Quran",
  },
  {
    id: 4,
    question_hi: "पैग़म्बर मुहम्मद ﷺ का जन्म कहाँ हुआ था?",
    question_hinglish: "Prophet Muhammad ﷺ ka janam kahan hua tha?",
    question_en: "Where was Prophet Muhammad ﷺ born?",
    options: ["Madinah", "Makkah", "Taif", "Jerusalem"],
    correct: 1,
    difficulty: "easy",
    topic: "Prophet Muhammad",
  },
  {
    id: 5,
    question_hi: "रोज़े किस इस्लामी महीने में रखे जाते हैं?",
    question_hinglish: "Roze kis Islamic mahine mein rakhe jaate hain?",
    question_en: "In which Islamic month is fasting observed?",
    options: ["Shaban", "Rajab", "Ramadan", "Muharram"],
    correct: 2,
    difficulty: "easy",
    topic: "Fasting",
  },
  {
    id: 6,
    question_hi: "नमाज़ किस दिशा में पढ़ी जाती है?",
    question_hinglish: "Namaz kis disha mein padhi jaati hai?",
    question_en: "In which direction do Muslims pray?",
    options: ["East", "West", "Towards the Qibla (Ka'bah)", "North"],
    correct: 2,
    difficulty: "easy",
    topic: "Prayer",
  },
  {
    id: 7,
    question_hi: "दिन में कितनी फ़र्ज़ नमाज़ें हैं?",
    question_hinglish: "Din mein kitni farz namazein hain?",
    question_en: "How many obligatory daily prayers are there?",
    options: ["3", "4", "5", "7"],
    correct: 2,
    difficulty: "easy",
    topic: "Prayer",
  },
  {
    id: 8,
    question_hi: "इस्लाम के पहले मुअज़्ज़िन कौन थे?",
    question_hinglish: "Islam ke pehle Muazzin kaun the?",
    question_en: "Who was the first Muezzin of Islam?",
    options: ["Umar (RA)", "Bilal (RA)", "Abu Bakr (RA)", "Ali (RA)"],
    correct: 1,
    difficulty: "easy",
    topic: "Islamic History",
  },
  {
    id: 9,
    question_hi: "लैलतुल क़द्र किस महीने में आती है?",
    question_hinglish: "Laylatul Qadr kis mahine mein aati hai?",
    question_en: "In which month does Laylatul Qadr occur?",
    options: ["Shawwal", "Dhul Hijjah", "Ramadan", "Rajab"],
    correct: 2,
    difficulty: "easy",
    topic: "Special Nights",
  },
  {
    id: 10,
    question_hi: "क़ुरआन में कितने जुज़ (पारे) हैं?",
    question_hinglish: "Quran mein kitne Juz (Paare) hain?",
    question_en: "How many Juz (parts) are in the Quran?",
    options: ["20", "25", "30", "40"],
    correct: 2,
    difficulty: "easy",
    topic: "Quran",
  },
  {
    id: 11,
    question_hi: "इस्लाम का पहला स्तंभ क्या है?",
    question_hinglish: "Islam ka pehla stambh kya hai?",
    question_en: "What is the first pillar of Islam?",
    options: ["Salah", "Zakat", "Shahada", "Hajj"],
    correct: 2,
    difficulty: "easy",
    topic: "Pillars of Islam",
  },
  {
    id: 12,
    question_hi: "क़ुरआन किस भाषा में नाज़िल हुआ?",
    question_hinglish: "Quran kis bhasha mein nazil hua?",
    question_en: "In which language was the Quran revealed?",
    options: ["Urdu", "Persian", "Arabic", "Hebrew"],
    correct: 2,
    difficulty: "easy",
    topic: "Quran",
  },
  {
    id: 13,
    question_hi: "मुसलमानों का पवित्र ग्रंथ कौन सा है?",
    question_hinglish: "Musalmano ka pavitra granth kaun sa hai?",
    question_en: "What is the holy book of Muslims?",
    options: ["Bible", "Torah", "Quran", "Psalms"],
    correct: 2,
    difficulty: "easy",
    topic: "Quran",
  },
  {
    id: 14,
    question_hi: "हज किस शहर में किया जाता है?",
    question_hinglish: "Hajj kis shehar mein kiya jaata hai?",
    question_en: "In which city is Hajj performed?",
    options: ["Madinah", "Jerusalem", "Makkah", "Cairo"],
    correct: 2,
    difficulty: "easy",
    topic: "Hajj",
  },
  {
    id: 15,
    question_hi: "ज़कात इस्लाम का कौन सा स्तंभ है?",
    question_hinglish: "Zakat Islam ka kaun sa stambh hai?",
    question_en: "Zakat is which pillar of Islam?",
    options: ["Second", "Third", "Fourth", "Fifth"],
    correct: 1,
    difficulty: "easy",
    topic: "Pillars of Islam",
  },
  {
    id: 16,
    question_hi: "पैग़म्बर मुहम्मद ﷺ के पिता का नाम क्या था?",
    question_hinglish: "Prophet Muhammad ﷺ ke walid ka naam kya tha?",
    question_en: "What was the name of Prophet Muhammad's ﷺ father?",
    options: ["Abu Talib", "Abdullah", "Abdul Muttalib", "Hamza"],
    correct: 1,
    difficulty: "easy",
    topic: "Prophet Muhammad",
  },
  {
    id: 17,
    question_hi: "ईद-उल-फ़ित्र किस के बाद मनाई जाती है?",
    question_hinglish: "Eid-ul-Fitr kis ke baad manayi jaati hai?",
    question_en: "Eid-ul-Fitr is celebrated after which month?",
    options: ["Dhul Hijjah", "Shawwal", "Ramadan", "Rajab"],
    correct: 2,
    difficulty: "easy",
    topic: "Festivals",
  },
  {
    id: 18,
    question_hi: "इस्लाम में कितने फ़रिश्तों पर ईमान लाना ज़रूरी है?",
    question_hinglish: "Islam mein kitne farishton par Iman lana zaroori hai?",
    question_en: "Belief in angels is which article of faith?",
    options: ["First", "Second", "Third", "Fourth"],
    correct: 1,
    difficulty: "easy",
    topic: "Articles of Faith",
  },
  {
    id: 19,
    question_hi: "पैग़म्बर मुहम्मद ﷺ की माता का नाम क्या था?",
    question_hinglish: "Prophet Muhammad ﷺ ki walida ka naam kya tha?",
    question_en: "What was the name of Prophet Muhammad's ﷺ mother?",
    options: ["Khadijah", "Aminah", "Fatimah", "Aisha"],
    correct: 1,
    difficulty: "easy",
    topic: "Prophet Muhammad",
  },
  {
    id: 20,
    question_hi: "मस्जिद-अल-हराम कहाँ स्थित है?",
    question_hinglish: "Masjid al-Haram kahan sthit hai?",
    question_en: "Where is Masjid al-Haram located?",
    options: ["Madinah", "Jerusalem", "Makkah", "Istanbul"],
    correct: 2,
    difficulty: "easy",
    topic: "Mosques",
  },
  {
    id: 21,
    question_hi: "क़ुरआन की आख़िरी सूरह कौन सी है?",
    question_hinglish: "Quran ki aakhiri Surah kaun si hai?",
    question_en: "What is the last Surah of the Quran?",
    options: ["Al-Falaq", "Al-Ikhlas", "An-Nas", "Al-Masad"],
    correct: 2,
    difficulty: "easy",
    topic: "Quran",
  },
  {
    id: 22,
    question_hi: "इस्लामी कैलेंडर का पहला महीना कौन सा है?",
    question_hinglish: "Islamic calendar ka pehla mahina kaun sa hai?",
    question_en: "What is the first month of the Islamic calendar?",
    options: ["Safar", "Ramadan", "Muharram", "Rajab"],
    correct: 2,
    difficulty: "easy",
    topic: "Islamic Calendar",
  },
  {
    id: 23,
    question_hi: "जुमे की नमाज़ किस दिन पढ़ी जाती है?",
    question_hinglish: "Jumu'ah ki namaz kis din padhi jaati hai?",
    question_en: "On which day is Jumu'ah (Friday) prayer offered?",
    options: ["Thursday", "Friday", "Saturday", "Sunday"],
    correct: 1,
    difficulty: "easy",
    topic: "Prayer",
  },
  {
    id: 24,
    question_hi: "पैग़म्बर मुहम्मद ﷺ की पहली पत्नी कौन थीं?",
    question_hinglish: "Prophet Muhammad ﷺ ki pehli biwi kaun thi?",
    question_en: "Who was the first wife of Prophet Muhammad ﷺ?",
    options: ["Aisha (RA)", "Khadijah (RA)", "Hafsa (RA)", "Zainab (RA)"],
    correct: 1,
    difficulty: "easy",
    topic: "Prophet Muhammad",
  },
  {
    id: 25,
    question_hi: "इस्लाम में 'ईमान के अरकान' कितने हैं?",
    question_hinglish: "Islam mein 'Iman ke Arkaan' kitne hain?",
    question_en: "How many articles of faith (Iman) are there in Islam?",
    options: ["4", "5", "6", "7"],
    correct: 2,
    difficulty: "easy",
    topic: "Articles of Faith",
  },
  {
    id: 26,
    question_hi: "मस्जिद-ए-नबवी कहाँ है?",
    question_hinglish: "Masjid-e-Nabawi kahan hai?",
    question_en: "Where is Masjid-e-Nabawi (Prophet's Mosque) located?",
    options: ["Makkah", "Madinah", "Jerusalem", "Baghdad"],
    correct: 1,
    difficulty: "easy",
    topic: "Mosques",
  },
  {
    id: 27,
    question_hi: "बिस्मिल्लाह से शुरू न होने वाली सूरह कौन सी है?",
    question_hinglish: "Bismillah se shuru na hone wali Surah kaun si hai?",
    question_en: "Which Surah does not begin with Bismillah?",
    options: ["Al-Fatihah", "Al-Baqarah", "At-Tawbah", "Al-Ikhlas"],
    correct: 2,
    difficulty: "easy",
    topic: "Quran",
  },
  {
    id: 28,
    question_hi: "इस्लाम का दूसरा स्तंभ कौन सा है?",
    question_hinglish: "Islam ka dusra stambh kaun sa hai?",
    question_en: "What is the second pillar of Islam?",
    options: ["Hajj", "Fasting", "Salah (Prayer)", "Zakat"],
    correct: 2,
    difficulty: "easy",
    topic: "Pillars of Islam",
  },
  {
    id: 29,
    question_hi: "आदम (अ.) इस्लाम में क्या माने जाते हैं?",
    question_hinglish: "Adam (AS) Islam mein kya maane jaate hain?",
    question_en: "What is Adam (AS) considered in Islam?",
    options: ["An angel", "First Prophet", "A king", "A scholar"],
    correct: 1,
    difficulty: "easy",
    topic: "Prophets",
  },
  {
    id: 30,
    question_hi: "'अल्लाहु अकबर' का क्या अर्थ है?",
    question_hinglish: "'Allahu Akbar' ka kya arth hai?",
    question_en: "What does 'Allahu Akbar' mean?",
    options: ["God is Merciful", "God is Great", "Praise be to God", "God is One"],
    correct: 1,
    difficulty: "easy",
    topic: "Arabic Phrases",
  },
  // ── MEDIUM (31-60) ───────────────────────────────────────────
  {
    id: 31,
    question_hi: "पाँच दैनिक नमाज़ों का सही क्रम क्या है?",
    question_hinglish: "Paanch daily namazon ka sahi kram kya hai?",
    question_en: "What is the correct order of the five daily prayers?",
    options: [
      "Fajr, Zuhr, Asr, Maghrib, Isha",
      "Fajr, Asr, Zuhr, Maghrib, Isha",
      "Zuhr, Fajr, Asr, Maghrib, Isha",
      "Fajr, Zuhr, Maghrib, Asr, Isha",
    ],
    correct: 0,
    difficulty: "medium",
    topic: "Prayer",
  },
  {
    id: 32,
    question_hi: "काबा किस नबी ने बनाया था?",
    question_hinglish: "Ka'bah kis Nabi ne banaya tha?",
    question_en: "Which Prophet built the Ka'bah?",
    options: ["Musa (AS)", "Nuh (AS)", "Ibrahim (AS)", "Isa (AS)"],
    correct: 2,
    difficulty: "medium",
    topic: "Prophets",
  },
  {
    id: 33,
    question_hi: "क़ुरआन की पहली वह्य कौन सी आयत थी?",
    question_hinglish: "Quran ki pehli wahi kaun si ayat thi?",
    question_en: "What was the first word/command revealed in the Quran?",
    options: ["Qul (Say)", "Iqra (Read)", "Sabbih (Glorify)", "Udhkur (Remember)"],
    correct: 1,
    difficulty: "medium",
    topic: "Revelation",
  },
  {
    id: 34,
    question_hi: "ग़ज़वा-ए-बद्र किस हिजरी सन में हुई?",
    question_hinglish: "Ghazwa-e-Badr kis Hijri san mein hui?",
    question_en: "In which year (AH) did the Battle of Badr take place?",
    options: ["1 AH", "2 AH", "3 AH", "4 AH"],
    correct: 1,
    difficulty: "medium",
    topic: "Islamic History",
  },
  {
    id: 35,
    question_hi: "क़ुरआन में नबी मुहम्मद ﷺ का नाम कितनी बार आया है?",
    question_hinglish: "Quran mein Nabi Muhammad ﷺ ka naam kitni baar aaya hai?",
    question_en: "How many times is Prophet Muhammad ﷺ mentioned by name in the Quran?",
    options: ["2", "4", "7", "25"],
    correct: 1,
    difficulty: "medium",
    topic: "Quran",
  },
  {
    id: 36,
    question_hi: "क़ुरआन की सबसे लंबी सूरह कौन सी है?",
    question_hinglish: "Quran ki sabse lambi Surah kaun si hai?",
    question_en: "What is the longest Surah in the Quran?",
    options: ["Al-Imran", "An-Nisa", "Al-Baqarah", "Al-Maidah"],
    correct: 2,
    difficulty: "medium",
    topic: "Quran",
  },
  {
    id: 37,
    question_hi: "क़ुरआन की सबसे छोटी सूरह कौन सी है?",
    question_hinglish: "Quran ki sabse chhoti Surah kaun si hai?",
    question_en: "What is the shortest Surah in the Quran?",
    options: ["Al-Ikhlas", "An-Nas", "Al-Kawthar", "Al-Asr"],
    correct: 2,
    difficulty: "medium",
    topic: "Quran",
  },
  {
    id: 38,
    question_hi: "इस्लाम के पहले ख़लीफ़ा कौन थे?",
    question_hinglish: "Islam ke pehle Khalifa kaun the?",
    question_en: "Who was the first Caliph of Islam?",
    options: ["Umar (RA)", "Uthman (RA)", "Ali (RA)", "Abu Bakr (RA)"],
    correct: 3,
    difficulty: "medium",
    topic: "Caliphs",
  },
  {
    id: 39,
    question_hi: "हिजरत (पलायन) किस शहर से किस शहर को हुई?",
    question_hinglish: "Hijrat kis shehar se kis shehar ko hui?",
    question_en: "The Hijrah (migration) was from which city to which city?",
    options: [
      "Madinah to Makkah",
      "Makkah to Taif",
      "Makkah to Madinah",
      "Makkah to Abyssinia",
    ],
    correct: 2,
    difficulty: "medium",
    topic: "Islamic History",
  },
  {
    id: 40,
    question_hi: "क़ुरआन किस ग़ार (गुफ़ा) में नाज़िल होना शुरू हुआ?",
    question_hinglish: "Quran kis Ghaar (gufa) mein nazil hona shuru hua?",
    question_en: "In which cave did the revelation of the Quran begin?",
    options: ["Cave of Thawr", "Cave of Hira", "Cave of Kahf", "Cave of Uhud"],
    correct: 1,
    difficulty: "medium",
    topic: "Revelation",
  },
  {
    id: 41,
    question_hi: "आयतुल कुर्सी क़ुरआन की किस सूरह में है?",
    question_hinglish: "Ayatul Kursi Quran ki kis Surah mein hai?",
    question_en: "Ayatul Kursi is in which Surah of the Quran?",
    options: ["Al-Imran", "Al-Baqarah", "An-Nisa", "Al-Maidah"],
    correct: 1,
    difficulty: "medium",
    topic: "Quran",
  },
  {
    id: 42,
    question_hi: "पैग़म्बर मुहम्मद ﷺ को नबूवत किस उम्र में मिली?",
    question_hinglish: "Prophet Muhammad ﷺ ko Nabuwwat kis umar mein mili?",
    question_en: "At what age did Prophet Muhammad ﷺ receive prophethood?",
    options: ["25", "30", "35", "40"],
    correct: 3,
    difficulty: "medium",
    topic: "Prophet Muhammad",
  },
  {
    id: 43,
    question_hi: "क़ुरआन कितने साल में मुकम्मल नाज़िल हुआ?",
    question_hinglish: "Quran kitne saal mein mukammal nazil hua?",
    question_en: "Over how many years was the Quran revealed?",
    options: ["10", "15", "20", "23"],
    correct: 3,
    difficulty: "medium",
    topic: "Revelation",
  },
  {
    id: 44,
    question_hi: "किस नबी को 'ख़लीलुल्लाह' (अल्लाह का दोस्त) कहा जाता है?",
    question_hinglish: "Kis Nabi ko 'Khalilullah' (Allah ka dost) kaha jaata hai?",
    question_en: "Which Prophet is known as 'Khalilullah' (Friend of Allah)?",
    options: ["Musa (AS)", "Isa (AS)", "Ibrahim (AS)", "Nuh (AS)"],
    correct: 2,
    difficulty: "medium",
    topic: "Prophets",
  },
  {
    id: 45,
    question_hi: "किस नबी को 'रूहुल्लाह' (अल्लाह की रूह) कहा जाता है?",
    question_hinglish: "Kis Nabi ko 'Ruhullah' (Allah ki Ruh) kaha jaata hai?",
    question_en: "Which Prophet is known as 'Ruhullah' (Spirit of Allah)?",
    options: ["Ibrahim (AS)", "Musa (AS)", "Isa (AS)", "Dawud (AS)"],
    correct: 2,
    difficulty: "medium",
    topic: "Prophets",
  },
  {
    id: 46,
    question_hi: "किस नबी को 'कलीमुल्लाह' (अल्लाह से बात करने वाला) कहा जाता है?",
    question_hinglish: "Kis Nabi ko 'Kalimullah' (Allah se baat karne wala) kaha jaata hai?",
    question_en: "Which Prophet is known as 'Kalimullah' (One who spoke to Allah)?",
    options: ["Isa (AS)", "Ibrahim (AS)", "Musa (AS)", "Yusuf (AS)"],
    correct: 2,
    difficulty: "medium",
    topic: "Prophets",
  },
  {
    id: 47,
    question_hi: "उहुद की लड़ाई किस हिजरी सन में हुई?",
    question_hinglish: "Uhud ki ladai kis Hijri san mein hui?",
    question_en: "In which year (AH) did the Battle of Uhud take place?",
    options: ["2 AH", "3 AH", "4 AH", "5 AH"],
    correct: 1,
    difficulty: "medium",
    topic: "Islamic History",
  },
  {
    id: 48,
    question_hi: "ज़मज़म का कुआँ किस शहर में है?",
    question_hinglish: "Zamzam ka kuan kis shehar mein hai?",
    question_en: "In which city is the well of Zamzam located?",
    options: ["Madinah", "Jerusalem", "Makkah", "Taif"],
    correct: 2,
    difficulty: "medium",
    topic: "Holy Places",
  },
  {
    id: 49,
    question_hi: "सूरह यासीन को क़ुरआन का _______ कहा जाता है।",
    question_hinglish: "Surah Yaseen ko Quran ka _______ kaha jaata hai.",
    question_en: "Surah Yaseen is called the _______ of the Quran.",
    options: ["Light", "Heart", "Crown", "Shield"],
    correct: 1,
    difficulty: "medium",
    topic: "Quran",
  },
  {
    id: 50,
    question_hi: "पैग़म्बर मुहम्मद ﷺ के कितने बेटे थे?",
    question_hinglish: "Prophet Muhammad ﷺ ke kitne bete the?",
    question_en: "How many sons did Prophet Muhammad ﷺ have?",
    options: ["1", "2", "3", "4"],
    correct: 2,
    difficulty: "medium",
    topic: "Prophet Muhammad",
  },
  {
    id: 51,
    question_hi: "पैग़म्बर मुहम्मद ﷺ की बेटी फ़ातिमा (रज़ि.) के पति कौन थे?",
    question_hinglish: "Prophet Muhammad ﷺ ki beti Fatimah (RA) ke pati kaun the?",
    question_en: "Who was the husband of Fatimah (RA), daughter of Prophet Muhammad ﷺ?",
    options: ["Umar (RA)", "Uthman (RA)", "Ali (RA)", "Abu Bakr (RA)"],
    correct: 2,
    difficulty: "medium",
    topic: "Prophet Muhammad",
  },
  {
    id: 52,
    question_hi: "इस्लाम में कितनी आसमानी किताबें हैं?",
    question_hinglish: "Islam mein kitni Aasmani Kitaabein hain?",
    question_en: "How many revealed books are recognized in Islam?",
    options: ["2", "3", "4", "5"],
    correct: 2,
    difficulty: "medium",
    topic: "Articles of Faith",
  },
  {
    id: 53,
    question_hi: "तौरात किस नबी पर नाज़िल हुई?",
    question_hinglish: "Tawrat kis Nabi par nazil hui?",
    question_en: "The Torah was revealed to which Prophet?",
    options: ["Isa (AS)", "Dawud (AS)", "Musa (AS)", "Ibrahim (AS)"],
    correct: 2,
    difficulty: "medium",
    topic: "Revealed Books",
  },
  {
    id: 54,
    question_hi: "ज़बूर किस नबी पर नाज़िल हुई?",
    question_hinglish: "Zabur kis Nabi par nazil hui?",
    question_en: "The Zabur (Psalms) was revealed to which Prophet?",
    options: ["Musa (AS)", "Dawud (AS)", "Isa (AS)", "Sulaiman (AS)"],
    correct: 1,
    difficulty: "medium",
    topic: "Revealed Books",
  },
  {
    id: 55,
    question_hi: "फ़त्ह मक्का (मक्का विजय) किस हिजरी सन में हुई?",
    question_hinglish: "Fath Makkah kis Hijri san mein hui?",
    question_en: "In which year (AH) did the Conquest of Makkah take place?",
    options: ["6 AH", "7 AH", "8 AH", "10 AH"],
    correct: 2,
    difficulty: "medium",
    topic: "Islamic History",
  },
  {
    id: 56,
    question_hi: "इस्राफ़ील (अ.) का क्या काम है?",
    question_hinglish: "Israfil (AS) ka kya kaam hai?",
    question_en: "What is the role of Angel Israfil (AS)?",
    options: [
      "Delivering revelation",
      "Recording deeds",
      "Blowing the trumpet on Judgment Day",
      "Taking souls",
    ],
    correct: 2,
    difficulty: "medium",
    topic: "Angels",
  },
  {
    id: 57,
    question_hi: "सूरह अल-मुल्क क़ुरआन के किस जुज़ (पारे) में है?",
    question_hinglish: "Surah Al-Mulk Quran ke kis Juz mein hai?",
    question_en: "Surah Al-Mulk is in which Juz (part) of the Quran?",
    options: ["28", "29", "30", "27"],
    correct: 1,
    difficulty: "medium",
    topic: "Quran",
  },
  {
    id: 58,
    question_hi: "निसाब क्या है?",
    question_hinglish: "Nisab kya hai?",
    question_en: "What is Nisab in Islam?",
    options: [
      "A type of prayer",
      "Minimum wealth for Zakat eligibility",
      "A fasting rule",
      "A pilgrimage ritual",
    ],
    correct: 1,
    difficulty: "medium",
    topic: "Zakat",
  },
  {
    id: 59,
    question_hi: "हदीस किसे कहते हैं?",
    question_hinglish: "Hadith kise kehte hain?",
    question_en: "What is a Hadith?",
    options: [
      "A chapter of the Quran",
      "Sayings and actions of Prophet Muhammad ﷺ",
      "An Islamic law book",
      "A prayer format",
    ],
    correct: 1,
    difficulty: "medium",
    topic: "Hadith",
  },
  {
    id: 60,
    question_hi: "सहीह बुख़ारी किसने संकलित की?",
    question_hinglish: "Sahih Bukhari kisne sankalit ki?",
    question_en: "Who compiled Sahih Bukhari?",
    options: [
      "Imam Muslim",
      "Imam Abu Dawud",
      "Imam Bukhari",
      "Imam Tirmidhi",
    ],
    correct: 2,
    difficulty: "medium",
    topic: "Hadith",
  },
  // ── HARD (61-90) ─────────────────────────────────────────────
  {
    id: 61,
    question_hi: "क़ुरआन में कितने नबियों का नाम लेकर ज़िक्र है?",
    question_hinglish: "Quran mein kitne Nabiyon ka naam lekar zikr hai?",
    question_en: "How many prophets are mentioned by name in the Quran?",
    options: ["20", "24", "25", "30"],
    correct: 2,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 62,
    question_hi: "क़ुरआन की आख़िरी नाज़िल होने वाली आयत किस सूरह में है?",
    question_hinglish: "Quran ki aakhiri nazil hone wali ayat kis Surah mein hai?",
    question_en: "The last revealed verse of the Quran is in which Surah?",
    options: ["Al-Baqarah 2:281", "Al-Maidah 5:3", "An-Nasr 110:3", "Al-Fatihah 1:1"],
    correct: 1,
    difficulty: "hard",
    topic: "Revelation",
  },
  {
    id: 63,
    question_hi: "मक्की सूरतें कितनी हैं?",
    question_hinglish: "Makki Suratein kitni hain?",
    question_en: "How many Makki (Meccan) Surahs are in the Quran?",
    options: ["86", "28", "60", "114"],
    correct: 0,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 64,
    question_hi: "मदनी सूरतें कितनी हैं?",
    question_hinglish: "Madani Suratein kitni hain?",
    question_en: "How many Madani (Medinan) Surahs are in the Quran?",
    options: ["86", "28", "30", "40"],
    correct: 1,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 65,
    question_hi: "क़ुरआन में कुल कितनी आयतें हैं?",
    question_hinglish: "Quran mein kul kitni ayatein hain?",
    question_en: "How many verses (ayat) are in the Quran?",
    options: ["5000", "6236", "6666", "7000"],
    correct: 1,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 66,
    question_hi: "सुलह हुदैबिया किस हिजरी सन में हुई?",
    question_hinglish: "Sulah Hudaibiya kis Hijri san mein hui?",
    question_en: "In which year (AH) did the Treaty of Hudaybiyyah take place?",
    options: ["4 AH", "5 AH", "6 AH", "7 AH"],
    correct: 2,
    difficulty: "hard",
    topic: "Islamic History",
  },
  {
    id: 67,
    question_hi: "क़ुरआन में किस नबी का सबसे ज़्यादा ज़िक्र है?",
    question_hinglish: "Quran mein kis Nabi ka sabse zyada zikr hai?",
    question_en: "Which Prophet is mentioned most frequently in the Quran?",
    options: ["Ibrahim (AS)", "Muhammad ﷺ", "Musa (AS)", "Isa (AS)"],
    correct: 2,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 68,
    question_hi: "क़ुरआन में किस एक औरत का नाम लिया गया है?",
    question_hinglish: "Quran mein kis ek aurat ka naam liya gaya hai?",
    question_en: "Which is the only woman mentioned by name in the Quran?",
    options: ["Khadijah", "Aisha", "Maryam", "Hajar"],
    correct: 2,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 69,
    question_hi: "सूरह अर-रहमान में 'फ़बि-अय्यि आलाई रब्बिकुमा तुक़ज़्ज़िबान' कितनी बार दोहराई गई है?",
    question_hinglish: "Surah Ar-Rahman mein 'Fabi-ayyi ala-i Rabbikuma tukazziban' kitni baar dohrayi gayi hai?",
    question_en: "How many times is 'Which of the favors of your Lord will you deny?' repeated in Surah Ar-Rahman?",
    options: ["25", "28", "31", "35"],
    correct: 2,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 70,
    question_hi: "किस सूरह में बिस्मिल्लाह दो बार आई है?",
    question_hinglish: "Kis Surah mein Bismillah do baar aayi hai?",
    question_en: "In which Surah does Bismillah appear twice?",
    options: ["Al-Fatihah", "An-Naml", "Al-Baqarah", "Yaseen"],
    correct: 1,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 71,
    question_hi: "उलुल अज़्म अंबिया कितने हैं?",
    question_hinglish: "Ulul Azm Ambiya kitne hain?",
    question_en: "How many Prophets of strong will (Ulul Azm) are there?",
    options: ["3", "4", "5", "7"],
    correct: 2,
    difficulty: "hard",
    topic: "Prophets",
  },
  {
    id: 72,
    question_hi: "हिज्र (शहर) किस क़ौम से संबंधित है?",
    question_hinglish: "Hijr (shehar) kis qaum se sambandhit hai?",
    question_en: "The city of Hijr is associated with which people?",
    options: ["People of Ad", "People of Thamud", "People of Lut", "People of Madyan"],
    correct: 1,
    difficulty: "hard",
    topic: "Quranic Nations",
  },
  {
    id: 73,
    question_hi: "क़ुरआन में सबसे लंबी आयत कौन सी है?",
    question_hinglish: "Quran mein sabse lambi ayat kaun si hai?",
    question_en: "What is the longest verse (ayah) in the Quran?",
    options: ["Al-Baqarah 2:255", "Al-Baqarah 2:282", "Al-Imran 3:7", "An-Nisa 4:11"],
    correct: 1,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 74,
    question_hi: "मेराज की रात पैग़म्बर ﷺ किस जानवर पर सवार थे?",
    question_hinglish: "Meraj ki raat Prophet ﷺ kis jaanwar par sawaar the?",
    question_en: "What was the name of the creature Prophet ﷺ rode during Isra and Miraj?",
    options: ["Duldul", "Buraq", "Qaswa", "Ya'fur"],
    correct: 1,
    difficulty: "hard",
    topic: "Prophet Muhammad",
  },
  {
    id: 75,
    question_hi: "किस ख़लीफ़ा के दौर में क़ुरआन को किताबी शक्ल में जमा किया गया?",
    question_hinglish: "Kis Khalifa ke daur mein Quran ko kitabi shakl mein jama kiya gaya?",
    question_en: "During which Caliph's reign was the Quran first compiled into a single book?",
    options: ["Umar (RA)", "Abu Bakr (RA)", "Uthman (RA)", "Ali (RA)"],
    correct: 1,
    difficulty: "hard",
    topic: "Quran Compilation",
  },
  {
    id: 76,
    question_hi: "किस ख़लीफ़ा ने क़ुरआन की मानक प्रतियाँ (मसाहिफ़) बनवाई?",
    question_hinglish: "Kis Khalifa ne Quran ki standard copies (Masahif) banvayi?",
    question_en: "Which Caliph standardized the written copies of the Quran?",
    options: ["Abu Bakr (RA)", "Umar (RA)", "Uthman (RA)", "Ali (RA)"],
    correct: 2,
    difficulty: "hard",
    topic: "Quran Compilation",
  },
  {
    id: 77,
    question_hi: "पैग़म्बर ﷺ ने कितने साल मक्का में दावत दी?",
    question_hinglish: "Prophet ﷺ ne kitne saal Makkah mein dawat di?",
    question_en: "How many years did Prophet ﷺ preach in Makkah before Hijrah?",
    options: ["10", "13", "15", "20"],
    correct: 1,
    difficulty: "hard",
    topic: "Prophet Muhammad",
  },
  {
    id: 78,
    question_hi: "ग़ज़वा-ए-ख़ंदक़ (ट्रेंच की लड़ाई) किस हिजरी सन में हुई?",
    question_hinglish: "Ghazwa-e-Khandaq kis Hijri san mein hui?",
    question_en: "In which year (AH) did the Battle of the Trench (Khandaq) take place?",
    options: ["3 AH", "4 AH", "5 AH", "6 AH"],
    correct: 2,
    difficulty: "hard",
    topic: "Islamic History",
  },
  {
    id: 79,
    question_hi: "क़ुरआन में 'अस्मा-उल-हुस्ना' (अल्लाह के सुंदर नाम) कितने हैं?",
    question_hinglish: "Quran mein 'Asma-ul-Husna' (Allah ke sundar naam) kitne hain?",
    question_en: "How many beautiful names of Allah (Asma-ul-Husna) are there?",
    options: ["72", "88", "99", "100"],
    correct: 2,
    difficulty: "hard",
    topic: "Names of Allah",
  },
  {
    id: 80,
    question_hi: "सूरह अल-कहफ़ में कितने क़िस्से हैं?",
    question_hinglish: "Surah Al-Kahf mein kitne qisse hain?",
    question_en: "How many main stories are narrated in Surah Al-Kahf?",
    options: ["2", "3", "4", "5"],
    correct: 2,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 81,
    question_hi: "किस नबी को मछली ने निगल लिया था?",
    question_hinglish: "Kis Nabi ko machhli ne nigal liya tha?",
    question_en: "Which Prophet was swallowed by a whale?",
    options: ["Musa (AS)", "Yunus (AS)", "Dawud (AS)", "Ilyas (AS)"],
    correct: 1,
    difficulty: "hard",
    topic: "Prophets",
  },
  {
    id: 82,
    question_hi: "पैग़म्बर ﷺ की वफ़ात किस हिजरी सन में हुई?",
    question_hinglish: "Prophet ﷺ ki wafat kis Hijri san mein hui?",
    question_en: "In which year (AH) did Prophet Muhammad ﷺ pass away?",
    options: ["8 AH", "9 AH", "10 AH", "11 AH"],
    correct: 3,
    difficulty: "hard",
    topic: "Prophet Muhammad",
  },
  {
    id: 83,
    question_hi: "क़ुरआन में 'सज्दा-ए-तिलावत' कितनी जगह हैं?",
    question_hinglish: "Quran mein 'Sajda-e-Tilawat' kitni jagah hain?",
    question_en: "How many places of prostration (Sajdah Tilawah) are in the Quran?",
    options: ["10", "14", "15", "20"],
    correct: 2,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 84,
    question_hi: "हब्शा (अबीसीनिया) की हिजरत कब हुई?",
    question_hinglish: "Habsha (Abyssinia) ki Hijrat kab hui?",
    question_en: "In which year of prophethood did the first migration to Abyssinia occur?",
    options: ["3rd year", "5th year", "7th year", "10th year"],
    correct: 1,
    difficulty: "hard",
    topic: "Islamic History",
  },
  {
    id: 85,
    question_hi: "क़ुरआन की किस सूरह को 'अरूसुल क़ुरआन' (क़ुरआन की दुल्हन) कहा जाता है?",
    question_hinglish: "Quran ki kis Surah ko 'Aroos-ul-Quran' (Quran ki dulhan) kaha jaata hai?",
    question_en: "Which Surah is called the 'Bride of the Quran' (Aroos-ul-Quran)?",
    options: ["Surah Yaseen", "Surah Ar-Rahman", "Surah Al-Mulk", "Surah Al-Kahf"],
    correct: 1,
    difficulty: "hard",
    topic: "Quran",
  },
  {
    id: 86,
    question_hi: "ग़ज़वा-ए-तबूक किस हिजरी सन में हुई?",
    question_hinglish: "Ghazwa-e-Tabuk kis Hijri san mein hui?",
    question_en: "In which year (AH) did the Expedition of Tabuk take place?",
    options: ["7 AH", "8 AH", "9 AH", "10 AH"],
    correct: 2,
    difficulty: "hard",
    topic: "Islamic History",
  },
  {
    id: 87,
    question_hi: "किस नबी ने अपने बेटे की क़ुर्बानी देने की तैयारी की थी?",
    question_hinglish: "Kis Nabi ne apne bete ki qurbani dene ki taiyari ki thi?",
    question_en: "Which Prophet was prepared to sacrifice his son by Allah's command?",
    options: ["Musa (AS)", "Nuh (AS)", "Ibrahim (AS)", "Yaqub (AS)"],
    correct: 2,
    difficulty: "hard",
    topic: "Prophets",
  },
  {
    id: 88,
    question_hi: "सिहाह सित्ता (छ: प्रामाणिक हदीस संग्रह) में कौन शामिल नहीं है?",
    question_hinglish: "Sihah Sitta (6 authentic Hadith collections) mein kaun shamil nahi hai?",
    question_en: "Which of the following is NOT one of the Sihah Sitta (Six Canonical Hadith Books)?",
    options: ["Sahih Bukhari", "Sahih Muslim", "Muwatta Imam Malik", "Sunan An-Nasai"],
    correct: 2,
    difficulty: "hard",
    topic: "Hadith",
  },
  {
    id: 89,
    question_hi: "किस सूरह में इंसान की पैदाइश के मराहिल बयान किए गए हैं?",
    question_hinglish: "Kis Surah mein insaan ki paidaish ke marahil bayan kiye gaye hain?",
    question_en: "Which Surah describes the stages of human embryonic development?",
    options: ["Al-Baqarah", "Al-Muminun", "An-Nur", "Al-Hadid"],
    correct: 1,
    difficulty: "hard",
    topic: "Quran & Science",
  },
  {
    id: 90,
    question_hi: "क़ुरआन में कितने रुकू हैं?",
    question_hinglish: "Quran mein kitne Ruku hain?",
    question_en: "How many Ruku (sections) are in the Quran?",
    options: ["400", "540", "558", "600"],
    correct: 2,
    difficulty: "hard",
    topic: "Quran",
  },
];
