export interface Hadith {
  id: number;
  arabic_text: string;
  english_text: string;
  narrator_en: string;
  collection: "bukhari" | "muslim" | "abu_dawud" | "tirmidhi";
  hadith_number: number;
  grade: "sahih" | "hasan";
  difficulty: "easy" | "medium" | "hard";
  topic: string;
}

export const CURATED_HADITHS: Hadith[] = [
  // ==================== EASY (1-50): Most Famous Hadiths ====================
  {
    id: 1,
    arabic_text: "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى",
    english_text: "Actions are judged by intentions, and every person will get what they intended.",
    narrator_en: "Umar ibn Al-Khattab",
    collection: "bukhari",
    hadith_number: 1,
    grade: "sahih",
    difficulty: "easy",
    topic: "intentions",
  },
  {
    id: 2,
    arabic_text: "بُنِيَ الْإِسْلَامُ عَلَى خَمْسٍ شَهَادَةِ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ وَإِقَامِ الصَّلَاةِ وَإِيتَاءِ الزَّكَاةِ وَالْحَجِّ وَصَوْمِ رَمَضَانَ",
    english_text: "Islam is built on five pillars: the testimony that there is no god but Allah and Muhammad is the Messenger of Allah, establishing prayer, paying zakat, performing Hajj, and fasting in Ramadan.",
    narrator_en: "Abdullah ibn Umar",
    collection: "bukhari",
    hadith_number: 8,
    grade: "sahih",
    difficulty: "easy",
    topic: "pillars of islam",
  },
  {
    id: 3,
    arabic_text: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",
    english_text: "None of you truly believes until he loves for his brother what he loves for himself.",
    narrator_en: "Anas ibn Malik",
    collection: "bukhari",
    hadith_number: 13,
    grade: "sahih",
    difficulty: "easy",
    topic: "faith",
  },
  {
    id: 4,
    arabic_text: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    english_text: "The best among you are those who learn the Quran and teach it.",
    narrator_en: "Uthman ibn Affan",
    collection: "bukhari",
    hadith_number: 5027,
    grade: "sahih",
    difficulty: "easy",
    topic: "quran",
  },
  {
    id: 5,
    arabic_text: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",
    english_text: "Whoever believes in Allah and the Last Day, let him speak good or remain silent.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 6018,
    grade: "sahih",
    difficulty: "easy",
    topic: "speech",
  },
  {
    id: 6,
    arabic_text: "لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ",
    english_text: "The strong person is not the one who can wrestle others, but the one who controls himself at the time of anger.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 6114,
    grade: "sahih",
    difficulty: "easy",
    topic: "anger management",
  },
  {
    id: 7,
    arabic_text: "يَسِّرُوا وَلَا تُعَسِّرُوا وَبَشِّرُوا وَلَا تُنَفِّرُوا",
    english_text: "Make things easy and do not make them difficult. Give good tidings and do not drive people away.",
    narrator_en: "Anas ibn Malik",
    collection: "bukhari",
    hadith_number: 69,
    grade: "sahih",
    difficulty: "easy",
    topic: "ease in religion",
  },
  {
    id: 8,
    arabic_text: "مِنْ حُسْنِ إِسْلَامِ الْمَرْءِ تَرْكُهُ مَا لَا يَعْنِيهِ",
    english_text: "Part of the perfection of a person's Islam is leaving that which does not concern him.",
    narrator_en: "Abu Hurairah",
    collection: "tirmidhi",
    hadith_number: 2317,
    grade: "hasan",
    difficulty: "easy",
    topic: "conduct",
  },
  {
    id: 9,
    arabic_text: "الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ",
    english_text: "The world is a prison for the believer and a paradise for the disbeliever.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 2956,
    grade: "sahih",
    difficulty: "easy",
    topic: "worldly life",
  },
  {
    id: 10,
    arabic_text: "الطُّهُورُ شَطْرُ الْإِيمَانِ",
    english_text: "Purity is half of faith.",
    narrator_en: "Abu Malik Al-Ashari",
    collection: "muslim",
    hadith_number: 223,
    grade: "sahih",
    difficulty: "easy",
    topic: "purification",
  },
  {
    id: 11,
    arabic_text: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ",
    english_text: "A Muslim is one from whose tongue and hand other Muslims are safe.",
    narrator_en: "Abdullah ibn Amr",
    collection: "bukhari",
    hadith_number: 10,
    grade: "sahih",
    difficulty: "easy",
    topic: "character",
  },
  {
    id: 12,
    arabic_text: "مَنْ غَشَّنَا فَلَيْسَ مِنَّا",
    english_text: "Whoever cheats us is not one of us.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 101,
    grade: "sahih",
    difficulty: "easy",
    topic: "honesty",
  },
  {
    id: 13,
    arabic_text: "لَا يَدْخُلُ الْجَنَّةَ مَنْ كَانَ فِي قَلْبِهِ مِثْقَالُ ذَرَّةٍ مِنْ كِبْرٍ",
    english_text: "No one who has an atom's weight of arrogance in his heart will enter Paradise.",
    narrator_en: "Abdullah ibn Masud",
    collection: "muslim",
    hadith_number: 91,
    grade: "sahih",
    difficulty: "easy",
    topic: "humility",
  },
  {
    id: 14,
    arabic_text: "الدِّينُ النَّصِيحَةُ",
    english_text: "The religion is sincere advice.",
    narrator_en: "Tamim Ad-Dari",
    collection: "muslim",
    hadith_number: 55,
    grade: "sahih",
    difficulty: "easy",
    topic: "sincerity",
  },
  {
    id: 15,
    arabic_text: "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ",
    english_text: "Whoever takes a path seeking knowledge, Allah will make easy for him a path to Paradise.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 2699,
    grade: "sahih",
    difficulty: "easy",
    topic: "knowledge",
  },
  {
    id: 16,
    arabic_text: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ",
    english_text: "Your smiling in the face of your brother is charity.",
    narrator_en: "Abu Dharr",
    collection: "tirmidhi",
    hadith_number: 1956,
    grade: "hasan",
    difficulty: "easy",
    topic: "charity",
  },
  {
    id: 17,
    arabic_text: "لَا ضَرَرَ وَلَا ضِرَارَ",
    english_text: "There should be no harm and no reciprocal harm.",
    narrator_en: "Abu Said Al-Khudri",
    collection: "muslim",
    hadith_number: 2341,
    grade: "sahih",
    difficulty: "easy",
    topic: "principles",
  },
  {
    id: 18,
    arabic_text: "إِنَّ اللَّهَ لَا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ",
    english_text: "Allah does not look at your appearances or wealth, but He looks at your hearts and deeds.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 2564,
    grade: "sahih",
    difficulty: "easy",
    topic: "sincerity",
  },
  {
    id: 19,
    arabic_text: "الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا",
    english_text: "The believer to another believer is like a building whose parts reinforce each other.",
    narrator_en: "Abu Musa Al-Ashari",
    collection: "bukhari",
    hadith_number: 6026,
    grade: "sahih",
    difficulty: "easy",
    topic: "brotherhood",
  },
  {
    id: 20,
    arabic_text: "خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ",
    english_text: "The best of people are those who are most beneficial to people.",
    narrator_en: "Jabir ibn Abdullah",
    collection: "tirmidhi",
    hadith_number: 2263,
    grade: "hasan",
    difficulty: "easy",
    topic: "service",
  },
  {
    id: 21,
    arabic_text: "مَنْ لَا يَرْحَمُ لَا يُرْحَمُ",
    english_text: "He who does not show mercy will not be shown mercy.",
    narrator_en: "Jarir ibn Abdullah",
    collection: "bukhari",
    hadith_number: 5997,
    grade: "sahih",
    difficulty: "easy",
    topic: "mercy",
  },
  {
    id: 22,
    arabic_text: "اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ",
    english_text: "Fear Allah wherever you are, follow a bad deed with a good deed and it will erase it, and treat people with good character.",
    narrator_en: "Abu Dharr",
    collection: "tirmidhi",
    hadith_number: 1987,
    grade: "hasan",
    difficulty: "easy",
    topic: "taqwa",
  },
  {
    id: 23,
    arabic_text: "إِنَّمَا بُعِثْتُ لِأُتَمِّمَ صَالِحَ الْأَخْلَاقِ",
    english_text: "I was only sent to perfect good character.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 273,
    grade: "sahih",
    difficulty: "easy",
    topic: "character",
  },
  {
    id: 24,
    arabic_text: "الْجَنَّةُ تَحْتَ أَقْدَامِ الْأُمَّهَاتِ",
    english_text: "Paradise is beneath the feet of mothers.",
    narrator_en: "Anas ibn Malik",
    collection: "tirmidhi",
    hadith_number: 3104,
    grade: "hasan",
    difficulty: "easy",
    topic: "parents",
  },
  {
    id: 25,
    arabic_text: "الْحَيَاءُ مِنَ الْإِيمَانِ",
    english_text: "Modesty is a branch of faith.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 9,
    grade: "sahih",
    difficulty: "easy",
    topic: "faith",
  },
  {
    id: 26,
    arabic_text: "الدُّعَاءُ هُوَ الْعِبَادَةُ",
    english_text: "Supplication is the essence of worship.",
    narrator_en: "An-Numan ibn Bashir",
    collection: "tirmidhi",
    hadith_number: 3371,
    grade: "sahih",
    difficulty: "easy",
    topic: "dua",
  },
  {
    id: 27,
    arabic_text: "مَنْ صَلَّى عَلَيَّ صَلَاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا",
    english_text: "Whoever sends blessings upon me once, Allah will send blessings upon him tenfold.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 408,
    grade: "sahih",
    difficulty: "easy",
    topic: "salawat",
  },
  {
    id: 28,
    arabic_text: "أَحَبُّ الْأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ",
    english_text: "The most beloved deeds to Allah are those done consistently, even if they are small.",
    narrator_en: "Aisha",
    collection: "bukhari",
    hadith_number: 6462,
    grade: "sahih",
    difficulty: "easy",
    topic: "consistency",
  },
  {
    id: 29,
    arabic_text: "كُلُّ مَعْرُوفٍ صَدَقَةٌ",
    english_text: "Every act of goodness is charity.",
    narrator_en: "Jabir ibn Abdullah",
    collection: "bukhari",
    hadith_number: 6021,
    grade: "sahih",
    difficulty: "easy",
    topic: "charity",
  },
  {
    id: 30,
    arabic_text: "إِذَا مَاتَ الْإِنْسَانُ انْقَطَعَ عَنْهُ عَمَلُهُ إِلَّا مِنْ ثَلَاثَةٍ إِلَّا مِنْ صَدَقَةٍ جَارِيَةٍ أَوْ عِلْمٍ يُنْتَفَعُ بِهِ أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ",
    english_text: "When a person dies, his deeds come to an end except for three: ongoing charity, beneficial knowledge, or a righteous child who prays for him.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 1631,
    grade: "sahih",
    difficulty: "easy",
    topic: "legacy",
  },
  {
    id: 31,
    arabic_text: "لَا تَغْضَبْ",
    english_text: "Do not become angry.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 6116,
    grade: "sahih",
    difficulty: "easy",
    topic: "anger management",
  },
  {
    id: 32,
    arabic_text: "الْمُسْلِمُ أَخُو الْمُسْلِمِ لَا يَظْلِمُهُ وَلَا يُسْلِمُهُ",
    english_text: "A Muslim is the brother of another Muslim. He does not wrong him or hand him over to harm.",
    narrator_en: "Abdullah ibn Umar",
    collection: "bukhari",
    hadith_number: 2442,
    grade: "sahih",
    difficulty: "easy",
    topic: "brotherhood",
  },
  {
    id: 33,
    arabic_text: "أَكْمَلُ الْمُؤْمِنِينَ إِيمَانًا أَحْسَنُهُمْ خُلُقًا",
    english_text: "The most complete of believers in faith are those with the best character.",
    narrator_en: "Abu Hurairah",
    collection: "tirmidhi",
    hadith_number: 1162,
    grade: "hasan",
    difficulty: "easy",
    topic: "character",
  },
  {
    id: 34,
    arabic_text: "مَا مَلَأَ آدَمِيٌّ وِعَاءً شَرًّا مِنْ بَطْنٍ",
    english_text: "No human has filled a vessel worse than his stomach.",
    narrator_en: "Al-Miqdam ibn Ma'dikarib",
    collection: "tirmidhi",
    hadith_number: 2380,
    grade: "sahih",
    difficulty: "easy",
    topic: "moderation",
  },
  {
    id: 35,
    arabic_text: "مَثَلُ الْجَلِيسِ الصَّالِحِ وَالْجَلِيسِ السَّوْءِ كَحَامِلِ الْمِسْكِ وَنَافِخِ الْكِيرِ",
    english_text: "The example of a good companion and a bad companion is like that of a musk seller and a blacksmith's bellows.",
    narrator_en: "Abu Musa Al-Ashari",
    collection: "bukhari",
    hadith_number: 5534,
    grade: "sahih",
    difficulty: "easy",
    topic: "companionship",
  },
  {
    id: 36,
    arabic_text: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيُكْرِمْ ضَيْفَهُ",
    english_text: "Whoever believes in Allah and the Last Day, let him honor his guest.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 6019,
    grade: "sahih",
    difficulty: "easy",
    topic: "hospitality",
  },
  {
    id: 37,
    arabic_text: "لَا يَشْكُرُ اللَّهَ مَنْ لَا يَشْكُرُ النَّاسَ",
    english_text: "He who does not thank people does not thank Allah.",
    narrator_en: "Abu Hurairah",
    collection: "tirmidhi",
    hadith_number: 1954,
    grade: "sahih",
    difficulty: "easy",
    topic: "gratitude",
  },
  {
    id: 38,
    arabic_text: "الصَّلَوَاتُ الْخَمْسُ وَالْجُمُعَةُ إِلَى الْجُمُعَةِ وَرَمَضَانُ إِلَى رَمَضَانَ مُكَفِّرَاتٌ مَا بَيْنَهُنَّ إِذَا اجْتُنِبَتِ الْكَبَائِرُ",
    english_text: "The five daily prayers, Friday to Friday, and Ramadan to Ramadan are expiation for sins between them, as long as major sins are avoided.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 233,
    grade: "sahih",
    difficulty: "easy",
    topic: "prayer",
  },
  {
    id: 39,
    arabic_text: "أَفْضَلُ الْجِهَادِ كَلِمَةُ حَقٍّ عِنْدَ سُلْطَانٍ جَائِرٍ",
    english_text: "The best form of striving is a word of truth before a tyrannical ruler.",
    narrator_en: "Abu Said Al-Khudri",
    collection: "tirmidhi",
    hadith_number: 2174,
    grade: "hasan",
    difficulty: "easy",
    topic: "justice",
  },
  {
    id: 40,
    arabic_text: "إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ فِي الْأَمْرِ كُلِّهِ",
    english_text: "Indeed, Allah is gentle and loves gentleness in all matters.",
    narrator_en: "Aisha",
    collection: "bukhari",
    hadith_number: 6927,
    grade: "sahih",
    difficulty: "easy",
    topic: "gentleness",
  },
  {
    id: 41,
    arabic_text: "مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ",
    english_text: "Charity does not decrease wealth.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 2588,
    grade: "sahih",
    difficulty: "easy",
    topic: "charity",
  },
  {
    id: 42,
    arabic_text: "كُلُّكُمْ رَاعٍ وَكُلُّكُمْ مَسْئُولٌ عَنْ رَعِيَّتِهِ",
    english_text: "Each of you is a shepherd and each of you is responsible for his flock.",
    narrator_en: "Abdullah ibn Umar",
    collection: "bukhari",
    hadith_number: 7138,
    grade: "sahih",
    difficulty: "easy",
    topic: "responsibility",
  },
  {
    id: 43,
    arabic_text: "إِنَّ مِنْ أَحَبِّكُمْ إِلَيَّ وَأَقْرَبِكُمْ مِنِّي مَجْلِسًا يَوْمَ الْقِيَامَةِ أَحَاسِنَكُمْ أَخْلَاقًا",
    english_text: "The dearest and closest of you to me on the Day of Judgment will be those with the best character.",
    narrator_en: "Jabir ibn Abdullah",
    collection: "tirmidhi",
    hadith_number: 2018,
    grade: "hasan",
    difficulty: "easy",
    topic: "character",
  },
  {
    id: 44,
    arabic_text: "مَنْ كَظَمَ غَيْظًا وَهُوَ قَادِرٌ عَلَى أَنْ يُنْفِذَهُ دَعَاهُ اللَّهُ عَلَى رُءُوسِ الْخَلَائِقِ يَوْمَ الْقِيَامَةِ",
    english_text: "Whoever suppresses his anger when he is able to act upon it, Allah will call him before all creation on the Day of Resurrection.",
    narrator_en: "Muadh ibn Anas",
    collection: "tirmidhi",
    hadith_number: 2021,
    grade: "hasan",
    difficulty: "easy",
    topic: "anger management",
  },
  {
    id: 45,
    arabic_text: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ",
    english_text: "O Allah, I seek refuge in You from worry and grief, from weakness and laziness.",
    narrator_en: "Anas ibn Malik",
    collection: "bukhari",
    hadith_number: 6369,
    grade: "sahih",
    difficulty: "easy",
    topic: "dua",
  },
  {
    id: 46,
    arabic_text: "الْحَلَالُ بَيِّنٌ وَالْحَرَامُ بَيِّنٌ وَبَيْنَهُمَا أُمُورٌ مُشْتَبِهَاتٌ",
    english_text: "The halal is clear and the haram is clear, and between them are doubtful matters.",
    narrator_en: "An-Numan ibn Bashir",
    collection: "bukhari",
    hadith_number: 52,
    grade: "sahih",
    difficulty: "easy",
    topic: "halal and haram",
  },
  {
    id: 47,
    arabic_text: "مَنْ قَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
    english_text: "Whoever stands in prayer during Ramadan out of faith and seeking reward, his previous sins will be forgiven.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 37,
    grade: "sahih",
    difficulty: "easy",
    topic: "ramadan",
  },
  {
    id: 48,
    arabic_text: "خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ وَأَنَا خَيْرُكُمْ لِأَهْلِي",
    english_text: "The best of you are those who are best to their families, and I am the best of you to my family.",
    narrator_en: "Aisha",
    collection: "tirmidhi",
    hadith_number: 3895,
    grade: "sahih",
    difficulty: "easy",
    topic: "family",
  },
  {
    id: 49,
    arabic_text: "إِنَّ اللَّهَ كَتَبَ الْإِحْسَانَ عَلَى كُلِّ شَيْءٍ",
    english_text: "Indeed, Allah has prescribed excellence in all things.",
    narrator_en: "Shaddad ibn Aws",
    collection: "muslim",
    hadith_number: 1955,
    grade: "sahih",
    difficulty: "easy",
    topic: "excellence",
  },
  {
    id: 50,
    arabic_text: "الْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ",
    english_text: "A good word is charity.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 2989,
    grade: "sahih",
    difficulty: "easy",
    topic: "speech",
  },
  // ==================== MEDIUM (51-100): Daily Life, Akhlaq, Family, Social ====================
  {
    id: 51,
    arabic_text: "مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ",
    english_text: "Whoever relieves a believer of a hardship in this world, Allah will relieve him of a hardship on the Day of Judgment.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 2699,
    grade: "sahih",
    difficulty: "medium",
    topic: "helping others",
  },
  {
    id: 52,
    arabic_text: "لَا تَحَاسَدُوا وَلَا تَنَاجَشُوا وَلَا تَبَاغَضُوا وَلَا تَدَابَرُوا وَلَا يَبِعْ بَعْضُكُمْ عَلَى بَيْعِ بَعْضٍ وَكُونُوا عِبَادَ اللَّهِ إِخْوَانًا",
    english_text: "Do not envy one another, do not inflate prices for one another, do not hate one another, do not turn your backs on one another, and be servants of Allah as brothers.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 2564,
    grade: "sahih",
    difficulty: "medium",
    topic: "social conduct",
  },
  {
    id: 53,
    arabic_text: "مَنْ أَصْبَحَ مِنْكُمْ آمِنًا فِي سِرْبِهِ مُعَافًى فِي جَسَدِهِ عِنْدَهُ قُوتُ يَوْمِهِ فَكَأَنَّمَا حِيزَتْ لَهُ الدُّنْيَا بِحَذَافِيرِهَا",
    english_text: "Whoever wakes up safe in his home, healthy in his body, and has his food for the day, it is as if the whole world has been gathered for him.",
    narrator_en: "Ubaidullah ibn Muhsin",
    collection: "tirmidhi",
    hadith_number: 2346,
    grade: "hasan",
    difficulty: "medium",
    topic: "gratitude",
  },
  {
    id: 54,
    arabic_text: "إِيَّاكُمْ وَالظَّنَّ فَإِنَّ الظَّنَّ أَكْذَبُ الْحَدِيثِ",
    english_text: "Beware of suspicion, for suspicion is the most false of speech.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 6064,
    grade: "sahih",
    difficulty: "medium",
    topic: "suspicion",
  },
  {
    id: 55,
    arabic_text: "مَنْ سَتَرَ مُسْلِمًا سَتَرَهُ اللَّهُ يَوْمَ الْقِيَامَةِ",
    english_text: "Whoever conceals the faults of a Muslim, Allah will conceal his faults on the Day of Judgment.",
    narrator_en: "Abdullah ibn Umar",
    collection: "bukhari",
    hadith_number: 2442,
    grade: "sahih",
    difficulty: "medium",
    topic: "concealing faults",
  },
  {
    id: 56,
    arabic_text: "أَنَا وَكَافِلُ الْيَتِيمِ فِي الْجَنَّةِ هَكَذَا وَأَشَارَ بِالسَّبَّابَةِ وَالْوُسْطَى وَفَرَّجَ بَيْنَهُمَا",
    english_text: "I and the caretaker of an orphan will be in Paradise like this — and he indicated with his index and middle fingers, holding them apart.",
    narrator_en: "Sahl ibn Saad",
    collection: "bukhari",
    hadith_number: 5304,
    grade: "sahih",
    difficulty: "medium",
    topic: "orphans",
  },
  {
    id: 57,
    arabic_text: "اسْتَحْيُوا مِنَ اللَّهِ حَقَّ الْحَيَاءِ قَالَ قُلْنَا يَا رَسُولَ اللَّهِ إِنَّا نَسْتَحْيِي وَالْحَمْدُ لِلَّهِ قَالَ لَيْسَ ذَاكَ وَلَكِنَّ الِاسْتِحْيَاءَ مِنَ اللَّهِ حَقَّ الْحَيَاءِ أَنْ تَحْفَظَ الرَّأْسَ وَمَا وَعَى وَالْبَطْنَ وَمَا حَوَى",
    english_text: "Be truly shy before Allah. True shyness before Allah means guarding the head and what it contains, and the stomach and what it holds.",
    narrator_en: "Abdullah ibn Masud",
    collection: "tirmidhi",
    hadith_number: 2458,
    grade: "hasan",
    difficulty: "medium",
    topic: "modesty",
  },
  {
    id: 58,
    arabic_text: "مَا مِنْ مُسْلِمٍ يَغْرِسُ غَرْسًا أَوْ يَزْرَعُ زَرْعًا فَيَأْكُلُ مِنْهُ طَيْرٌ أَوْ إِنْسَانٌ أَوْ بَهِيمَةٌ إِلَّا كَانَ لَهُ بِهِ صَدَقَةٌ",
    english_text: "No Muslim plants a tree or sows seeds from which a bird, human, or animal eats, except that it is counted as charity for him.",
    narrator_en: "Anas ibn Malik",
    collection: "bukhari",
    hadith_number: 2320,
    grade: "sahih",
    difficulty: "medium",
    topic: "environment",
  },
  {
    id: 59,
    arabic_text: "أَطْعِمُوا الْجَائِعَ وَعُودُوا الْمَرِيضَ وَفُكُّوا الْعَانِيَ",
    english_text: "Feed the hungry, visit the sick, and free the captive.",
    narrator_en: "Abu Musa Al-Ashari",
    collection: "bukhari",
    hadith_number: 5649,
    grade: "sahih",
    difficulty: "medium",
    topic: "social duty",
  },
  {
    id: 60,
    arabic_text: "لَا تَدْخُلُونَ الْجَنَّةَ حَتَّى تُؤْمِنُوا وَلَا تُؤْمِنُوا حَتَّى تَحَابُّوا أَوَلَا أَدُلُّكُمْ عَلَى شَيْءٍ إِذَا فَعَلْتُمُوهُ تَحَابَبْتُمْ أَفْشُوا السَّلَامَ بَيْنَكُمْ",
    english_text: "You will not enter Paradise until you believe, and you will not believe until you love one another. Shall I not tell you something that if you do it, you will love one another? Spread the greeting of peace among yourselves.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 54,
    grade: "sahih",
    difficulty: "medium",
    topic: "salaam",
  },
  {
    id: 61,
    arabic_text: "الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ ارْحَمُوا مَنْ فِي الْأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ",
    english_text: "The merciful are shown mercy by the Most Merciful. Be merciful to those on earth, and the One in the heavens will be merciful to you.",
    narrator_en: "Abdullah ibn Amr",
    collection: "tirmidhi",
    hadith_number: 1924,
    grade: "sahih",
    difficulty: "medium",
    topic: "mercy",
  },
  {
    id: 62,
    arabic_text: "مَا زَالَ جِبْرِيلُ يُوصِينِي بِالْجَارِ حَتَّى ظَنَنْتُ أَنَّهُ سَيُوَرِّثُهُ",
    english_text: "Jibreel kept advising me about the neighbor until I thought he would make him an heir.",
    narrator_en: "Aisha",
    collection: "bukhari",
    hadith_number: 6014,
    grade: "sahih",
    difficulty: "medium",
    topic: "neighbors",
  },
  {
    id: 63,
    arabic_text: "مَنْ أَكَلَ طَعَامًا ثُمَّ قَالَ الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
    english_text: "Whoever eats food and then says 'Praise be to Allah who fed me this and provided it for me without any power or might from me,' his previous sins will be forgiven.",
    narrator_en: "Muadh ibn Anas",
    collection: "tirmidhi",
    hadith_number: 3458,
    grade: "hasan",
    difficulty: "medium",
    topic: "food etiquette",
  },
  {
    id: 64,
    arabic_text: "مَنْ عَادَ مَرِيضًا لَمْ يَزَلْ فِي خُرْفَةِ الْجَنَّةِ حَتَّى يَرْجِعَ",
    english_text: "Whoever visits a sick person continues to be in the harvest of Paradise until he returns.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 2568,
    grade: "sahih",
    difficulty: "medium",
    topic: "visiting sick",
  },
  {
    id: 65,
    arabic_text: "لَيْسَ مِنَّا مَنْ لَمْ يَرْحَمْ صَغِيرَنَا وَيُوَقِّرْ كَبِيرَنَا",
    english_text: "He is not one of us who does not show mercy to our young ones and respect to our elders.",
    narrator_en: "Abdullah ibn Amr",
    collection: "tirmidhi",
    hadith_number: 1919,
    grade: "hasan",
    difficulty: "medium",
    topic: "respect",
  },
  {
    id: 66,
    arabic_text: "إِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ",
    english_text: "Truthfulness leads to righteousness, and righteousness leads to Paradise.",
    narrator_en: "Abdullah ibn Masud",
    collection: "bukhari",
    hadith_number: 6094,
    grade: "sahih",
    difficulty: "medium",
    topic: "truthfulness",
  },
  {
    id: 67,
    arabic_text: "مَنْ كَانَ فِي حَاجَةِ أَخِيهِ كَانَ اللَّهُ فِي حَاجَتِهِ",
    english_text: "Whoever fulfills the need of his brother, Allah will fulfill his need.",
    narrator_en: "Abdullah ibn Umar",
    collection: "bukhari",
    hadith_number: 2442,
    grade: "sahih",
    difficulty: "medium",
    topic: "helping others",
  },
  {
    id: 68,
    arabic_text: "إِنَّ الْكَذِبَ يَهْدِي إِلَى الْفُجُورِ وَإِنَّ الْفُجُورَ يَهْدِي إِلَى النَّارِ",
    english_text: "Lying leads to wickedness, and wickedness leads to the Hellfire.",
    narrator_en: "Abdullah ibn Masud",
    collection: "bukhari",
    hadith_number: 6094,
    grade: "sahih",
    difficulty: "medium",
    topic: "truthfulness",
  },
  {
    id: 69,
    arabic_text: "أَلَا أُخْبِرُكُمْ بِأَكْبَرِ الْكَبَائِرِ الْإِشْرَاكُ بِاللَّهِ وَعُقُوقُ الْوَالِدَيْنِ",
    english_text: "Shall I not inform you of the greatest of major sins? Associating partners with Allah and disobeying one's parents.",
    narrator_en: "Abu Bakrah",
    collection: "bukhari",
    hadith_number: 2654,
    grade: "sahih",
    difficulty: "medium",
    topic: "major sins",
  },
  {
    id: 70,
    arabic_text: "مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ",
    english_text: "When Allah wills good for a person, He grants him understanding of the religion.",
    narrator_en: "Muawiyah ibn Abi Sufyan",
    collection: "bukhari",
    hadith_number: 71,
    grade: "sahih",
    difficulty: "medium",
    topic: "knowledge",
  },
  {
    id: 71,
    arabic_text: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى",
    english_text: "O Allah, I ask You for guidance, piety, chastity, and self-sufficiency.",
    narrator_en: "Abdullah ibn Masud",
    collection: "muslim",
    hadith_number: 2721,
    grade: "sahih",
    difficulty: "medium",
    topic: "dua",
  },
  {
    id: 72,
    arabic_text: "لِكُلِّ أُمَّةٍ فِتْنَةٌ وَفِتْنَةُ أُمَّتِي الْمَالُ",
    english_text: "Every nation has its trial, and the trial of my nation is wealth.",
    narrator_en: "Kaab ibn Iyad",
    collection: "tirmidhi",
    hadith_number: 2336,
    grade: "sahih",
    difficulty: "medium",
    topic: "wealth",
  },
  {
    id: 73,
    arabic_text: "الْمُتَبَايِعَانِ بِالْخِيَارِ مَا لَمْ يَتَفَرَّقَا فَإِنْ صَدَقَا وَبَيَّنَا بُورِكَ لَهُمَا فِي بَيْعِهِمَا",
    english_text: "The two parties in a transaction have the option to cancel as long as they have not parted. If they are honest and transparent, their transaction will be blessed.",
    narrator_en: "Hakim ibn Hizam",
    collection: "bukhari",
    hadith_number: 2079,
    grade: "sahih",
    difficulty: "medium",
    topic: "trade",
  },
  {
    id: 74,
    arabic_text: "لَا يَحِلُّ لِمُسْلِمٍ أَنْ يَهْجُرَ أَخَاهُ فَوْقَ ثَلَاثِ لَيَالٍ",
    english_text: "It is not permissible for a Muslim to forsake his brother for more than three days.",
    narrator_en: "Abu Ayyub Al-Ansari",
    collection: "bukhari",
    hadith_number: 6077,
    grade: "sahih",
    difficulty: "medium",
    topic: "reconciliation",
  },
  {
    id: 75,
    arabic_text: "مَنْ قَرَأَ حَرْفًا مِنْ كِتَابِ اللَّهِ فَلَهُ بِهِ حَسَنَةٌ وَالْحَسَنَةُ بِعَشْرِ أَمْثَالِهَا",
    english_text: "Whoever reads a letter from the Book of Allah will receive a good deed, and each good deed is multiplied by ten.",
    narrator_en: "Abdullah ibn Masud",
    collection: "tirmidhi",
    hadith_number: 2910,
    grade: "sahih",
    difficulty: "medium",
    topic: "quran recitation",
  },
  {
    id: 76,
    arabic_text: "مَا مِنْ عَبْدٍ مُسْلِمٍ يَدْعُو لِأَخِيهِ بِظَهْرِ الْغَيْبِ إِلَّا قَالَ الْمَلَكُ وَلَكَ بِمِثْلٍ",
    english_text: "No Muslim servant supplicates for his brother behind his back except that the angel says: 'And for you the same.'",
    narrator_en: "Abu Darda",
    collection: "muslim",
    hadith_number: 2732,
    grade: "sahih",
    difficulty: "medium",
    topic: "dua",
  },
  {
    id: 77,
    arabic_text: "إِنَّ اللَّهَ لَا يَقْبِضُ الْعِلْمَ انْتِزَاعًا يَنْتَزِعُهُ مِنْ الْعِبَادِ وَلَكِنْ يَقْبِضُ الْعِلْمَ بِقَبْضِ الْعُلَمَاءِ",
    english_text: "Allah does not take away knowledge by snatching it from people, but He takes it away by the passing of scholars.",
    narrator_en: "Abdullah ibn Amr",
    collection: "bukhari",
    hadith_number: 100,
    grade: "sahih",
    difficulty: "medium",
    topic: "knowledge",
  },
  {
    id: 78,
    arabic_text: "لَيْسَ الْغِنَى عَنْ كَثْرَةِ الْعَرَضِ وَلَكِنَّ الْغِنَى غِنَى النَّفْسِ",
    english_text: "Richness is not having many possessions. Rather, true richness is the richness of the soul.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 6446,
    grade: "sahih",
    difficulty: "medium",
    topic: "contentment",
  },
  {
    id: 79,
    arabic_text: "انْصُرْ أَخَاكَ ظَالِمًا أَوْ مَظْلُومًا قَالُوا يَا رَسُولَ اللَّهِ هَذَا نَنْصُرُهُ مَظْلُومًا فَكَيْفَ نَنْصُرُهُ ظَالِمًا قَالَ تَأْخُذُ فَوْقَ يَدَيْهِ",
    english_text: "Help your brother whether he is an oppressor or oppressed. They asked: 'How do we help him if he is the oppressor?' He said: 'By restraining him.'",
    narrator_en: "Anas ibn Malik",
    collection: "bukhari",
    hadith_number: 2444,
    grade: "sahih",
    difficulty: "medium",
    topic: "justice",
  },
  {
    id: 80,
    arabic_text: "الْمُسْلِمُ إِذَا سُئِلَ فِي الْقَبْرِ يَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ فَذَلِكَ قَوْلُهُ يُثَبِّتُ اللَّهُ الَّذِينَ آمَنُوا بِالْقَوْلِ الثَّابِتِ",
    english_text: "When a Muslim is questioned in the grave, he testifies that there is no god but Allah and Muhammad is His Messenger. That is the meaning of the verse: 'Allah keeps firm those who believe with the firm word.'",
    narrator_en: "Al-Bara ibn Azib",
    collection: "bukhari",
    hadith_number: 1369,
    grade: "sahih",
    difficulty: "medium",
    topic: "afterlife",
  },
  {
    id: 81,
    arabic_text: "حَقُّ الْمُسْلِمِ عَلَى الْمُسْلِمِ خَمْسٌ رَدُّ السَّلَامِ وَعِيَادَةُ الْمَرِيضِ وَاتِّبَاعُ الْجَنَائِزِ وَإِجَابَةُ الدَّعْوَةِ وَتَشْمِيتُ الْعَاطِسِ",
    english_text: "The rights of a Muslim upon another Muslim are five: returning the greeting, visiting the sick, following funeral processions, accepting invitations, and saying 'yarhamukallah' to one who sneezes.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 1240,
    grade: "sahih",
    difficulty: "medium",
    topic: "muslim rights",
  },
  {
    id: 82,
    arabic_text: "مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
    english_text: "Whoever fasts Ramadan out of faith and seeking reward, his previous sins will be forgiven.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 38,
    grade: "sahih",
    difficulty: "medium",
    topic: "fasting",
  },
  {
    id: 83,
    arabic_text: "مَنْ صَلَّى الْبَرْدَيْنِ دَخَلَ الْجَنَّةَ",
    english_text: "Whoever prays the two cool prayers (Fajr and Asr) will enter Paradise.",
    narrator_en: "Abu Musa Al-Ashari",
    collection: "bukhari",
    hadith_number: 574,
    grade: "sahih",
    difficulty: "medium",
    topic: "prayer",
  },
  {
    id: 84,
    arabic_text: "إِنَّ فِي الْجَسَدِ مُضْغَةً إِذَا صَلَحَتْ صَلَحَ الْجَسَدُ كُلُّهُ وَإِذَا فَسَدَتْ فَسَدَ الْجَسَدُ كُلُّهُ أَلَا وَهِيَ الْقَلْبُ",
    english_text: "In the body there is a morsel of flesh; if it is sound, the whole body is sound. If it is corrupt, the whole body is corrupt. It is the heart.",
    narrator_en: "An-Numan ibn Bashir",
    collection: "bukhari",
    hadith_number: 52,
    grade: "sahih",
    difficulty: "medium",
    topic: "heart",
  },
  {
    id: 85,
    arabic_text: "مَنْ حُسِبَ حُوسِبَ عُذِّبَ",
    english_text: "Whoever is called to account will be punished.",
    narrator_en: "Aisha",
    collection: "bukhari",
    hadith_number: 6536,
    grade: "sahih",
    difficulty: "medium",
    topic: "accountability",
  },
  {
    id: 86,
    arabic_text: "مَنْ قَالَ سُبْحَانَ اللَّهِ وَبِحَمْدِهِ فِي يَوْمٍ مِائَةَ مَرَّةٍ حُطَّتْ خَطَايَاهُ وَإِنْ كَانَتْ مِثْلَ زَبَدِ الْبَحْرِ",
    english_text: "Whoever says 'SubhanAllahi wa bihamdihi' a hundred times during the day, his sins will be wiped away even if they are like the foam of the sea.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 6405,
    grade: "sahih",
    difficulty: "medium",
    topic: "dhikr",
  },
  {
    id: 87,
    arabic_text: "سَبْعَةٌ يُظِلُّهُمُ اللَّهُ فِي ظِلِّهِ يَوْمَ لَا ظِلَّ إِلَّا ظِلُّهُ إِمَامٌ عَادِلٌ وَشَابٌّ نَشَأَ فِي عِبَادَةِ اللَّهِ",
    english_text: "Seven will be shaded by Allah on a day when there is no shade but His: a just ruler, a youth raised in the worship of Allah...",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 660,
    grade: "sahih",
    difficulty: "medium",
    topic: "day of judgment",
  },
  {
    id: 88,
    arabic_text: "مَنْ بَنَى مَسْجِدًا لِلَّهِ بَنَى اللَّهُ لَهُ مِثْلَهُ فِي الْجَنَّةِ",
    english_text: "Whoever builds a mosque for the sake of Allah, Allah will build for him a similar one in Paradise.",
    narrator_en: "Uthman ibn Affan",
    collection: "bukhari",
    hadith_number: 450,
    grade: "sahih",
    difficulty: "medium",
    topic: "mosque",
  },
  {
    id: 89,
    arabic_text: "اقْرَءُوا الْقُرْآنَ فَإِنَّهُ يَأْتِي يَوْمَ الْقِيَامَةِ شَفِيعًا لِأَصْحَابِهِ",
    english_text: "Read the Quran, for it will come on the Day of Judgment as an intercessor for its companions.",
    narrator_en: "Abu Umamah",
    collection: "muslim",
    hadith_number: 804,
    grade: "sahih",
    difficulty: "medium",
    topic: "quran",
  },
  {
    id: 90,
    arabic_text: "أَحَبُّ الْبِلَادِ إِلَى اللَّهِ مَسَاجِدُهَا وَأَبْغَضُ الْبِلَادِ إِلَى اللَّهِ أَسْوَاقُهَا",
    english_text: "The most beloved places to Allah are the mosques, and the most hated places to Allah are the marketplaces.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 671,
    grade: "sahih",
    difficulty: "medium",
    topic: "mosque",
  },
  {
    id: 91,
    arabic_text: "مَنْ تَوَضَّأَ فَأَحْسَنَ الْوُضُوءَ خَرَجَتْ خَطَايَاهُ مِنْ جَسَدِهِ حَتَّى تَخْرُجَ مِنْ تَحْتِ أَظْفَارِهِ",
    english_text: "Whoever performs wudu and does it well, his sins will come out from his body, even from beneath his nails.",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 245,
    grade: "sahih",
    difficulty: "medium",
    topic: "wudu",
  },
  {
    id: 92,
    arabic_text: "مَنْ قَالَ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ فِي يَوْمٍ مِائَةَ مَرَّةٍ كَانَتْ لَهُ عَدْلَ عَشْرِ رِقَابٍ",
    english_text: "Whoever says 'La ilaha illallah wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa huwa ala kulli shayin qadir' a hundred times a day, it will be equivalent to freeing ten slaves.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 6403,
    grade: "sahih",
    difficulty: "medium",
    topic: "dhikr",
  },
  {
    id: 93,
    arabic_text: "مَنْ صَلَّى اثْنَتَيْ عَشْرَةَ رَكْعَةً فِي يَوْمٍ وَلَيْلَةٍ بُنِيَ لَهُ بَيْتٌ فِي الْجَنَّةِ",
    english_text: "Whoever prays twelve voluntary rak'ahs in a day and night, a house will be built for him in Paradise.",
    narrator_en: "Umm Habibah",
    collection: "muslim",
    hadith_number: 728,
    grade: "sahih",
    difficulty: "medium",
    topic: "voluntary prayer",
  },
  {
    id: 94,
    arabic_text: "إِنَّ أَثْقَلَ صَلَاةٍ عَلَى الْمُنَافِقِينَ صَلَاةُ الْعِشَاءِ وَصَلَاةُ الْفَجْرِ",
    english_text: "The heaviest prayers upon the hypocrites are the Isha and Fajr prayers.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 657,
    grade: "sahih",
    difficulty: "medium",
    topic: "prayer",
  },
  {
    id: 95,
    arabic_text: "مَنْ قَامَ لَيْلَةَ الْقَدْرِ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
    english_text: "Whoever stands in prayer on the Night of Decree out of faith and seeking reward, his previous sins will be forgiven.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 1901,
    grade: "sahih",
    difficulty: "medium",
    topic: "laylatul qadr",
  },
  {
    id: 96,
    arabic_text: "مَنْ غَدَا إِلَى الْمَسْجِدِ أَوْ رَاحَ أَعَدَّ اللَّهُ لَهُ فِي الْجَنَّةِ نُزُلًا كُلَّمَا غَدَا أَوْ رَاحَ",
    english_text: "Whoever goes to the mosque in the morning or evening, Allah prepares a place of hospitality for him in Paradise each time he goes.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 662,
    grade: "sahih",
    difficulty: "medium",
    topic: "mosque",
  },
  {
    id: 97,
    arabic_text: "مَنْ سَأَلَ اللَّهَ الشَّهَادَةَ بِصِدْقٍ بَلَّغَهُ اللَّهُ مَنَازِلَ الشُّهَدَاءِ وَإِنْ مَاتَ عَلَى فِرَاشِهِ",
    english_text: "Whoever sincerely asks Allah for martyrdom, Allah will grant him the rank of the martyrs, even if he dies in his bed.",
    narrator_en: "Sahl ibn Hunayf",
    collection: "muslim",
    hadith_number: 1909,
    grade: "sahih",
    difficulty: "medium",
    topic: "sincerity",
  },
  {
    id: 98,
    arabic_text: "خَيْرُ الصَّدَقَةِ مَا كَانَ عَنْ ظَهْرِ غِنًى",
    english_text: "The best charity is that which is given when one is self-sufficient.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 1426,
    grade: "sahih",
    difficulty: "medium",
    topic: "charity",
  },
  {
    id: 99,
    arabic_text: "ازْهَدْ فِي الدُّنْيَا يُحِبَّكَ اللَّهُ وَازْهَدْ فِيمَا عِنْدَ النَّاسِ يُحِبَّكَ النَّاسُ",
    english_text: "Be detached from the world and Allah will love you. Be detached from what people have and people will love you.",
    narrator_en: "Sahl ibn Saad",
    collection: "tirmidhi",
    hadith_number: 2318,
    grade: "hasan",
    difficulty: "medium",
    topic: "asceticism",
  },
  {
    id: 100,
    arabic_text: "إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ",
    english_text: "Indeed, Allah loves that when one of you does a task, he does it with excellence.",
    narrator_en: "Aisha",
    collection: "abu_dawud",
    hadith_number: 5104,
    grade: "hasan",
    difficulty: "medium",
    topic: "excellence",
  },
  // ==================== HARD (101-150): Theological, Fiqh, Lesser-Known ====================
  {
    id: 101,
    arabic_text: "أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَهَى عَنْ بَيْعِ الْغَرَرِ",
    english_text: "The Messenger of Allah ﷺ prohibited the sale involving uncertainty (gharar).",
    narrator_en: "Abu Hurairah",
    collection: "muslim",
    hadith_number: 1513,
    grade: "sahih",
    difficulty: "hard",
    topic: "islamic finance",
  },
  {
    id: 102,
    arabic_text: "رُفِعَ الْقَلَمُ عَنْ ثَلَاثَةٍ عَنِ النَّائِمِ حَتَّى يَسْتَيْقِظَ وَعَنِ الصَّبِيِّ حَتَّى يَحْتَلِمَ وَعَنِ الْمَجْنُونِ حَتَّى يَعْقِلَ",
    english_text: "The pen is lifted from three: the sleeper until he wakes, the child until he reaches puberty, and the insane until he regains his sanity.",
    narrator_en: "Ali ibn Abi Talib",
    collection: "abu_dawud",
    hadith_number: 4403,
    grade: "sahih",
    difficulty: "hard",
    topic: "legal responsibility",
  },
  {
    id: 103,
    arabic_text: "إِذَا حَكَمَ الْحَاكِمُ فَاجْتَهَدَ ثُمَّ أَصَابَ فَلَهُ أَجْرَانِ وَإِذَا حَكَمَ فَاجْتَهَدَ ثُمَّ أَخْطَأَ فَلَهُ أَجْرٌ",
    english_text: "If a judge makes a ruling and strives to reach the correct conclusion and gets it right, he has two rewards. If he strives and gets it wrong, he has one reward.",
    narrator_en: "Amr ibn Al-As",
    collection: "bukhari",
    hadith_number: 7352,
    grade: "sahih",
    difficulty: "hard",
    topic: "ijtihad",
  },
  {
    id: 104,
    arabic_text: "أُمِرْتُ أَنْ أَسْجُدَ عَلَى سَبْعَةِ أَعْظُمٍ عَلَى الْجَبْهَةِ وَأَشَارَ بِيَدِهِ إِلَى أَنْفِهِ وَالْيَدَيْنِ وَالرُّكْبَتَيْنِ وَأَطْرَافِ الْقَدَمَيْنِ",
    english_text: "I have been commanded to prostrate on seven bones: the forehead — and he pointed to his nose — the hands, the knees, and the tips of the feet.",
    narrator_en: "Abdullah ibn Abbas",
    collection: "bukhari",
    hadith_number: 812,
    grade: "sahih",
    difficulty: "hard",
    topic: "prayer posture",
  },
  {
    id: 105,
    arabic_text: "لَا صَلَاةَ لِمَنْ لَمْ يَقْرَأْ بِفَاتِحَةِ الْكِتَابِ",
    english_text: "There is no prayer for the one who does not recite the Opening of the Book (Al-Fatiha).",
    narrator_en: "Ubadah ibn As-Samit",
    collection: "bukhari",
    hadith_number: 756,
    grade: "sahih",
    difficulty: "hard",
    topic: "prayer requirements",
  },
  {
    id: 106,
    arabic_text: "إِنَّ اللَّهَ تَجَاوَزَ عَنْ أُمَّتِي الْخَطَأَ وَالنِّسْيَانَ وَمَا اسْتُكْرِهُوا عَلَيْهِ",
    english_text: "Allah has pardoned my ummah for mistakes, forgetfulness, and what they are coerced into doing.",
    narrator_en: "Abdullah ibn Abbas",
    collection: "tirmidhi",
    hadith_number: 2043,
    grade: "hasan",
    difficulty: "hard",
    topic: "legal maxims",
  },
  {
    id: 107,
    arabic_text: "الْبَيِّنَةُ عَلَى الْمُدَّعِي وَالْيَمِينُ عَلَى الْمُدَّعَى عَلَيْهِ",
    english_text: "The burden of proof is upon the claimant, and the oath is upon the one who denies.",
    narrator_en: "Abdullah ibn Abbas",
    collection: "tirmidhi",
    hadith_number: 1341,
    grade: "hasan",
    difficulty: "hard",
    topic: "islamic jurisprudence",
  },
  {
    id: 108,
    arabic_text: "صَلُّوا كَمَا رَأَيْتُمُونِي أُصَلِّي",
    english_text: "Pray as you have seen me praying.",
    narrator_en: "Malik ibn Al-Huwayrith",
    collection: "bukhari",
    hadith_number: 631,
    grade: "sahih",
    difficulty: "hard",
    topic: "prayer method",
  },
  {
    id: 109,
    arabic_text: "خُذُوا عَنِّي مَنَاسِكَكُمْ",
    english_text: "Take your rites of Hajj from me.",
    narrator_en: "Jabir ibn Abdullah",
    collection: "muslim",
    hadith_number: 1297,
    grade: "sahih",
    difficulty: "hard",
    topic: "hajj",
  },
  {
    id: 110,
    arabic_text: "مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ مِنْهُ فَهُوَ رَدٌّ",
    english_text: "Whoever introduces into this matter of ours something that is not part of it, it is rejected.",
    narrator_en: "Aisha",
    collection: "bukhari",
    hadith_number: 2697,
    grade: "sahih",
    difficulty: "hard",
    topic: "innovation",
  },
  {
    id: 111,
    arabic_text: "لَا وَصِيَّةَ لِوَارِثٍ",
    english_text: "There is no bequest for an heir.",
    narrator_en: "Abu Umamah",
    collection: "tirmidhi",
    hadith_number: 2120,
    grade: "sahih",
    difficulty: "hard",
    topic: "inheritance",
  },
  {
    id: 112,
    arabic_text: "لَا يَرِثُ الْمُسْلِمُ الْكَافِرَ وَلَا الْكَافِرُ الْمُسْلِمَ",
    english_text: "A Muslim does not inherit from a disbeliever, nor does a disbeliever inherit from a Muslim.",
    narrator_en: "Usamah ibn Zayd",
    collection: "bukhari",
    hadith_number: 6764,
    grade: "sahih",
    difficulty: "hard",
    topic: "inheritance",
  },
  {
    id: 113,
    arabic_text: "أَنَّ النَّبِيَّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَهَى عَنِ الْمُزَابَنَةِ وَالْمُحَاقَلَةِ",
    english_text: "The Prophet ﷺ forbade muzabanah (selling fresh dates for dried dates by estimation) and muhaqalah (selling unharvested wheat for harvested wheat).",
    narrator_en: "Abdullah ibn Umar",
    collection: "bukhari",
    hadith_number: 2186,
    grade: "sahih",
    difficulty: "hard",
    topic: "trade law",
  },
  {
    id: 114,
    arabic_text: "لَا تُنْكَحُ الْأَيِّمُ حَتَّى تُسْتَأْمَرَ وَلَا تُنْكَحُ الْبِكْرُ حَتَّى تُسْتَأْذَنَ",
    english_text: "A previously married woman should not be married until she is consulted, and a virgin should not be married until her permission is sought.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 5136,
    grade: "sahih",
    difficulty: "hard",
    topic: "marriage consent",
  },
  {
    id: 115,
    arabic_text: "لَا يَقْضِيَنَّ حَكَمٌ بَيْنَ اثْنَيْنِ وَهُوَ غَضْبَانُ",
    english_text: "A judge should not pass judgment between two people while he is angry.",
    narrator_en: "Abu Bakrah",
    collection: "bukhari",
    hadith_number: 7158,
    grade: "sahih",
    difficulty: "hard",
    topic: "judicial conduct",
  },
  {
    id: 116,
    arabic_text: "إِنَّ اللَّهَ فَرَضَ فَرَائِضَ فَلَا تُضَيِّعُوهَا وَحَدَّ حُدُودًا فَلَا تَعْتَدُوهَا وَحَرَّمَ أَشْيَاءَ فَلَا تَنْتَهِكُوهَا وَسَكَتَ عَنْ أَشْيَاءَ رَحْمَةً بِكُمْ غَيْرَ نِسْيَانٍ فَلَا تَسْأَلُوا عَنْهَا",
    english_text: "Allah has made certain obligations, so do not neglect them. He has set limits, so do not transgress them. He has forbidden things, so do not violate them. And He has remained silent about things out of mercy, not forgetfulness, so do not ask about them.",
    narrator_en: "Abu Thalabah Al-Khushani",
    collection: "tirmidhi",
    hadith_number: 1726,
    grade: "hasan",
    difficulty: "hard",
    topic: "legal principles",
  },
  {
    id: 117,
    arabic_text: "الْخَرَاجُ بِالضَّمَانِ",
    english_text: "Revenue comes with liability (profit is linked to risk).",
    narrator_en: "Aisha",
    collection: "tirmidhi",
    hadith_number: 1285,
    grade: "hasan",
    difficulty: "hard",
    topic: "islamic finance",
  },
  {
    id: 118,
    arabic_text: "أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ قَضَى بِالشُّفْعَةِ فِي كُلِّ مَا لَمْ يُقْسَمْ",
    english_text: "The Messenger of Allah ﷺ ruled that pre-emption (shuf'ah) applies to every undivided jointly-owned property.",
    narrator_en: "Jabir ibn Abdullah",
    collection: "bukhari",
    hadith_number: 2257,
    grade: "sahih",
    difficulty: "hard",
    topic: "property law",
  },
  {
    id: 119,
    arabic_text: "مَطْلُ الْغَنِيِّ ظُلْمٌ",
    english_text: "The delay of payment by a wealthy person is injustice.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 2287,
    grade: "sahih",
    difficulty: "hard",
    topic: "debt",
  },
  {
    id: 120,
    arabic_text: "مَنِ اقْتَطَعَ حَقَّ امْرِئٍ مُسْلِمٍ بِيَمِينِهِ فَقَدْ أَوْجَبَ اللَّهُ لَهُ النَّارَ وَحَرَّمَ عَلَيْهِ الْجَنَّةَ",
    english_text: "Whoever seizes the right of a Muslim by a false oath, Allah will decree the Fire for him and forbid him Paradise.",
    narrator_en: "Abu Umamah",
    collection: "muslim",
    hadith_number: 137,
    grade: "sahih",
    difficulty: "hard",
    topic: "false oaths",
  },
  {
    id: 121,
    arabic_text: "إِنَّ أَعْظَمَ الْفِرْيَةِ أَنْ يَدَّعِيَ الرَّجُلُ إِلَى غَيْرِ أَبِيهِ",
    english_text: "Indeed, the gravest falsehood is for a man to claim descent from someone other than his father.",
    narrator_en: "Abu Dharr",
    collection: "bukhari",
    hadith_number: 3508,
    grade: "sahih",
    difficulty: "hard",
    topic: "lineage",
  },
  {
    id: 122,
    arabic_text: "نَهَى رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ عَنْ بَيْعِ الثَّمَرَةِ حَتَّى يَبْدُوَ صَلَاحُهَا",
    english_text: "The Messenger of Allah ﷺ forbade selling fruit until its ripeness becomes apparent.",
    narrator_en: "Abdullah ibn Umar",
    collection: "bukhari",
    hadith_number: 2194,
    grade: "sahih",
    difficulty: "hard",
    topic: "trade conditions",
  },
  {
    id: 123,
    arabic_text: "لَعَنَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ آكِلَ الرِّبَا وَمُوكِلَهُ وَكَاتِبَهُ وَشَاهِدَيْهِ",
    english_text: "The Messenger of Allah ﷺ cursed the one who consumes riba (interest), the one who pays it, the one who writes it, and the two witnesses to it.",
    narrator_en: "Jabir ibn Abdullah",
    collection: "muslim",
    hadith_number: 1598,
    grade: "sahih",
    difficulty: "hard",
    topic: "riba",
  },
  {
    id: 124,
    arabic_text: "إِنَّ الدِّينَ يُسْرٌ وَلَنْ يُشَادَّ الدِّينَ أَحَدٌ إِلَّا غَلَبَهُ",
    english_text: "Indeed, this religion is easy, and no one overburdens himself in religion except that it overwhelms him.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 39,
    grade: "sahih",
    difficulty: "hard",
    topic: "ease in religion",
  },
  {
    id: 125,
    arabic_text: "أَنَّ النَّبِيَّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَهَى عَنْ بَيْعَتَيْنِ فِي بَيْعَةٍ",
    english_text: "The Prophet ﷺ prohibited two transactions in one transaction.",
    narrator_en: "Abu Hurairah",
    collection: "tirmidhi",
    hadith_number: 1231,
    grade: "sahih",
    difficulty: "hard",
    topic: "trade law",
  },
  {
    id: 126,
    arabic_text: "أَيُّمَا امْرَأَةٍ نَكَحَتْ بِغَيْرِ إِذْنِ وَلِيِّهَا فَنِكَاحُهَا بَاطِلٌ",
    english_text: "Any woman who marries without the permission of her guardian, her marriage is invalid.",
    narrator_en: "Aisha",
    collection: "tirmidhi",
    hadith_number: 1102,
    grade: "sahih",
    difficulty: "hard",
    topic: "marriage law",
  },
  {
    id: 127,
    arabic_text: "لَا نِكَاحَ إِلَّا بِوَلِيٍّ",
    english_text: "There is no marriage except with a guardian.",
    narrator_en: "Abu Musa Al-Ashari",
    collection: "tirmidhi",
    hadith_number: 1101,
    grade: "sahih",
    difficulty: "hard",
    topic: "marriage requirements",
  },
  {
    id: 128,
    arabic_text: "مَنْ أَعْتَقَ شِرْكًا لَهُ فِي عَبْدٍ فَكَانَ لَهُ مَالٌ يَبْلُغُ ثَمَنَ الْعَبْدِ قُوِّمَ الْعَبْدُ عَلَيْهِ قِيمَةَ عَدْلٍ فَأَعْطَى شُرَكَاءَهُ حِصَصَهُمْ وَعَتَقَ عَلَيْهِ",
    english_text: "Whoever frees his share of a jointly-owned slave and has enough money, the slave's fair value is assessed. He pays the co-owners their shares, and the slave is freed.",
    narrator_en: "Abdullah ibn Umar",
    collection: "bukhari",
    hadith_number: 2522,
    grade: "sahih",
    difficulty: "hard",
    topic: "emancipation",
  },
  {
    id: 129,
    arabic_text: "لَا يُجْمَعُ بَيْنَ الْمَرْأَةِ وَعَمَّتِهَا وَلَا بَيْنَ الْمَرْأَةِ وَخَالَتِهَا",
    english_text: "A woman should not be married simultaneously with her paternal aunt or her maternal aunt.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 5109,
    grade: "sahih",
    difficulty: "hard",
    topic: "marriage prohibition",
  },
  {
    id: 130,
    arabic_text: "الذَّهَبُ بِالذَّهَبِ وَالْفِضَّةُ بِالْفِضَّةِ وَالْبُرُّ بِالْبُرِّ وَالشَّعِيرُ بِالشَّعِيرِ وَالتَّمْرُ بِالتَّمْرِ وَالْمِلْحُ بِالْمِلْحِ مِثْلًا بِمِثْلٍ سَوَاءً بِسَوَاءٍ يَدًا بِيَدٍ",
    english_text: "Gold for gold, silver for silver, wheat for wheat, barley for barley, dates for dates, salt for salt — like for like, equal for equal, hand to hand.",
    narrator_en: "Ubadah ibn As-Samit",
    collection: "muslim",
    hadith_number: 1587,
    grade: "sahih",
    difficulty: "hard",
    topic: "ribawi items",
  },
  {
    id: 131,
    arabic_text: "لَا يَبِيعُ حَاضِرٌ لِبَادٍ",
    english_text: "A resident should not sell on behalf of a desert-dweller (a settled middleman should not exploit the ignorance of newcomers).",
    narrator_en: "Abdullah ibn Umar",
    collection: "bukhari",
    hadith_number: 2158,
    grade: "sahih",
    difficulty: "hard",
    topic: "market regulation",
  },
  {
    id: 132,
    arabic_text: "نَهَى رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ عَنِ النَّجْشِ",
    english_text: "The Messenger of Allah ﷺ forbade najash (artificially inflating prices through fake bidding).",
    narrator_en: "Abdullah ibn Umar",
    collection: "bukhari",
    hadith_number: 2142,
    grade: "sahih",
    difficulty: "hard",
    topic: "market ethics",
  },
  {
    id: 133,
    arabic_text: "لَا تَلَقَّوُا الرُّكْبَانَ وَلَا يَبِعْ بَعْضُكُمْ عَلَى بَيْعِ بَعْضٍ",
    english_text: "Do not go out to meet the riders (to buy their goods before they reach the market), and do not sell over the sale of one another.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 2150,
    grade: "sahih",
    difficulty: "hard",
    topic: "fair trade",
  },
  {
    id: 134,
    arabic_text: "مَنْ أَسْلَمَ عَلَى شَيْءٍ فَهُوَ لَهُ",
    english_text: "Whoever accepts Islam while possessing something, it remains his.",
    narrator_en: "Abdullah ibn Abbas",
    collection: "abu_dawud",
    hadith_number: 3067,
    grade: "hasan",
    difficulty: "hard",
    topic: "property rights",
  },
  {
    id: 135,
    arabic_text: "لَا يَحِلُّ مَالُ امْرِئٍ مُسْلِمٍ إِلَّا بِطِيبِ نَفْسٍ مِنْهُ",
    english_text: "It is not permissible to take the wealth of a Muslim except with his willing consent.",
    narrator_en: "Abu Hurairah",
    collection: "abu_dawud",
    hadith_number: 3535,
    grade: "sahih",
    difficulty: "hard",
    topic: "property rights",
  },
  {
    id: 136,
    arabic_text: "فِي الرِّكَازِ الْخُمُسُ",
    english_text: "In buried treasure (rikaz), one-fifth (is due as zakat).",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 1499,
    grade: "sahih",
    difficulty: "hard",
    topic: "zakat",
  },
  {
    id: 137,
    arabic_text: "لَيْسَ فِيمَا دُونَ خَمْسِ أَوَاقٍ صَدَقَةٌ وَلَيْسَ فِيمَا دُونَ خَمْسِ ذَوْدٍ صَدَقَةٌ وَلَيْسَ فِيمَا دُونَ خَمْسَةِ أَوْسُقٍ صَدَقَةٌ",
    english_text: "There is no zakat on less than five awaq of silver, nor on less than five camels, nor on less than five wasq of grain.",
    narrator_en: "Abu Said Al-Khudri",
    collection: "bukhari",
    hadith_number: 1459,
    grade: "sahih",
    difficulty: "hard",
    topic: "zakat thresholds",
  },
  {
    id: 138,
    arabic_text: "تُعْرَضُ الْفِتَنُ عَلَى الْقُلُوبِ كَالْحَصِيرِ عُودًا عُودًا فَأَيُّ قَلْبٍ أُشْرِبَهَا نُكِتَ فِيهِ نُكْتَةٌ سَوْدَاءُ",
    english_text: "Trials are presented to the hearts like a reed mat, woven stick by stick. Any heart that absorbs them gets a black spot imprinted on it.",
    narrator_en: "Hudhayfah ibn Al-Yaman",
    collection: "muslim",
    hadith_number: 144,
    grade: "sahih",
    difficulty: "hard",
    topic: "trials",
  },
  {
    id: 139,
    arabic_text: "عَلَيْكُمْ بِسُنَّتِي وَسُنَّةِ الْخُلَفَاءِ الرَّاشِدِينَ الْمَهْدِيِّينَ عَضُّوا عَلَيْهَا بِالنَّوَاجِذِ",
    english_text: "Hold fast to my Sunnah and the way of the rightly-guided caliphs. Bite onto it with your molars.",
    narrator_en: "Al-Irbad ibn Sariyah",
    collection: "tirmidhi",
    hadith_number: 2676,
    grade: "sahih",
    difficulty: "hard",
    topic: "sunnah",
  },
  {
    id: 140,
    arabic_text: "مَا تَرَكْتُ بَعْدِي فِتْنَةً أَضَرَّ عَلَى الرِّجَالِ مِنَ النِّسَاءِ",
    english_text: "I have not left behind me a trial more harmful to men than women.",
    narrator_en: "Usamah ibn Zayd",
    collection: "bukhari",
    hadith_number: 5096,
    grade: "sahih",
    difficulty: "hard",
    topic: "trials",
  },
  {
    id: 141,
    arabic_text: "يَتَقَارَبُ الزَّمَانُ وَيَنْقُصُ الْعِلْمُ وَتَظْهَرُ الْفِتَنُ وَيُلْقَى الشُّحُّ وَيَكْثُرُ الْهَرْجُ",
    english_text: "Time will pass rapidly, knowledge will decrease, trials will appear, miserliness will spread, and killing will increase.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 1036,
    grade: "sahih",
    difficulty: "hard",
    topic: "end times",
  },
  {
    id: 142,
    arabic_text: "لَا تَقُومُ السَّاعَةُ حَتَّى يُقْبَضَ الْعِلْمُ وَتَكْثُرَ الزَّلَازِلُ وَيَتَقَارَبَ الزَّمَانُ",
    english_text: "The Hour will not come until knowledge is taken away, earthquakes increase, and time passes quickly.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 1036,
    grade: "sahih",
    difficulty: "hard",
    topic: "signs of the hour",
  },
  {
    id: 143,
    arabic_text: "لَا تَزَالُ طَائِفَةٌ مِنْ أُمَّتِي ظَاهِرِينَ عَلَى الْحَقِّ لَا يَضُرُّهُمْ مَنْ خَذَلَهُمْ حَتَّى يَأْتِيَ أَمْرُ اللَّهِ",
    english_text: "There will always remain a group from my ummah manifest upon the truth. They will not be harmed by those who forsake them until the command of Allah comes.",
    narrator_en: "Muawiyah ibn Abi Sufyan",
    collection: "muslim",
    hadith_number: 1920,
    grade: "sahih",
    difficulty: "hard",
    topic: "ummah",
  },
  {
    id: 144,
    arabic_text: "أَنَّ النَّبِيَّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَهَى عَنْ كُلِّ ذِي نَابٍ مِنَ السِّبَاعِ وَعَنْ كُلِّ ذِي مِخْلَبٍ مِنَ الطَّيْرِ",
    english_text: "The Prophet ﷺ forbade eating every predatory animal with fangs and every bird with talons.",
    narrator_en: "Abdullah ibn Abbas",
    collection: "muslim",
    hadith_number: 1934,
    grade: "sahih",
    difficulty: "hard",
    topic: "halal food",
  },
  {
    id: 145,
    arabic_text: "إِنَّ أَوَّلَ مَا يُحَاسَبُ بِهِ الْعَبْدُ يَوْمَ الْقِيَامَةِ مِنْ عَمَلِهِ صَلَاتُهُ",
    english_text: "The first thing a servant will be held accountable for on the Day of Judgment from his deeds is his prayer.",
    narrator_en: "Abu Hurairah",
    collection: "tirmidhi",
    hadith_number: 413,
    grade: "sahih",
    difficulty: "hard",
    topic: "accountability",
  },
  {
    id: 146,
    arabic_text: "إِذَا اجْتَهَدَ الْحَاكِمُ فَأَخْطَأَ فَلَهُ أَجْرٌ وَإِذَا اجْتَهَدَ فَأَصَابَ فَلَهُ أَجْرَانِ",
    english_text: "When a judge strives and makes an error, he gets one reward. When he strives and is correct, he gets two rewards.",
    narrator_en: "Abu Hurairah",
    collection: "bukhari",
    hadith_number: 7352,
    grade: "sahih",
    difficulty: "hard",
    topic: "judicial effort",
  },
  {
    id: 147,
    arabic_text: "أَنَّ النَّبِيَّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ رَجَمَ مَاعِزًا وَالْغَامِدِيَّةَ",
    english_text: "The Prophet ﷺ carried out the legal punishment on Ma'iz and the Ghamidiyyah (after their own confessions and insistence).",
    narrator_en: "Jabir ibn Abdullah",
    collection: "muslim",
    hadith_number: 1691,
    grade: "sahih",
    difficulty: "hard",
    topic: "hudud",
  },
  {
    id: 148,
    arabic_text: "ادْرَءُوا الْحُدُودَ عَنِ الْمُسْلِمِينَ مَا اسْتَطَعْتُمْ فَإِنْ كَانَ لَهُ مَخْرَجٌ فَخَلُّوا سَبِيلَهُ",
    english_text: "Avert legal punishments from Muslims as much as possible. If there is a way out for him, let him go.",
    narrator_en: "Aisha",
    collection: "tirmidhi",
    hadith_number: 1424,
    grade: "hasan",
    difficulty: "hard",
    topic: "hudud leniency",
  },
  {
    id: 149,
    arabic_text: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يَكُونَ هَوَاهُ تَبَعًا لِمَا جِئْتُ بِهِ",
    english_text: "None of you truly believes until his desires are in accordance with what I have brought.",
    narrator_en: "Abdullah ibn Amr",
    collection: "tirmidhi",
    hadith_number: 2614,
    grade: "hasan",
    difficulty: "hard",
    topic: "submission",
  },
  {
    id: 150,
    arabic_text: "لَا تَجْتَمِعُ أُمَّتِي عَلَى ضَلَالَةٍ",
    english_text: "My ummah will not unite upon misguidance.",
    narrator_en: "Abdullah ibn Umar",
    collection: "tirmidhi",
    hadith_number: 2167,
    grade: "hasan",
    difficulty: "hard",
    topic: "ijma",
  },
];

export function getHadithsByDifficulty(level: "easy" | "medium" | "hard"): Hadith[] {
  return CURATED_HADITHS.filter((h) => h.difficulty === level);
}
