export interface SeerahEvent {
  id: number;
  year: string;
  hijri_year?: string;
  title_hi: string;
  title_hinglish: string;
  title_en: string;
  description_hi: string;
  description_hinglish: string;
  description_en: string;
  category: "early_life" | "prophethood" | "makkah" | "madinah" | "final_years";
}

export const SEERAH_EVENTS: SeerahEvent[] = [
  {
    id: 1,
    year: "570 CE",
    title_hi: "पैगंबर ﷺ का जन्म",
    title_hinglish: "Paigambar ﷺ ki Paidaish",
    title_en: "Birth of the Prophet ﷺ",
    description_hi: "मक्का में बनू हाशिम कबीले में रबीउल अव्वल में पैदा हुए। पिता अब्दुल्लाह का इंतकाल पहले ही हो चुका था।",
    description_hinglish: "Makkah mein Banu Hashim qabile mein Rabi ul-Awwal mein paida hue. Walid Abdullah ka inteqal pehle hi ho chuka tha.",
    description_en: "Born in Makkah in the clan of Banu Hashim during Rabi ul-Awwal. His father Abdullah had already passed away.",
    category: "early_life",
  },
  {
    id: 2,
    year: "576 CE",
    title_hi: "माँ आमिना का इंतकाल",
    title_hinglish: "Maa Amina ka Inteqal",
    title_en: "Death of Mother Amina",
    description_hi: "6 साल की उम्र में माँ आमिना का इंतकाल हुआ। इसके बाद दादा अब्दुल मुत्तलिब ने पालन किया।",
    description_hinglish: "6 saal ki umar mein maa Amina ka inteqal hua. Iske baad dada Abdul Muttalib ne paalan kiya.",
    description_en: "At age 6, his mother Amina passed away. He was then raised by his grandfather Abdul Muttalib.",
    category: "early_life",
  },
  {
    id: 3,
    year: "578 CE",
    title_hi: "दादा अब्दुल मुत्तलिब का इंतकाल",
    title_hinglish: "Dada Abdul Muttalib ka Inteqal",
    title_en: "Death of Grandfather Abdul Muttalib",
    description_hi: "8 साल की उम्र में दादा का इंतकाल। चाचा अबू तालिब ने उनकी परवरिश संभाली।",
    description_hinglish: "8 saal ki umar mein dada ka inteqal. Chacha Abu Talib ne unki parwarish sambhaali.",
    description_en: "At age 8, his grandfather passed away. His uncle Abu Talib took over his guardianship.",
    category: "early_life",
  },
  {
    id: 4,
    year: "583 CE",
    title_hi: "शाम (सीरिया) का सफर",
    title_hinglish: "Shaam (Syria) ka Safar",
    title_en: "Journey to Syria",
    description_hi: "चाचा अबू तालिब के साथ व्यापारिक यात्रा। राहिब बहीरा ने नबुव्वत की निशानियां पहचानीं।",
    description_hinglish: "Chacha Abu Talib ke saath tijarati yatra. Rahib Bahira ne nubuwwat ki nishaniyan pehchaanin.",
    description_en: "Traveled with uncle Abu Talib on a trade journey. The monk Bahira recognized signs of prophethood.",
    category: "early_life",
  },
  {
    id: 5,
    year: "595 CE",
    title_hi: "हज़रत ख़दीजा ؓ से निकाह",
    title_hinglish: "Hazrat Khadija ؓ se Nikaah",
    title_en: "Marriage to Khadijah ؓ",
    description_hi: "25 साल की उम्र में हज़रत ख़दीजा ؓ से शादी हुई। वह एक सम्मानित व्यापारी महिला थीं।",
    description_hinglish: "25 saal ki umar mein Hazrat Khadija ؓ se shaadi hui. Woh ek sammanit tijarat karne wali khatoon thin.",
    description_en: "At age 25, married Khadijah ؓ, a respected businesswoman. She became his greatest supporter.",
    category: "early_life",
  },
  {
    id: 6,
    year: "605 CE",
    title_hi: "काबा की तामीर और हजर-ए-अस्वद",
    title_hinglish: "Kaaba ki Taameer aur Hajar-e-Aswad",
    title_en: "Rebuilding of the Kaaba & the Black Stone",
    description_hi: "कबीलों के बीच हजर-ए-अस्वद रखने के विवाद को हल किया। सबने आप ﷺ को 'अल-अमीन' माना।",
    description_hinglish: "Qabilon ke beech Hajar-e-Aswad rakhne ke vivaad ko hal kiya. Sabne Aap ﷺ ko 'Al-Ameen' maana.",
    description_en: "Resolved the dispute over placing the Black Stone during Kaaba reconstruction. Known as 'Al-Ameen' (The Trustworthy).",
    category: "early_life",
  },
  {
    id: 7,
    year: "610 CE",
    hijri_year: "Before Hijrah",
    title_hi: "पहली वह्य — ग़ारे हिरा में",
    title_hinglish: "Pehli Wahi — Ghaar-e-Hira mein",
    title_en: "First Revelation in Cave Hira",
    description_hi: "40 साल की उम्र में जिब्रईल अलैहिस्सलाम ने 'इक़रा' की आयतें नाज़िल कीं। नबुव्वत का आग़ाज़।",
    description_hinglish: "40 saal ki umar mein Jibrael AS ne 'Iqra' ki aayatein naazil keen. Nubuwwat ka aaghaaz.",
    description_en: "At age 40, Angel Jibreel revealed the first verses 'Iqra' (Read). The beginning of prophethood.",
    category: "prophethood",
  },
  {
    id: 8,
    year: "610 CE",
    title_hi: "पहले मुसलमान",
    title_hinglish: "Pehle Musalman",
    title_en: "First Muslims",
    description_hi: "हज़रत ख़दीजा ؓ, हज़रत अबू बक्र ؓ, हज़रत अली ؓ और ज़ैद बिन हारिसा ؓ ने सबसे पहले इस्लाम क़बूल किया।",
    description_hinglish: "Hazrat Khadija ؓ, Hazrat Abu Bakr ؓ, Hazrat Ali ؓ aur Zaid bin Harisa ؓ ne sabse pehle Islam qabool kiya.",
    description_en: "Khadijah ؓ, Abu Bakr ؓ, Ali ؓ, and Zaid bin Harithah ؓ were among the first to accept Islam.",
    category: "prophethood",
  },
  {
    id: 9,
    year: "613 CE",
    title_hi: "खुली दावत का आग़ाज़",
    title_hinglish: "Khuli Dawat ka Aaghaaz",
    title_en: "Public Preaching Begins",
    description_hi: "तीन साल की खुफिया दावत के बाद अल्लाह के हुक्म से खुली तब्लीग़ शुरू हुई।",
    description_hinglish: "Teen saal ki khufiya dawat ke baad Allah ke hukm se khuli tableegh shuru hui.",
    description_en: "After three years of secret preaching, public proclamation of Islam began by Allah's command.",
    category: "makkah",
  },
  {
    id: 10,
    year: "615 CE",
    title_hi: "हबशा (अबीसीनिया) की हिजरत",
    title_hinglish: "Habsha (Abyssinia) ki Hijrat",
    title_en: "Migration to Abyssinia",
    description_hi: "क़ुरैश के ज़ुल्म से बचने के लिए कुछ मुसलमान हबशा चले गए। नजाशी बादशाह ने पनाह दी।",
    description_hinglish: "Quraish ke zulm se bachne ke liye kuch Musalman Habsha chale gaye. Najashi badshah ne panaah di.",
    description_en: "Some Muslims migrated to Abyssinia to escape Quraysh persecution. King Negus granted them refuge.",
    category: "makkah",
  },
  {
    id: 11,
    year: "616 CE",
    title_hi: "हज़रत हमज़ा ؓ और उमर ؓ का इस्लाम",
    title_hinglish: "Hazrat Hamza ؓ aur Umar ؓ ka Islam",
    title_en: "Hamza ؓ and Umar ؓ Accept Islam",
    description_hi: "दो ताक़तवर शख़्सियतों ने इस्लाम क़बूल किया, जिससे मुसलमानों को बहुत ताक़त मिली।",
    description_hinglish: "Do taaqatwar shakhsiyaton ne Islam qabool kiya, jisse Musalmano ko bahut taaqat mili.",
    description_en: "Two powerful figures accepted Islam, greatly strengthening the Muslim community.",
    category: "makkah",
  },
  {
    id: 12,
    year: "616-619 CE",
    title_hi: "शिअब-ए-अबू तालिब — बॉयकॉट",
    title_hinglish: "Shi'b-e-Abu Talib — Boycott",
    title_en: "Boycott in the Valley of Abu Talib",
    description_hi: "क़ुरैश ने बनू हाशिम का सामाजिक और आर्थिक बहिष्कार किया। तीन साल तक भूख और तकलीफ सहनी पड़ी।",
    description_hinglish: "Quraish ne Banu Hashim ka samaaji aur maali boycott kiya. Teen saal tak bhookh aur takleef sehni padi.",
    description_en: "Quraysh imposed a social and economic boycott on Banu Hashim lasting three years of hardship.",
    category: "makkah",
  },
  {
    id: 13,
    year: "619 CE",
    title_hi: "आम-उल-हुज़्न — ग़म का साल",
    title_hinglish: "Aam-ul-Huzn — Gham ka Saal",
    title_en: "Year of Sorrow",
    description_hi: "हज़रत ख़दीजा ؓ और चाचा अबू तालिब दोनों का इंतकाल हुआ। बहुत दुखद वक़्त।",
    description_hinglish: "Hazrat Khadija ؓ aur chacha Abu Talib dono ka inteqal hua. Bahut dukhad waqt.",
    description_en: "Both Khadijah ؓ and Abu Talib passed away, a period of immense grief for the Prophet ﷺ.",
    category: "makkah",
  },
  {
    id: 14,
    year: "619 CE",
    title_hi: "ताइफ़ का सफ़र",
    title_hinglish: "Taif ka Safar",
    title_en: "Journey to Taif",
    description_hi: "दावत के लिए ताइफ़ गए लेकिन लोगों ने पत्थर मारे। आप ﷺ ने फिर भी उनके लिए दुआ की।",
    description_hinglish: "Dawat ke liye Taif gaye lekin logon ne patthar maare. Aap ﷺ ne phir bhi unke liye dua ki.",
    description_en: "Traveled to Taif to preach but was stoned by its people. He ﷺ still prayed for their guidance.",
    category: "makkah",
  },
  {
    id: 15,
    year: "620 CE",
    hijri_year: "Before Hijrah",
    title_hi: "इसरा और मेराज — रात की यात्रा",
    title_hinglish: "Isra aur Me'raj — Raat ki Yatra",
    title_en: "The Night Journey & Ascension",
    description_hi: "मक्का से बैतुल मक़दिस (इसरा) और फिर सातों आसमानों के ज़रिए मेराज। पांच वक़्त की नमाज़ फ़र्ज़ हुई।",
    description_hinglish: "Makkah se Baitul Maqdis (Isra) aur phir saaton aasmaano ke zariye Me'raj. Paanch waqt ki namaz farz hui.",
    description_en: "Night journey from Makkah to Jerusalem (Isra) and ascension through the heavens (Mi'raj). Five daily prayers were ordained.",
    category: "makkah",
  },
  {
    id: 16,
    year: "622 CE",
    hijri_year: "1 AH",
    title_hi: "हिजरत — मदीना की ओर",
    title_hinglish: "Hijrat — Madinah ki Taraf",
    title_en: "The Hijrah to Madinah",
    description_hi: "मक्का छोड़कर मदीना की तरफ हिजरत। इस्लामी कैलेंडर (हिजरी) की शुरुआत।",
    description_hinglish: "Makkah chhodkar Madinah ki taraf hijrat. Islami calendar (Hijri) ki shuru'aat.",
    description_en: "Migration from Makkah to Madinah, marking the start of the Islamic (Hijri) calendar.",
    category: "madinah",
  },
  {
    id: 17,
    year: "622 CE",
    hijri_year: "1 AH",
    title_hi: "मस्जिद-ए-नबवी की तामीर",
    title_hinglish: "Masjid-e-Nabawi ki Taameer",
    title_en: "Construction of Masjid al-Nabawi",
    description_hi: "मदीना पहुंचकर सबसे पहले मस्जिद बनाई। यह इल्म, इबादत और समाज का केंद्र बनी।",
    description_hinglish: "Madinah pahunchkar sabse pehle masjid banayi. Yeh ilm, ibaadat aur samaaj ka markaz bani.",
    description_en: "Upon arrival in Madinah, the Prophet's Mosque was built as a center for worship, learning, and community.",
    category: "madinah",
  },
  {
    id: 18,
    year: "622 CE",
    hijri_year: "1 AH",
    title_hi: "मीसाक़-ए-मदीना",
    title_hinglish: "Meesaq-e-Madinah",
    title_en: "Constitution of Madinah",
    description_hi: "मदीना के सभी क़बीलों के बीच एक लिखित समझौता किया गया, जिसे इस्लामी इतिहास में एक अहम सामाजिक दस्तावेज़ माना जाता है।",
    description_hinglish: "Madinah ke sabhi qabilon ke beech ek likhit samjhauta kiya gaya, jise Islami tareekh mein ek aham samaaji dastavez maana jata hai.",
    description_en: "A written charter was established between the tribes of Madinah, often treated as an important civic document in Islamic history.",
    category: "madinah",
  },
  {
    id: 19,
    year: "624 CE",
    hijri_year: "2 AH",
    title_hi: "ग़ज़्वा-ए-बद्र",
    title_hinglish: "Ghazwa-e-Badr",
    title_en: "Battle of Badr",
    description_hi: "313 मुसलमानों ने 1000 क़ुरैशी फ़ौज को हराया। इस्लाम की पहली बड़ी जंग में फ़तह।",
    description_hinglish: "313 Musalmano ne 1000 Qureshi fauj ko haraaya. Islam ki pehli badi jang mein fatah.",
    description_en: "313 Muslims defeated an army of 1000 Quraysh. The first major victory of Islam.",
    category: "madinah",
  },
  {
    id: 20,
    year: "625 CE",
    hijri_year: "3 AH",
    title_hi: "ग़ज़्वा-ए-उहुद",
    title_hinglish: "Ghazwa-e-Uhud",
    title_en: "Battle of Uhud",
    description_hi: "उहुद पहाड़ के पास लड़ी गई। हज़रत हमज़ा ؓ शहीद हुए। सब्र और अनुशासन का सबक।",
    description_hinglish: "Uhud pahaad ke paas ladi gayi. Hazrat Hamza ؓ shaheed hue. Sabr aur anushasan ka sabaq.",
    description_en: "Fought near Mount Uhud. Hamza ؓ was martyred. A lesson in patience and discipline.",
    category: "madinah",
  },
  {
    id: 21,
    year: "627 CE",
    hijri_year: "5 AH",
    title_hi: "ग़ज़्वा-ए-ख़ंदक़ (अहज़ाब)",
    title_hinglish: "Ghazwa-e-Khandaq (Ahzab)",
    title_en: "Battle of the Trench",
    description_hi: "सलमान फ़ारसी ؓ की तजवीज़ पर खंदक खोदी गई। 10,000 की दुश्मन फ़ौज को रोका गया।",
    description_hinglish: "Salman Farsi ؓ ki tajweez par khandaq khodi gayi. 10,000 ki dushman fauj ko roka gaya.",
    description_en: "A trench was dug on Salman al-Farsi's ؓ suggestion, repelling a 10,000-strong enemy coalition.",
    category: "madinah",
  },
  {
    id: 22,
    year: "628 CE",
    hijri_year: "6 AH",
    title_hi: "सुल्ह-ए-हुदैबिया",
    title_hinglish: "Sulah-e-Hudaibiya",
    title_en: "Treaty of Hudaybiyyah",
    description_hi: "क़ुरैश के साथ 10 साल की सुलह। क़ुरआन ने इसे 'फ़तह-ए-मुबीन' (खुली जीत) कहा।",
    description_hinglish: "Quraish ke saath 10 saal ki sulah. Quran ne ise 'Fatah-e-Mubeen' (khuli jeet) kaha.",
    description_en: "A 10-year peace treaty with Quraysh. The Quran called it a 'clear victory' (Fatah Mubeen).",
    category: "madinah",
  },
  {
    id: 23,
    year: "628 CE",
    hijri_year: "7 AH",
    title_hi: "ख़ैबर की फ़तह",
    title_hinglish: "Khaibar ki Fatah",
    title_en: "Conquest of Khaybar",
    description_hi: "ख़ैबर के किले फ़तह हुए। हज़रत अली ؓ ने किले का दरवाज़ा खोला।",
    description_hinglish: "Khaibar ke qile fatah hue. Hazrat Ali ؓ ne qile ka darwaza khola.",
    description_en: "The fortress of Khaybar was conquered. Ali ؓ famously breached the fort's gate.",
    category: "madinah",
  },
  {
    id: 24,
    year: "629 CE",
    hijri_year: "7 AH",
    title_hi: "बादशाहों को इस्लाम की दावत",
    title_hinglish: "Badshahon ko Islam ki Dawat",
    title_en: "Letters to World Leaders",
    description_hi: "रोम, फ़ारस, मिस्र और हबशा के बादशाहों को इस्लाम की दावत के ख़त भेजे।",
    description_hinglish: "Rome, Faras, Misr aur Habsha ke badshahon ko Islam ki dawat ke khat bheje.",
    description_en: "Letters inviting to Islam were sent to the rulers of Rome, Persia, Egypt, and Abyssinia.",
    category: "madinah",
  },
  {
    id: 25,
    year: "630 CE",
    hijri_year: "8 AH",
    title_hi: "फ़तह मक्का",
    title_hinglish: "Fatah Makkah",
    title_en: "Conquest of Makkah",
    description_hi: "10,000 मुसलमानों ने बिना खून बहाए मक्का फ़तह किया। काबा से बुत साफ़ किए। आम माफ़ी का ऐलान।",
    description_hinglish: "10,000 Musalmano ne bina khoon bahaaye Makkah fatah kiya. Kaaba se but saaf kiye. Aam maafi ka elaan.",
    description_en: "10,000 Muslims entered Makkah peacefully. Idols were removed from the Kaaba. General amnesty was declared.",
    category: "final_years",
  },
  {
    id: 26,
    year: "630 CE",
    hijri_year: "8 AH",
    title_hi: "ग़ज़्वा-ए-हुनैन",
    title_hinglish: "Ghazwa-e-Hunain",
    title_en: "Battle of Hunayn",
    description_hi: "फ़तह मक्का के बाद हवाज़िन और सक़ीफ़ क़बीलों से जंग। शुरू में मुश्किल, फिर फ़तह।",
    description_hinglish: "Fatah Makkah ke baad Hawazin aur Saqeef qabilon se jang. Shuru mein mushkil, phir fatah.",
    description_en: "After Makkah's conquest, battle against Hawazin and Thaqif tribes. Initially difficult, then victorious.",
    category: "final_years",
  },
  {
    id: 27,
    year: "630 CE",
    hijri_year: "9 AH",
    title_hi: "ग़ज़्वा-ए-तबूक",
    title_hinglish: "Ghazwa-e-Tabuk",
    title_en: "Expedition to Tabuk",
    description_hi: "रोमन ख़तरे के ख़िलाफ़ उत्तर की ओर फ़ौजी मुहिम। ईमान की सबसे बड़ी आज़माइश।",
    description_hinglish: "Roman khatre ke khilaaf uttar ki ore fauji muhim. Imaan ki sabse badi aazmaish.",
    description_en: "Military expedition northward against a potential Roman threat. A great test of faith.",
    category: "final_years",
  },
  {
    id: 28,
    year: "632 CE",
    hijri_year: "10 AH",
    title_hi: "हज्जतुल विदा — आख़िरी हज",
    title_hinglish: "Hajjatul Wida — Aakhri Hajj",
    title_en: "The Farewell Hajj",
    description_hi: "1 लाख से ज़्यादा मुसलमानों के साथ आख़िरी हज। अरफ़ात में ऐतिहासिक ख़ुतबा दिया।",
    description_hinglish: "1 lakh se zyada Musalmano ke saath aakhri Hajj. Arafat mein aitihaasik khutba diya.",
    description_en: "Performed the final Hajj with over 100,000 Muslims. Delivered the historic Farewell Sermon at Arafat.",
    category: "final_years",
  },
  {
    id: 29,
    year: "632 CE",
    hijri_year: "10 AH",
    title_hi: "ख़ुतबा हज्जतुल विदा",
    title_hinglish: "Khutba Hajjatul Wida",
    title_en: "The Farewell Sermon",
    description_hi: "इंसानी हक़ूक, बराबरी और इंसाफ़ का ऐलान। 'तुम सब आदम की औलाद हो।'",
    description_hinglish: "Insani haqooq, barabari aur insaaf ka elaan. 'Tum sab Adam ki aulaad ho.'",
    description_en: "Proclaimed human rights, equality, and justice. 'All of you are from Adam, and Adam was from dust.'",
    category: "final_years",
  },
  {
    id: 30,
    year: "632 CE",
    hijri_year: "11 AH",
    title_hi: "पैगंबर ﷺ का विसाल",
    title_hinglish: "Paigambar ﷺ ka Wisaal",
    title_en: "Passing of the Prophet ﷺ",
    description_hi: "12 रबीउल अव्वल को 63 साल की उम्र में मदीना में इंतकाल। मस्जिद-ए-नबवी में दफ़न।",
    description_hinglish: "12 Rabi ul-Awwal ko 63 saal ki umar mein Madinah mein inteqal. Masjid-e-Nabawi mein dafan.",
    description_en: "Passed away on 12th Rabi ul-Awwal at age 63 in Madinah. Buried in Masjid al-Nabawi.",
    category: "final_years",
  },
];
